### PR TITLE
Bias+GeLU example in C++

### LINKED ISSUE #426: Bias+Gelu Fusion from Bert Model fails in Codegen
## 🐛 Bug

Perhaps there is a bug related to broadcast, with bias, and fp16 usage.  It is hard to tell more than this for now without throwing this threw the debugger.  At the point of failure, there is no ability to simply print the Fusion IR.

```
graph(%bias.1 : Tensor,
      %y.1 : Tensor):
  %2 : float = prim::Constant[value=0.5]() # test.py:19:16
  %3 : float = prim::Constant[value=1.]() # test.py:19:23
  %4 : float = prim::Constant[value=0.79788455999999996]() # test.py:19:40
  %5 : int = prim::Constant[value=1]() # test.py:19:58
  %6 : float = prim::Constant[value=0.044714999999999998]() # test.py:19:62
  %17 : Tensor = prim::profile[profiled_type=Half(4096:1, requires_grad=1, device=cuda:0)](%bias.1)
  %18 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%y.1)
  %x.1 : Tensor = aten::add(%17, %18, %5) # test.py:18:8
  %19 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%x.1)
  %8 : Tensor = aten::mul(%19, %2) # test.py:19:12
  %20 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%x.1)
  %9 : Tensor = aten::mul(%20, %4) # <string>:3:9
  %21 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%x.1)
  %10 : Tensor = aten::mul(%21, %6) # <string>:3:9
  %22 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%10)
  %23 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%x.1)
  %11 : Tensor = aten::mul(%22, %23) # test.py:19:62
  %24 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%11)
  %12 : Tensor = aten::add(%24, %5, %5) # <string>:5:9
  %25 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%9)
  %26 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%12)
  %13 : Tensor = aten::mul(%25, %26) # test.py:19:40
  %27 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%13)
  %14 : Tensor = aten::tanh(%27) # test.py:19:29
  %28 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%14)
  %15 : Tensor = aten::add(%28, %3, %5) # <string>:5:9
  %29 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%8)
  %30 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%15)
  %16 : Tensor = aten::mul(%29, %30) # test.py:19:12
  %31 : Tensor = prim::profile[profiled_type=Half(6:2097152, 512:4096, 4096:1, requires_grad=1, device=cuda:0)](%16)
   = prim::profile()
  return (%31)

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    outputs = bias_gelu_impl(inputs, bias)
  File "test.py", line 37, in forward
    return bias_gelu(bias, input)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: *new_compute_at_domain_ == *td INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/compute_at.cpp":98, please report a bug to PyTorch. TensorDomain, [ iS208{( ceilDiv(( ceilDiv(i1, 128) ), 1) )}, iS209{1}, iS207{128} ], does not match with the previously set domain of T1[ iS208{( ceilDiv(( ceilDiv(i1, 128) ), 1) )}, iS209{1}, iS207{128} ] compute_at( T4, 3 ), which is [ iS204{( ceilDiv(( ceilDiv(i1, 128) ), 1) )}, iS205{1}, iS203{128} ]
```

## To Reproduce

Script to reproduce: (note this doesn't fail if FP32 I/O is used)

```
import torch                                                                                                                                                                            
import os                                                                                                                                                                               
                                                                                                                                                                                        
torch._C._jit_set_nvfuser_enabled(True)
torch._C._jit_set_texpr_fuser_enabled(False)                                                                                                                                                 
torch._C._jit_set_profiling_executor(True)                                                                                                                                              
torch._C._jit_set_profiling_mode(True)                                                                                                                                                  
torch._C._jit_override_can_fuse_on_cpu(False)                                                                                                                                           
torch._C._jit_override_can_fuse_on_gpu(False)                                                                                                                                           
torch._C._jit_set_bailout_depth(20)                                                                                                                                                     
                                                                                                                                                                                        
os.environ['PYTORCH_CUDA_FUSER_DEBUG'] = '1'                                                                                                                                            
                                                                                                                                                                                        
# this function is tanh approximation of gelu                                                                                                                                           
# actual gelu is:                                                                                                                                                                       
# x * 0.5 * (1.0 + torch.erf(x * 0.70710678))                                                                                                                                           
@torch.jit.script                                                                                                                                                                       
def bias_gelu(bias, y):                                                                                                                                                                 
    x = bias + y                                                                                                                                                                        
    return  x * 0.5 * (1.0 + torch.tanh(0.79788456 * x * (1 + 0.044715 * x * x)))                                                                                                       
                                                                                                                                                                                        
# gradient of tanh approximation of gelu                                                                                                                                                
# gradient of actual gelu is:                                                                                                                                                           
# 0.5 * (1. + torch.erf(x * 0.70710678)) + 0.3989423 * x * torch.exp(-0.5 * x * x)                                                                                                      
@torch.jit.script                                                                                                                                                                       
def bias_gelu_back(g, bias, y):                                                                                                                                                         
    x = bias + y                                                                                                                                                                        
    tanh_out = torch.tanh(0.79788456 * x * (1 + 0.044715 * x * x))                                                                                                                      
    # sqrt(2/pi) * 3 * 0.044715 -> 0.1070322243                                                                                                                                         
    ff = 0.5 * x * ((1 - tanh_out * tanh_out) * (0.79788456 + 0.1070322243 * x * x)) + 0.5 * (1 + tanh_out)                                                                             
    return ff*g                                                                                                                                                                         
                                                                                                                                                                                        
class GeLUFunction(torch.autograd.Function):                                                                                                                                            
    @staticmethod                                                                                                                                                                       
    # bias is an optional argument                                                                                                                                                      
    def forward(ctx, input, bias):                                                                                                                                                      
        ctx.save_for_backward(input, bias)                                                                                                                                              
        return bias_gelu(bias, input)                                                                                                                                                   
                                                                                                                                                                                        
    @staticmethod                                                                                                                                                                       
    def backward(ctx, grad_output):                                                                                                                                                     
        input, bias = ctx.saved_tensors                                                                                                                                                 
        tmp = bias_gelu_back(grad_output, bias, input)                                                                                                                                  
        return tmp, tmp                                                                                                                                                                 
                                                                                                                                                                                        
bias_gelu_impl = GeLUFunction.apply                                                                                                                                                     
                                                                                                                                                                                        
input_shape = [6, 512, 4096]                                                                                                                                                            
grad_shape = [6, 512, 4096]                                                                                                                                                             
bias_shape = [4096]                                                                                                                                                                     
                                                                                                                                                                                        
inputs = torch.randn(input_shape, device='cuda', dtype=torch.float16, requires_grad=True)                                                                                               
grads = torch.randn(grad_shape, device='cuda', dtype=torch.float16, requires_grad=True)                                                                                                 
bias = torch.randn(bias_shape, device='cuda', dtype=torch.float16, requires_grad=True)                                                                                                  
                                                                                                                                                                                        
print(bias_gelu.graph_for(bias, inputs))                                                                                                                                                
                                                                                                                                                                                        
for idx in range(0, 5) :                                                                                                                                                                
    outputs = bias_gelu_impl(inputs, bias)                                                                                                                                              
    outputs.backward(grads)
```

### PR DESCRIPTION
**Pull request by naoyam**
This PR adds the reported in #426 by @csarofeen and bias+gelu example fusions in C++.

For the bias+gelu C++ fusions, I used the Python version reported in #426 and tried to faithfully emulate it. For example, we save a lot of intermediate tensors as it happens in the Python version. Let me know if that should be omitted. 

Interestingly, there seems to be a problem with computeAt and those intermediate tensors. See the TODO note in the test.

Closes #426

### CODE REVIEW

**Review by csarofeen — CHANGES_REQUESTED** [review]
Can we use the pointwise scheduler for these examples instead of manually producing the schedule? scheduler.h::scheduleFusion should work for these.

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -8286,6 +8286,246 @@ TEST(NVFuserTest, FusionNonUniqueBroadcastSize_CUDA) {
...
 }
 
+TEST(NVFuserTest, FusionBiasGeluFwd_CUDA) {
+  Fusion fusion;
+  FusionGuard fg(&fusion);
+
+  const float k_079 = 0.79788456;
+  const float k_004 = 0.044715;
+
+  std::vector<TensorView*> tvs;
```
Comment (tlemo) [inline test/cpp/jit/test_gpu.cpp]: what is the reason for using the tvs vector instead of naming each intermediate value? (which would avoid the need for the `// Tn` comments as well)

Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: At some point, I thought that would look nicer, but it doesn't seem so now. I'll simplify this part.

**Comment by naoyam** [comment]
> Can we use the pointwise scheduler for these examples instead of manually producing the schedule? scheduler.h::scheduleFusion should work for these.

Updated. Please see 5c7c24c2b6435a4046a245f44fd0624d265ecf2f.

**Review by csarofeen — APPROVED** [review]
