### PR TITLE
PairwiseRootDomainMap: map a broadcast producer domain and a trivial-reduction consumer domain

### LINKED ISSUE #2080: codegen error: producer->getMemoryType() == MemoryType::Global INTERNAL ASSERT FAILED ... producer->getMemoryType() == MemoryType::Global INTERNAL ASSERT FAILED ... Producer is required to be in Global Memory based on parallelization strategy.
### 🐛 Describe the bug

```
import torch
from torch._C._nvfuser import FusionDefinition, Fusion, DataType

def nvfuser_fusion(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T2 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T3 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguous=[True, True, True, True], dtype=DataType.Float)
    T4 = fd.ops.broadcast_in_dim(T0, output_shape=[96, 1], broadcast_dims=[0])
    T5 = fd.ops.view(T1, original_shape=[96], new_shape=[-1, 1, 1]) 
    T6 = fd.ops.broadcast_in_dim(T2, output_shape=[96, 1], broadcast_dims=[0])
    T7 = fd.ops.broadcast_in_dim(T4, output_shape=[96, 1, 1], broadcast_dims=[0, 1]) 
    T8 = fd.ops.broadcast_in_dim(T5, output_shape=[64, 96, 56, 56], broadcast_dims=[1, 2, 3]) 
    T9 = fd.ops.broadcast_in_dim(T6, output_shape=[96, 1, 1], broadcast_dims=[0, 1]) 
    T10 = fd.ops.broadcast_in_dim(T7, output_shape=[64, 96, 56, 56], broadcast_dims=[1, 2, 3]) 
    T11 = fd.ops.add(T3, T8) 
    T12 = fd.ops.broadcast_in_dim(T9, output_shape=[64, 96, 56, 56], broadcast_dims=[1, 2, 3]) 
    T13 = fd.ops.view(T11, original_shape=[64, 96, 56, 56], new_shape=[64, 1, 96, 3136])
    T14 = fd.ops.var(T13, axes=[2, 3], correction=0, keepdim=False)
    T15 = fd.ops.sum(T13, axes=[2, 3], keepdim=False, dtype=DataType.Null)
    T16 = fd.ops.broadcast_in_dim(T14, output_shape=[64, 1, 1, 1], broadcast_dims=[0, 1]) 
    T17 = fd.ops.broadcast_in_dim(T15, output_shape=[64, 1, 1, 1], broadcast_dims=[0, 1]) 
    S18 = fd.define_constant(1.00000e-05)
    T19 = fd.ops.add(T16, S18)
    S20 = fd.define_constant(301056.)
    T21 = fd.ops.div(T17, S20)
    T22 = fd.ops.rsqrt(T19)
    T23 = fd.ops.broadcast_in_dim(T21, output_shape=[64, 1, 96, 3136], broadcast_dims=[0, 1, 2, 3]) 
    T24 = fd.ops.squeeze(T21, original_shape=[64, 1, 1, 1], dim=3)
    T25 = fd.ops.broadcast_in_dim(T22, output_shape=[64, 1, 96, 3136], broadcast_dims=[0, 1, 2, 3]) 
    T26 = fd.ops.squeeze(T22, original_shape=[64, 1, 1, 1], dim=3)
    T27 = fd.ops.sub(T13, T23)
    T28 = fd.ops.squeeze(T24, original_shape=[64, 1, 1], dim=2)
    T29 = fd.ops.squeeze(T26, original_shape=[64, 1, 1], dim=2)
    T30 = fd.ops.mul(T27, T25)
    T31 = fd.ops.view(T30, original_shape=[64, 1, 96, 3136], new_shape=[64, 96, 56, 56])
    T32 = fd.ops.mul(T31, T12)
    T33 = fd.ops.add(T32, T10)
    fd.add_output(T11)
    fd.add_output(T28)
    fd.add_output(T29)
    fd.add_output(T33)

inputs = [ 
    torch.randn(96, device='cuda'),
    torch.randn(96, device='cuda'),
    torch.randn(96, device='cuda'),
    torch.randn(64, 96, 56, 56, device='cuda'),
]

fs = Fusion()
with FusionDefinition(fs) as fd: 
    nvfuser_fusion(fd)

for _ in range(5) :
    fs.execute(inputs)
```

gives error:
```
root@968afdff8879:/opt/pytorch/torchdynamo# python /jiej/playground/repro_fd.py
Traceback (most recent call last):
  File "/jiej/playground/repro_fd.py", line 56, in <module>
    fs.execute(inputs)
RuntimeError: producer->getMemoryType() == MemoryType::Global INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/lower_sync_information.cpp":437, please report a bug to PyTorch. Inconsistent parallelization found between TV33 (T33_l[ rblockIdx.x386{( ceilDiv(( ceilDiv(( 56 * ( ceilDiv(1, 56) ) ), 4) ), blockDim.x) )}, iblockIdx.y389{( ceilDiv(( i4 * 1 ), 1) )}, iUS390{1}, rS385{4}, rthreadIdx.x387{blockDim.x}, bS118{1} ] produce_pos( 3)) and TV50(T50_l[ iblockIdx.y434{( ceilDiv(( i4 * 1 ), 1) )}, iUS435{1}, bS138{1} ] ca_pos( 2 )). Producer is required to be in Global Memory based on parallelization strategy.
```

### Versions

`torchbenchPerf`

### PR DESCRIPTION
**Pull request by naoyam**
Not confirmed but should fix #2080 

`PairwiseRootDomainMap` doesn't map a broadcast consumer domain with any of non-broadcast consumer domain. This PR relaxes the constraint such that it is mapped with a trivial-reduction consumer domain. Also added a little change in the pointwise scheduler to accommodate the mapping change.

In #2080:

```
// t0: [I0, B1]
t1 = sum(t0, {1})
// t1: [I1, R2]

t0->merge(0)
t1->merge(0)

// t0: [I0*B1]
// t1: [I1*R2]
```

Here, the exact map only has `{I0, I1}` and no `{B1, R2}` and thus no `{I0*B1, I1*R2}`. This PR makes them mapped as well.

I think mapping broadcast and trivial reduction domains make sense but not 100% sure if there's any unwanted side effect. At least, none of the tests fails.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp [hunk 1]
```diff
@@ -13,7 +13,9 @@ bool DomainMap::areAllInputIdsMappedTo(TensorView* input_tv, TensorView* tv)
   std::unordered_set<IterDomain*> in_concrete_ids;
   for (auto in_id : input_tv->getMaybeRFactorDomain()) {
     auto concrete = ca_map_.getConcreteMappedID(in_id, IdMappingMode::EXACT);
-    if (!concrete->isBroadcast() && !in_id->isReduction()) {
+    if (!concrete->isBroadcast() && !in_id->isReduction() &&
+        // Ignore trivial reductions
+        !(in_id->isBroadcast() && concrete->isTrivialReduction())) {
```
Comment (zasdfgbnm) [inline torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp]: Would `!concrete->isTrivialReduction()` be sufficient here? I can not think of any case where a non-broadcasting ID is mapped to a trivial reduction.

**Review by zasdfgbnm — APPROVED** [review]

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise_utils.cpp]: Yeah, I think that's sufficient. Well remove it.
