### PR TITLE
Fix root mapping for trivial reduction

### LINKED ISSUE #723: Root mapping falsely flags mappable domains with trivial reductions
Originally reported by @shmsong at https://github.com/csarofeen/pytorch/issues/715#issuecomment-792230119

IterDomains that are generated with trivial reductions should not prevent any otherwise-legal mappings as trivial reductions are not materialized as actual loops.

For example, in the below case, `tv3->axis(0)` is a trivial-reduction axis. While it is one of the concrete IDs of `tv2->axis(0)`, it should not impact whether the `TV2` axis can be mapped with other axes. In this particular case, the `TV2` axis can be mapped with the first axis of `TV4`.

```
auto tv2 = broadcast(tv0,{true,false});
auto tv3 = sum(tv2,{0});
auto tv4 = add(tv2,tv1);
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #723

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/root_domain_map.cpp [hunk 1]
```diff
@@ -310,9 +310,14 @@ bool ComputeAtRootDomainMap::canMap(
...
-      // If both concrete IDs are not broadcast, they must be mappable
+      // If both concrete IDs are not broadcast, they must be
+      // mappable. Also, if either of the concrete IDs is a reduction,
+      // that means a trivial reduction (i.e., broadcast immediately
+      // followed by reduction), which does not prevent any mapping.
       if (!key_a.concreteId()->isBroadcast() &&
-          !key_b.concreteId()->isBroadcast() && !mappable) {
+          !key_b.concreteId()->isBroadcast() &&
+          !key_a.concreteId()->isReduction() &&
+          !key_b.concreteId()->isReduction() && !mappable) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/root_domain_map.cpp:320]: Sorry, I forgot, does td_a and td_b always have a producer-consumer relationship?

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/root_domain_map.cpp:320]: nevermind, this is grabbing the concrete Id... forget that.

**Review by csarofeen — APPROVED** [review]
LGTM
