### PR TITLE
Fix missing vectorize predicate in batch norm test

### LINKED ISSUE #897: Predicate lowering pass refactor #844 drops predicate that causes BN to produce wrong result
## 🐛 Bug

Opening this bug to track the error.
I'm observing this on my PR branch #684. I have input tensor size [2, 89, 8, 8] and I notice a python test failure after merging dev_branch.
I tried to revert a9d3bd432942fb5f0bbff8ed7c4919be7c387aea and the error goes away.

Looked at the generated code, it seems that the refactor drops a predicate in the else block that checks the indexing falls within the total range of the tensor. I think that causes a race condition and produces nan as well.

vvv Notice how the output to T15 in the else block lost the predicate in after the refactor.

This is the one with target PR reverted:
```
======= Codegen output for kernel: kernel2 =======

__global__ void kernel2(Tensor<float, 4> T0, Tensor<float, 4> T1, Tensor<float, 1> T2, Tensor<float, 1> T3, Tensor<float, 1> T4, Tensor<float, 1> T5, Tensor<float, 1> T6, int64_t i26, Tensor<float, 4> T15) {
  if (((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3])) && (((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0]))) {
    constexpr int64_t ki344 = 0;
    float T16[2];
    *reinterpret_cast<Array<float, 2>*>(&T16[0]) = *reinterpret_cast<Array<float, 2>*>(&T1[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]);
    // Alias Allocation - register
    float* T17 = T16;
    for(size_t ki353 = 0; ki353 < 2; ++ki353) {
      float T7[1];
      T7[0]
         = T3[(((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) * 1)];
      float T8[1];
      T8[0]
        = T7[0]
        + (float) 9.9999997473787516e-06;
      float T9[1];
      T9[0]
         = rsqrtf(T8[0]);
      float T11[1];
      T11[0]
        = T16[ki353]
        * T9[0];
      float T12[1];
      T12[0]
        = T11[0]
        * (float) 1;
      T17[ki353]
        = T12[0]
        * (float) 1;
    }
    *reinterpret_cast<Array<float, 2>*>(&T15[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]) = *reinterpret_cast<Array<float, 2>*>(&T17[0]);
  } else {
    constexpr int64_t ki344 = 0;
    float T16[2];
    if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
      *reinterpret_cast<Array<float, 2>*>(&T16[0]) = *reinterpret_cast<Array<float, 2>*>(&T1[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]);
    }
    // Alias Allocation - register
    float* T17 = T16;
    #pragma unroll 1
    for(size_t ki353 = 0; ki353 < 2; ++ki353) {
      float T7[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T7[0]
           = T3[(((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) * 1)];
      }
      float T8[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T8[0]
          = T7[0]
          + (float) 9.9999997473787516e-06;
      }
      float T9[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T9[0]
           = rsqrtf(T8[0]);
      }
      float T11[1];
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T11[0]
          = T16[ki353]
          * T9[0];
      }
      float T12[1];
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T12[0]
          = T11[0]
          * (float) 1;
      }
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T17[ki353]
          = T12[0]
          * (float) 1;
      }
    }
    if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
      *reinterpret_cast<Array<float, 2>*>(&T15[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]) = *reinterpret_cast<Array<float, 2>*>(&T17[0]);
    }
  }
}
```

This is with the target PR.

```
======= Codegen output for kernel: kernel2 =======

__global__ void kernel2(Tensor<float, 4> T0, Tensor<float, 4> T1, Tensor<float, 1> T2, Tensor<float, 1> T3, Tensor<float, 1> T4, Tensor<float, 1> T5, Tensor<float, 1> T6, int64_t i26, Tensor<float, 4> T15) {
  if (((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3])) && (((((((((blockIdx.x * 128) + threadIdx.x) * 1) + (1 - 1)) * 2) + (2 - 1)) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0]))) {
    constexpr int64_t ki344 = 0;
    float T16[2];
    *reinterpret_cast<Array<float, 2>*>(&T16[0]) = *reinterpret_cast<Array<float, 2>*>(&T1[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]);
    // Alias Allocation - register
    float* T17 = T16;
    for(size_t ki353 = 0; ki353 < 2; ++ki353) {
      float T7[1];
      T7[0]
         = T3[(((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) * 1)];
      float T8[1];
      T8[0]
        = T7[0]
        + (float) 9.9999997473787516e-06;
      float T9[1];
      T9[0]
         = rsqrtf(T8[0]);
      float T11[1];
      T11[0]
        = T16[ki353]
        * T9[0];
      float T12[1];
      T12[0]
        = T11[0]
        * (float) 1;
      T17[ki353]
        = T12[0]
        * (float) 1;
    }
    *reinterpret_cast<Array<float, 2>*>(&T15[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]) = *reinterpret_cast<Array<float, 2>*>(&T17[0]);
  } else {
    constexpr int64_t ki344 = 0;
    float T16[2];
    *reinterpret_cast<Array<float, 2>*>(&T16[0]) = *reinterpret_cast<Array<float, 2>*>(&T1[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]);
    // Alias Allocation - register
    float* T17 = T16;
    #pragma unroll 1
    for(size_t ki353 = 0; ki353 < 2; ++ki353) {
      float T7[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T7[0]
           = T3[(((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) * 1)];
      }
      float T8[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T8[0]
          = T7[0]
          + (float) 9.9999997473787516e-06;
      }
      float T9[1];
      if ((((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) % (T1.size[1] * (T1.size[2] * T1.size[3]))) / (T1.size[2] * T1.size[3])) < T3.size[0])) {
        T9[0]
           = rsqrtf(T8[0]);
      }
      float T11[1];
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T11[0]
          = T16[ki353]
          * T9[0];
      }
      float T12[1];
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T12[0]
          = T11[0]
          * (float) 1;
      }
      if ((((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + ki353) < (((T1.size[0] * T1.size[1]) * T1.size[2]) * T1.size[3]))) {
        T17[ki353]
          = T12[0]
          * (float) 1;
      }
    }
    *reinterpret_cast<Array<float, 2>*>(&T15[(((((((blockIdx.x * 128) + threadIdx.x) * 1) + ki344) * 2) + 0) * 1)]) = *reinterpret_cast<Array<float, 2>*>(&T17[0]);
  }
}

======================================
```

### PR DESCRIPTION
**Pull request by rdspring1**
Fix #897 

- **Symptom:** The predicate for vectorize operations was not being generated, causing `test_batch_norm_impl_index_correctness` to fail.
- **Underlying problem:** UnswitchPredicate does not handle IfThenElse nodes, so it returned a `true` predicate.
- **Solution:** Modify UnswitchPredicate to open the IfThenElse then body and process those expressions.

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @naoyam

File: torch/csrc/jit/codegen/cuda/lower_predicate.cpp [hunk 1]
```diff
@@ -100,6 +100,22 @@ class ConditionalFromPredicateModifier {
...
+            break;
+          } else {
+            outer_loops.emplace_back(loop);
+          }
+        }
+        TORCH_INTERNAL_ASSERT(
+            vectorized_loop != nullptr, "Should be unreachable.");
+        return UnswitchPredicate::get(
+            outer_loops, vectorized_loop, p2c_root_map_);
+      }
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_predicate.cpp:118]: I understand how the other parts of this PR fixes the problem, but I'm not sure about this part. Is this also necessary? Or, is this just refactoring?

Comment (rdspring1) [reply torch/csrc/jit/codegen/cuda/lower_predicate.cpp:118]: It is necessary because `outer_loops != for_loop_structure_` so the code can't be shared with `PredicateType::Unswitch`.

Comment (rdspring1) [reply torch/csrc/jit/codegen/cuda/lower_predicate.cpp:118]: It is also a small refactor since I moved this code from `lower_unroll.cpp`

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_predicate.cpp:118]: Ah, okay, makes sense.

**Review by naoyam — APPROVED** [review]
Approving the PR, though @rdspring1 seems to having a different error.
