### PR TITLE
Detect trivial reductions more comprehensively

### LINKED ISSUE #727: Problems with trivial reductions
There are two issues with trivial reductions:

1. Trivial reductions are supposed to be lowered to unary set. However, it fails when a reduction axis is split. See https://github.com/csarofeen/pytorch/issues/716#issuecomment-792380664.
2. Trivial reductions do not need actual loops, but the current codegen emits anyway. 

PR #726 should address the first issue.

For the second issue, it is not harmful unless computeAt is done involving such trivial reductions. Loops with extent 1 would be generated, but that's just fine at least functionally. However, in #724, ComputeAtRootMap is relaxed to allow certain mappings based on the assumption that trivial reductions do not result in actual loops, which is not really the case. For example, this test fails at the result validation:

```
TEST(NVFuserTest, FusionRootMappingTrivialReduction_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(1);
  auto tv1 = makeSymbolicTensor(2);

  fusion.addInput(tv0);
  fusion.addInput(tv1);

  auto tv2 = broadcast(tv0, {true, false});
  auto tv3 = sum(tv2, {0});
  auto tv4 = add(tv2, tv1);

  fusion.addOutput(tv3);
  fusion.addOutput(tv4);

  ComputeAtRootDomainMap map;
  map.build();

  checkIdMapped(
      map, tv2, tv2->getRootDomain()[0], tv4, tv4->getRootDomain()[0], true);
  checkIdMapped(
      map, tv2, tv2->getRootDomain()[0], tv3, tv3->getRootDomain()[0], true);

  tv2->computeAt(tv4, -1);

  fusion.printKernel();

  const int x = 11;
  const int y = 12;
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({x}, options);
  at::Tensor t1 = at::randn({y, x}, options);
  std::vector<IValue> aten_inputs = {t0, t1};

  FusionExecutor fe;
  fe.compileFusion(&fusion);
  auto outputs = fe.runFusion(aten_inputs);

  auto t3 = t0;
  auto t4 = t0.unsqueeze(0).expand({y, x}) + t1;

  testValidate(&fusion, outputs, aten_inputs, {t3, t4}, __LINE__, __FILE__);
}
```

The generated kernel:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 1> T0, Tensor<float, 2> T1, Tensor<float, 1> T3, Tensor<float, 2> T4) {
  for(size_t ki26 = 0; ki26 < 1; ++ki26) {
    for(size_t ki27 = 0; ki27 < T0.size[0]; ++ki27) {
      float T2[1];
      T2[0]
         = T0[(ki27 * T0.stride[0])];
      T3[ki27]
         = T2[0];
      T4[(ki26 * T4.stride[0]) + ki27]
        = T2[0]
        + T1[(ki26 * T1.stride[0]) + (ki27 * T1.stride[1])];
    }
  }
}
```

Notice that the outer-most loop has extent one, which is derived from `tv3->axis(0)`. That's fine for `T3` but not for `T4` since `T4`'s first axis has actually an extent of `T1.size[0]`.

The problem is that `tv2->axis(0)` is determined to be mappable with both `tv3->axis(0)` and `tv4->axis(0)`. This is semantically correct, assuming there is no loop generated for `tv3->axis(0)`, which is in fact not the case. As shown above, the outer-most loop is the one corresponding to `tv3->axis(0)`. 

I think that just using a unary set for a given trivial reduction isn't sufficient. If we replace the trivial reduction axis, `tv3->axis(0)`, with a broadcast axis, then we would not generate the extent-one loop since ComputeAtMap would not pick it as the concrete IterDomain, which would then correctly generate the outer-most loop with the `T1.size[0]`. 

I'm still not 100% clear whether there could be any negative side effect.

### PR DESCRIPTION
**Pull request by naoyam**
This PR addresses the issues around trivial reductions (#727):

1. Detect IterDomains that are derived from trivial reductions (lower_trivial_reduction.cpp)
2. In ComputeAtMap, avoid choosing trivial-reduction domains as concrete domains
3. When generating kir::ForLoops, do not generate loops with trivial-reduction IterDomains

Currently, trivial reductions are only detected when the extent of reduced axis is literal one, and it does not work, e.g., if the axis is split. This PR should find all such domains by backward-traversing IterDomain expressions to root domains.

The second problem in issue #727 is solved by not choosing trivial-reduction IterDomains over other domains as concrete IDs in ComputeAtMap.

Finally, trivial-reduction domains may still show up as a concrete ID for loop generation when no other mappable domain is found. In such case, since no loop is needed, it is simply skipped when generating loops.

Fixes #727

### CODE REVIEW

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -13470,6 +13550,54 @@ TEST(NVFuserTest, FusionBlockWelfordInSerialLoop_CUDA) {
...
+  at::manual_seed(0);
+  at::Tensor t0 = at::randn({M}, options);
+  at::Tensor t0_ref = t0.clone();
+  std::vector<IValue> aten_inputs = {t0};
+
+  FusionExecutor fe;
+  fe.compileFusion(&fusion);
+
+  // Error occurs at executor.cpp:321.
+  // TODO: Enable below.
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu.cpp]: What's the issue?

File: torch/csrc/jit/codegen/cuda/ir_internal_nodes.h [hunk 2]
```diff
@@ -425,6 +425,9 @@ class TORCH_CUDA_CU_API IterDomain : public Val {
 
   //! Check if IterDomain is a reduction axis with size of 1, i.e.
   //! a "squeeze" operator.
+  //! TODO: Consider removing this as it does not detect trivial
+  //! reduction always. Trivial reductions are detected at the
+  //! lowering time.
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/ir_internal_nodes.h]: We typically use this for root domain trivial reduction checks. So we ship to the correct scheduler. It may not be incredibly robust, but I think it makes sense to keep it or something like it.

File: torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+std::unordered_set<IterDomain*> detectTrivialReductionDerivedDomains(
+    Fusion* fusion) {
+  auto used_vals = DependencyCheck::getAllValsBetween(
+      {fusion->inputs().begin(), fusion->inputs().end()}, fusion->outputs());
+
+  std::unordered_set<IterDomain*> trivial_reductions;
+
+  for (auto tv : ir_utils::filterByType<TensorView>(used_vals)) {
+    for (auto id : tv->domain()->domain()) {
+      if (isDerivedFromTrivialReduction(tv, id)) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: The logic here seems a little bit backwards to me. Why wouldn't we check both root domain and rfactor domains for trivial reductions. Then grab all vals between all the trivial reductions and the current domain, and mark everything in between as derived from trivial reduction?

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: Seems this is because all vals between doesn't actually grab values explicitly in between provided values. Seems like we should really fix that, as it's really misleading that it doesn't. Shouldn't be hard to fix:
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/iter_visitor.cpp#L377
Should only do that if there are no provided dependencies, and then if no provided dependencies we should insert the front of the stack at this point https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/iter_visitor.cpp#L372 to vals
similar to https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/iter_visitor.cpp#L503-L507

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: This is the current error:

```
C++ exception with description "val.has_value()INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":321, please report a bug to PyTorch. Tried to evaluate the extent of blockIdx.x to set launch bounds but could not.
Exception raised from computeLaunchParams at ../torch/csrc/jit/codegen/cuda/executor.cpp:321 (most recent call first):
```

The test is the one @jjsjann123 posted at #716. 

The generated code looks fine. I'm not yet sure what the error means, which I'm planning to look into, but I think that's not related to trivial reductions.

File: torch/csrc/jit/codegen/cuda/ir_internal_nodes.h (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/ir_internal_nodes.h]: OK. I'll add your comment to the code as well.

File: torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: Are you saying `getAllValsBetween` grabs all vals in a dependency chain if no given dependency val appears in the chain? That is indeed counter-intuitive, and should be easy to fix.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: `getAllValsBetween` can be fixed, but sorry, I don't understand why it's relevant here. The detection is done for a leaf IterDomain with `isDerivedFromTrivialReduction`, which traverses up to root axes. It also further traverses back to rfactor tensors if found since a rfactored tensor does not have complete domain information necessary to determine triviality. For example:

```
auto tv0 = makeSymbolicTensor(1);
auto tv1 = broadcast(tv0, {false, true});
auto tv2 = sum(tv1, {1}); // trivial reduction

tv2->split(1, 4);
auto tv3 = tv2->rfactor({1});
```

`tv3` is still trivial reduction, but its domain should look like `[I, r(4)]`. Looking at `tv3`'s root domain doesn't give you enough information to determine it's indeed trivial.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: I'm saying it seems like it would make sense to me to do it in the reverse direction. Start from `tv3`'s root/rfactor domain, and propagate to leaves. Which could easily be done with `getAllValsBetween` if the behavior was fixed.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: If you think it makes more sense as is, I'm not 100% firm in this position, but the logic as is simply seems a bit convoluted to me.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: I'm sorry I meant `tv2` not `tv3`. The root domains of `tv2` are:

```
tv2 root: iS11{i1} rS12{4}
tv2 maybe-rfactor root: iS11{i1} rS12{4}
```

How do we know `rS12{4}` is a trivial reduction if we start analysis from the root or maybe-rfactor root domains?

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: My initial attempt was actually like as you suggested. It just looked at the root domain. 61f37db. 

However, I realized it doesn't work for the case like above.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_reductions.cpp:84]: Added an issue on `getAllValsBetween` #728

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: The reason of this error is that the expression evaluator fails to determine the actual value of `gridDim.x`. There seem two issues. First, the test uses `rFactor` after setting a parallel type. This should probably be avoided. If an rfactor axis has a parallel type, it's not clear what the end result should look like. We may want to yield errors when rfactored tensors have parallel types.

That is not actually the reason of this failure, but there is a problem with `IterDomain::clone`. See #730

Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: The test is now enabled and works with no error.

**Review by csarofeen — APPROVED** [review]
