### PR TITLE
Make sure WAR syncs for gather ops are properly generated.

### LINKED ISSUE #1510: Missing syncthreads
Some of the shift/gather tests are failing non-deterministically due to missing syncthreads.

For example, in `FusionMaxPoolingStrided`, there must be syncthreads after loading to `T3`, but that's missing.

Correct:

```
        #pragma unroll
        for(nvfuser_index_t i61 = 0; i61 < 5; ++i61) {
          #pragma unroll
          for(nvfuser_index_t i62 = 0; i62 < 5; ++i62) {
            T3[(((((nvfuser_index_t)threadIdx.y) * 3) + i61) * 98) + ((((nvfuser_index_t)threadIdx.x) * 3) + i62)]
               = T0[(((nvfuser_index_t)blockIdx.x) * T0.stride[0]) + ((((((i43 * 8) + ((nvfuser_index_t)threadIdx.y)) * 3) + i61) - 1) * T0.stride[1]) + ((((((i45 * 32) + ((nvfuser_index_t)threadIdx.x)) * 3) + (i62 + nvfuser_zero)) - 1)
 * T0.stride[2])];
          }
        }
        NVFUSER_UPDATE_MAGIC_ZERO
        __barrier_sync(0);
```

TOT:

```
        #pragma unroll
        for(nvfuser_index_t i61 = 0; i61 < 5; ++i61) {
          #pragma unroll
          for(nvfuser_index_t i62 = 0; i62 < 5; ++i62) {
            T3[(((((nvfuser_index_t)threadIdx.y) * 3) + i61) * 98) + ((((nvfuser_index_t)threadIdx.x) * 3) + i62)]
               = T0[(((nvfuser_index_t)blockIdx.x) * T0.stride[0]) + ((((((i43 * 8) + ((nvfuser_index_t)threadIdx.y)) * 3) + i61) - 1) * T0.stride[1]) + ((((((i45 * 32) + ((nvfuser_index_t)threadIdx.x)) * 3) + (i62 + nvfuser_zero)) - 1)
 * T0.stride[2])];
          }
        }
        NVFUSER_UPDATE_MAGIC_ZERO
        float T1[((1 * 3) * 3)];
```

Not sure why yet, but this bug is introduced with #1484.

### PR DESCRIPTION
**Pull request by csarofeen**
Fixes #1510

A little conservative since it also generates an unnecessary RAW sync, but it's functional.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/lower_sync_information.cpp [hunk 1]
```diff
@@ -103,7 +105,9 @@ void SyncMap::build(Fusion* fusion) {
       validateParallelizationOfTensor(consumer);
     }
 
-    // Validate parallelization between a producer and a consumer
+    // It's probably enough to just check one producer (must be a TV if there's
+    // a TV) to one consumer, but to be conservative for now checking every
+    // producer <-> consumer relationship.
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_sync_information.cpp]: Unless we assume all producers have the same memory type and parallel types, wouldn't it be necessary to validate each consumer?

For consumers, since all consumers do have the same parallel types and their memory types don't matter, I think it's just sufficient to check one of the consumers.

**Review by naoyam — APPROVED** [review]
Thanks for the fix. This looks sufficient for the failing tests. However, I think the same issue could happen with `shift` as well, as long as shifted or gathered axes are split and only outer domains are parallelized. That's the pattern showing up with strided gather, but no other shift/gather tests has. For now, I think we should merge this to address the test failures, and I'll create a follow-up PR to address `shift`.

**Comment by naoyam** [comment]
BTW, the missing syncthreads is not a WAR sync but a RAW sync.

In `MaxPoolingStrided`, the write to `T3` is:
```
   T3[(((((nvfuser_index_t)threadIdx.y) * 3) + i61) * 98) + ((((nvfuser_index_t)threadIdx.x) * 3) + i62)]
               = T0[(((nvfuser_index_t)blockIdx.x) * T0.stride[0]) + ((((((i43 * 8) + ((nvfuser_index_t)threadIdx.y)) * 3) + i61) - 1) * T0.stride[1]) + ((((((i45 * 32) + ((nvfuser_index_t)threadIdx.x)) * 3) + (i62 + nvfuser_zero)) - 1)
 * T0.stride[2])];
```

The read of `T3` is:
```
 T3[((((((nvfuser_index_t)threadIdx.y) * 3) + 1) + (i57 - 1)) * 98) + (((((nvfuser_index_t)threadIdx.x) * 3) + 1) + (i58 - 1))];
```

I.e., the read offset of each thread is shifted by 1, so each thread must wait the completion of the writes by its neighbor thread.

File: torch/csrc/jit/codegen/cuda/lower_sync_information.cpp (hunk 1 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_sync_information.cpp]: Yeah, you're right, thanks.

**Comment by csarofeen** [comment]
Note: We discussed more on RAW vs WAR and does seem it's a WAR missing in this instance, we're uncertain if this can manifest as a RAW, or if there's other cases we're unable to detect with this PR.

**Comment by naoyam** [comment]
Here's a repro with shift: https://github.com/csarofeen/pytorch/issues/1518

I'll work on a fix for the shift case.

**Comment by csarofeen** [comment]
Great, I'll leave this PR open so we can push it directly here.

**Comment by naoyam** [comment]
Updated with the support for shift. The repro of #1518 works fine now.
