### PR TITLE
Unswitch predicate equality fix

### LINKED ISSUE #1080: Incorrect unswitch/unroll predication
In `UnswitchPredicate::predicateOn`, an unswitch predicate is only used when it covers a new root domain, but this only looks at concrete root domains in the loop CA map, which doesn't seem always correct. For example:

```
TEST(NVFuserTest, FusionUnswitchPredicate_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);

  auto tv1 = add(tv0, new Double(1));
  auto tv2 = add(tv1, new Double(1));
  fusion.addOutput(tv2);

  fusion.printMath();
  fusion.printKernel();

  tv2->split(0, 4);
  tv0->computeAt(tv2, 2);

  tv2->split(-1, 8);
  tv1->split(-1, 8);

  tv2->axis(1)->parallelize(ParallelType::Unswitch);

  tv2->axis(-1)->parallelize(ParallelType::TIDx);
  tv2->axis(-2)->parallelize(ParallelType::TIDy);

  // swap TIDx and TIDy
  tv1->axis(-1)->parallelize(ParallelType::TIDy);
  tv1->axis(-2)->parallelize(ParallelType::TIDx);

  tv1->setMemoryType(MemoryType::Shared);

  fusion.printKernel();

  FusionExecutor fe;
  fe.compileFusion(&fusion);

  const int nx = 4;
  const int ny = 10;
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({nx, ny}, options);
  std::vector<IValue> aten_inputs = {t0};
  auto outputs = fe.runFusion(aten_inputs);

  auto ref = t0 + 2;

  testValidate(
      &fusion, outputs, aten_inputs, {ref}, __LINE__, __FILE__);
}
```

The generated code is:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 2> T2) {
  alignas(4) extern __shared__ char array[];
  unsigned offset = 0;
  NVFUSER_DEFINE_MAGIC_ZERO
  offset = alignBufferSize(offset,4);
  float* T1 = reinterpret_cast<float*>(array + offset);
  offset += (((ceilDiv(T0.size[1], 8)) * 8) * sizeof(float));
  #pragma unroll 1
  for(nvfuser_index_t ki70 = 0; ki70 < (ceilDiv(T0.size[0], 4)); ++ki70) {
    if (((((ki70 * 4) + (4 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[1]))) {
      #pragma unroll
      for(nvfuser_index_t ki72 = 0; ki72 < 4; ++ki72) {
        T1[((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y))]
          = T0[(((ki70 * 4) + (ki72 + nvfuser_zero)) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[1])]
          + (float) 1;
        __barrier_sync(0);
        T2[(((ki70 * 4) + (ki72 + nvfuser_zero)) * (1 * T0.size[1])) + (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 1)]
          = T1[((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.x))]
          + (float) 1;
        __barrier_sync(0);
      }
      NVFUSER_UPDATE_MAGIC_ZERO
    } else {
      #pragma unroll
      for(nvfuser_index_t ki72 = 0; ki72 < 4; ++ki72) {
        if (((((ki70 * 4) + (ki72 + nvfuser_zero)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[1]))) {
          T1[((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y))]
            = T0[(((ki70 * 4) + (ki72 + nvfuser_zero)) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[1])]
            + (float) 1;
        }
        __barrier_sync(0);
        if (((((ki70 * 4) + (ki72 + nvfuser_zero)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) < T0.size[1]))) {
          T2[(((ki70 * 4) + (ki72 + nvfuser_zero)) * (1 * T0.size[1])) + (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 1)]
            = T1[((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.x))]
            + (float) 1;
        }
        __barrier_sync(0);
      }
      NVFUSER_UPDATE_MAGIC_ZERO
    }
  }
}
```

The problem is that the unswitch predicate only includes `(((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[1])))` but not `(((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) < T0.size[1]))`. Running this with compute-sanitizer should issue SMEM access errors. 

In this particular case, using the CA parallel map would fix the issue, but not sure whether that's always correct.

### PR DESCRIPTION
**Pull request by naoyam**
Make sure not to miss necessary predicates during the unswitch pass. Currently only predicated concrete domains are used to filter out duplicates, but if the same domain is parallelized differently as shown in #1080, each one needs to be used. This PR looks at how predicated domains are parallelized and use that information, stored as `UnswitchPredicateKey`, to decide which one to keep and discard.

Here's the generated code from the reproducer in #1080
```
__global__ void kernel1(Tensor<float, 2> T0, Tensor<float, 2> T2) {
  alignas(4) extern __shared__ char array[];
  unsigned offset = 0;
  offset = alignBufferSize(offset,4);
  float* T1 = reinterpret_cast<float*>(array + offset);
  offset += (((ceilDiv(T0.size[1], 8)) * 8) * sizeof(float));
  #pragma unroll 1
  for(nvfuser_index_t ki74 = 0; ki74 < (ceilDiv(T0.size[0], 4)); ++ki74) {
    if ((((((ki74 * 4) + (4 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[1])) && (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) < T0.size[1]))) {
      #pragma unroll 1
      for(nvfuser_index_t ki76 = 0; ki76 < 4; ++ki76) {
        T1[((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y))]
          = T0[(((ki74 * 4) + ki76) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[1])]
          + (float) 1;
        __barrier_sync(0);
        T2[(((ki74 * 4) + ki76) * (1 * T0.size[1])) + (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 1)]
          = T1[((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))]
          + (float) 1;
        __barrier_sync(0);
      }
    } else {
      #pragma unroll 1
      for(nvfuser_index_t ki76 = 0; ki76 < 4; ++ki76) {
        if (((((ki74 * 4) + ki76) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) < T0.size[1]))) {
          T1[((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y))]
            = T0[(((ki74 * 4) + ki76) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[1])]
            + (float) 1;
        }
        __barrier_sync(0);
        if (((((ki74 * 4) + ki76) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) < T0.size[1]))) {
          T2[(((ki74 * 4) + ki76) * (1 * T0.size[1])) + (((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) * 1)]
            = T1[((((nvfuser_index_t)threadIdx.y) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))]
            + (float) 1;
        }
        __barrier_sync(0);
      }
    }
  }
}
```

Fixes #1080 

Depends on #1109

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp [hunk 1]
```diff
@@ -52,8 +52,108 @@ bool isOutputLocal(const kir::Expr* expr) {
       });
 }
 
+constexpr std::array<ParallelType, 6> parallel_types = {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/predicate_compute.cpp]: Should this go in `type.h`? Seems relatively useful especially if we ever have to add a new parallel type.

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp [hunk 2]
```diff
@@ -52,8 +52,108 @@ bool isOutputLocal(const kir::Expr* expr) {
...
+      std::back_inserter(parallelized_leaf_domains),
+      [](IterDomain* x) { return isParallelTypeThread(x->getParallelType()); });
+
+  // If the reference is not parallelized at all, no need to
+  // differentiate keys based on how id_ is parallelized
+  if (parallelized_leaf_domains.empty()) {
+    return;
+  }
+
+  auto all_vals =
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/predicate_compute.cpp]: nit: Please make the name more specific like `all_parallelized_root_vals`

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp [hunk 3]
```diff
@@ -52,8 +52,108 @@ bool isOutputLocal(const kir::Expr* expr) {
...
+    parallel_ids_.insert({pt, nullptr});
+  }
+
+  // The id parameter is a concrete domain. Needs to find the
+  // corresponding reference domain to find leaf domains that are
+  // parallelized.
+  IterDomain* ref_id = reference.concrete_to_id.at(id_);
+  TensorDomain* ref_td = reference.domain;
+
+  std::vector<Val*> parallelized_leaf_domains;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/predicate_compute.cpp]: Nit: `parallelized_concrete_leaf_ids`

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp [hunk 4]
```diff
@@ -52,8 +52,108 @@ bool isOutputLocal(const kir::Expr* expr) {
...
+
+  // If the reference is not parallelized at all, no need to
+  // differentiate keys based on how id_ is parallelized
+  if (parallelized_leaf_domains.empty()) {
+    return;
+  }
+
+  auto all_vals =
+      DependencyCheck::getAllValsBetween({ref_id}, parallelized_leaf_domains);
+  std::vector<IterDomain*> leaf_ids;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/predicate_compute.cpp]: Nit: `parallelized_ref_leaf_ids`

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp [hunk 5]
```diff
@@ -52,8 +52,108 @@ bool isOutputLocal(const kir::Expr* expr) {
...
+  for (auto ref_leaf : leaf_ids) {
+    auto pt = ref_leaf->getParallelType();
+    auto it = std::find_if(
+        reference.concrete_to_id.begin(),
+        reference.concrete_to_id.end(),
+        [&](const auto& kv) { return kv.second == ref_leaf; });
+    TORCH_INTERNAL_ASSERT(it != reference.concrete_to_id.end());
+    auto concrete_leaf = it->first;
+    parallel_ids_.at(pt) = concrete_leaf;
+  }
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/predicate_compute.cpp:126]: Wouldn't this have been easier to do by just flipping the `concrete_to_id` map? Seems you could have then just looked for the parallelized leaf domains in the reference, directly grabbed the concrete leaf, and thrown it in the parlalel_ids_ map. You wouldn't even have to flip the whole map, just those in the reference domain.

Conversely I think it would be reasonable to just put `id_to_concrete` map into the reference domain, even if this is the only place we use it.

**Review by csarofeen — APPROVED** [review]
LGTM, minor comments on some cleanup.

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/predicate_compute.cpp:126]: I'll add `id_to_concrete`. Thanks for the suggesion.

File: torch/csrc/jit/codegen/cuda/predicate_compute.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/predicate_compute.cpp]: Added to types.h. Thanks for the suggestion.
