### PR TITLE
Expand+Reduction, Expand+View support, rework View analysis and guards

### LINKED ISSUE #1860: Handling of broadcasted input tensor with concrete sizes in codegen
### 🐛 Describe the bug

When a fusion takes tensor with concrete broadcast dimension as input, current kernel check asserts on the size of such dimension being 1. I think the information is dropped during fusion scheduling. I'm investigating this. 

I currently have a fusion segmentation with these signatures:

g{​​(persistent)
inputs:
T0_g[ bS0{​​1}​​, iS1{​​i2}​​, iS2{​​i3}​​ ] float
T1_g[ bS3{​​1}​​, iS4{​​i7}​​, iS5{​​i8}​​ ] float
T2_g[ bS6{​​1}​​, iS7{​​i9}​​, iS8{​​i10}​​ ] float
T22_g[ bS63{​​1}​​, bS64{​​2}​​, bS65{​​3}​​ ] float
outputs:
T26_g[ bS75{​​1}​​, iS76{​​i2}​​, iS77{​​i3}​​ ] float

Note that T22_g has static broadcasted size bS64{2} & bS65{3}.

But in the generated kernel, those seems to have been lost....

it ended up with a kernel like this:
KERNEL (T0_g[ iS137{​( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[1] * T0.size[2] ), 1) ), 1) ), 4) )}​, iS134{​1}​, iS136{​4}​, iS132{​1}​, bS0{​1}​ ], T2_g[ iS235{​( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[1] * T0.size[2] ), 1)
 ), 1) ), 4) )}​, iS232{​1}​, iS234{​4}​, iS230{​1}​, bS6{​1}​ ], T1_g[ iS214{​( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[1] * T0.size[2] ), 1) ), 1) ), 4) )}​, iS211{​1}​, iS213{​4}​, iS209{​1}​, bS3{​1}​ ], T22_g[ bS193{​( ceilDiv((
 ceilDiv(( ceilDiv(( 1 * 1 ), 1) ), 1) ), 4) )}​, bS190{​1}​, bS192{​4}​, bS188{​1}​, bS63{​1}​ ]) -> (T26_g[ ithreadIdx.x249{​( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[1] * T0.size[2] ), 1) ), 1) ), 4) )}​, iUS246{​1}​, iUR24
8{​4}​, iS244{​1}​, bS96{​1}​ ] produce_pos( 2)) :

And during execution, it asserts, since kernel requires T22_g to be size 1 across all dimensions.

### Versions

Upstream code bump push: https://github.com/pytorch/pytorch/pull/81861

commit: https://github.com/csarofeen/pytorch/commit/0cd50c71d65d0d8d3d5fc3c7679ebe9da4d4288b

### PR DESCRIPTION
**Pull request by csarofeen**
Fixes #1860

Big rabbit hole I went into. Almost completely rewrote `transform_view[.cpp,.h]` as I was having a lot of trouble parsing the way it was written and adjusting it for expand support.

Now supporting Expand+Reduction and Expand+View which resolve the expanded broadcast axes before the following operations (Reduction/View).
Reworked view analysis, and drafted the caching scheme we could move forward for dynamic shape view support.
Jie found a naming conflict and fixed that.

TODO:
- [x] Make tests explicit for the view caching system

TODO in follow up:
- [ ] Add registry rules to allow pre-fusion of view (views fused if they're producers to all references in scheduler)
- [ ] Enable view fusions

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp [hunk 1]
```diff
@@ -980,6 +947,218 @@ TEST_F(NVFuserTest, FusionExpandRepro_CUDA) {
...
+  FusionExecutorCache executor_cache(std::move(fusion));
+  auto cg_outputs = executor_cache.runFusionWithInputs({t0, t1});
+
+  auto ref = at::native::reshape(t0.expand({12, 8}), {3, 4, 8}) + t1;
+
+  testValidate(
+      executor_cache.fusion(), cg_outputs, {t0, t1}, {ref}, __LINE__, __FILE__);
+}
+
+TEST_F(NVFuserTest, FusionViewTransformCache_CUDA) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp:1015]: @kevinstephano this is what the caching system for transform looks like, will have to be piped up to the front end FYI.

It's just sending in runtime sizes, and checking equivalence.

File: torch/csrc/jit/codegen/cuda/transform_view.h [hunk 2]
```diff
@@ -34,17 +34,71 @@ class ViewTransform;
...
 
 struct AnalyzeViewResult {
-  bool has_broadcast = false;
   std::vector<bool> broadcast_axes;
   std::vector<int> trivial_reduction_axes;
   std::vector<std::shared_ptr<ViewTransform>> transforms;
 };
 
-struct AnalyzeViewConstraint {
+struct TORCH_API AnalyzeViewConstraint {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/transform_view.h:42]: @kevinstephano this structure is what's helping with the view caching system for view.

File: torch/csrc/jit/codegen/cuda/transform_view.h [hunk 3]
```diff
@@ -34,17 +34,71 @@ class ViewTransform;
...
+    return conglomerate;
+  }
+
+  bool operator==(const AnalyzeViewConstraint& other) const {
+    return other.conglomerateString() == this->conglomerateString();
+  }
+
+  // Naive hashing function, likely has a lot of collisions, but may not matter
+  // too much if we don't expact many types of views.
+  size_t hash() {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/transform_view.h:82]: @kevinstephano Really stupid hash function, that I'm sure could be improved if needed.

File: torch/csrc/jit/codegen/cuda/transform_view.h [hunk 4]
```diff
@@ -53,7 +107,7 @@ AnalyzeViewResult analyzeView(
     const std::vector<int64_t>& new_sizes);
 
 // Find the constraints derived from the view transformations
-AnalyzeViewConstraint analyzeViewConstraint(
+TORCH_CUDA_CU_API AnalyzeViewConstraint analyzeViewConstraint(
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/transform_view.h:110]: @kevinstephano returns the struct above from the raw runtime sizes.

File: torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp (hunk 1 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp:1015]: Maybe we want a utility function to provide the overall runtime sizes on the fusion input and return if the view caches check out after runtime inference. Note for the future. Just let me know if this rough infrastructure seems to make sense.

**Review by csarofeen — COMMENTED** [review]
Notes for Kevin.

**Comment by csarofeen** [comment]
@jjsjann123 you can check the renaming you were responsible for and sign off on that.
@rdspring1 is out, so we might review this without him, but adding him here for an FYI.

**Comment by csarofeen** [comment]
@naoya could you please review the changes related to expand
@zasdfgbnm maybe you could help review the view logic (transform_view and alias)

**Comment by naoya** [comment]
@csarofeen Maybe it's someone else?

@naoyam

File: torch/csrc/jit/codegen/cuda/arith.cpp [hunk 5]
```diff
@@ -1194,7 +1199,7 @@ TensorView* expand(TensorView* inp, const std::vector<Val*>& expanded_sizes) {
       // This is just done for clarity. It isn't necessary as it's
       // already done when constructing out_id_builder.
       out_id_builder.extent(inp_id->extent());
-    } else if (inp_id->isBroadcast()) {
+    } else if (inp_id->isBroadcast() && expanded_size_int != 1) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/arith.cpp:1250]: Is it an error to pass an expanded size of 1?

File: torch/csrc/jit/codegen/cuda/root_domain_map.cpp [hunk 6]
```diff
@@ -1147,6 +1147,15 @@ ExactRootDomainMap::ExactRootDomainMap(Fusion* fusion) {
 bool ExactRootDomainMap::areMapped(
     const IterDomain* id_a,
     const IterDomain* id_b) const {
+  // With expand going into a view operation there can be an instance where an
+  // iteration root domain in the consumer resolves the broadcast from the
+  // producer, then immediately rfactors it. In this case the consumer root is
+  // not mapped exactly to any other domain, so it might no have an entry in
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/root_domain_map.cpp:1153]: typo: no -> not

**Comment by csarofeen** [comment]
Sorry about that! Thanks ;-)

**Comment by jjsjann123** [comment]
Linking another expand related upstream issue here as well: https://github.com/pytorch/pytorch/issues/82858

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 7]
```diff
@@ -777,13 +777,21 @@ kir::ExpressionEvaluator bindKernelInputs(
...
+              " dimension ",
+              dim,
+              " but found stride ",
+              aten_tensor.strides()[dim]);
         }
-        const auto value = aten_tensor.sizes()[dim];
+
+        const auto value = root_domain[dim]->hasExpandedExtent()
+            ? 1
+            : aten_tensor.sizes()[dim];
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp]: Still trying to understand what the right behavior should be.

If a root domain has an expanded extent, can't we know the size of the extpanded extent from the corresponding aten tensor? If so, shouldn't we bind the expanded extent to that aten value?

IIUC, what's done in this PR is effectively none as `extent` is an extent of a broadcast domain, so it should be 1, and thus `extent->isConstScalar()` is true and `expr_eval->bind()` isn't called.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 8]
```diff
@@ -844,19 +852,27 @@ ExpressionEvaluator bindFusionInputs(
...
-          aten_tensor.ndimension() == (int64_t)root_dom.size(),
+          aten_tensor.ndimension() == (int64_t)root_domain.size(),
           "Something went wrong configuring launch. Inputs do not match.");
-      for (const auto dim : c10::irange(root_dom.size())) {
-        Val* extent = nullptr;
-        if (root_dom[dim]->hasExpandedExtent()) {
-          extent = root_dom[dim]->expandedExtent();
-        } else {
-          extent = root_dom[dim]->extent();
+      for (const auto dim : c10::irange(root_domain.size())) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:873]: same here

File: torch/csrc/jit/codegen/cuda/ir_nodes.cpp [hunk 9]
```diff
@@ -1182,6 +1182,25 @@ IterDomain* IterDomain::merge(IterDomain* outer, IterDomain* inner) {
...
 
+  Val* expanded_extent = nullptr;
+  if (outer->hasExpandedExtent() || inner->hasExpandedExtent()) {
+    if (outer->hasExpandedExtent() && inner->hasExpandedExtent()) {
+      expanded_extent = mul(outer->expandedExtent(), inner->expandedExtent());
+    } else if (outer->hasExpandedExtent() && !inner->hasExpandedExtent()) {
+      if (inner->isBroadcast()) {
+        expanded_extent = outer->expandedExtent();
+      } else {
+        expanded_extent = mul(outer->expandedExtent(), inner->extent());
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/ir_nodes.cpp:1193]: Does this mean a non-broadcast ID can have an expanded extent? I thought that's not allowed. The comment on `IterDomain::expanded_extent_` also indicates so.

File: torch/csrc/jit/codegen/cuda/lower_index_compute.cpp [hunk 10]
```diff
@@ -799,11 +799,12 @@ IndexFromIdGraph getTensorIndexFromIdGraph(
...
 
   // Populate indexing through exact map from initial indexing
+  auto consumer_root = index_producer ? consumer_tv->getRootDomain()
+                                      : consumer_tv->getMaybeRFactorDomain();
 
   // First collect all iterdomains in consumer transform history.
   auto all_consumer_vals = DependencyCheck::getAllValsBetween(
-      {consumer_tv->getMaybeRFactorDomain().begin(),
-       consumer_tv->getMaybeRFactorDomain().end()},
+      {consumer_root.begin(), consumer_root.end()},
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_index_compute.cpp:807]: Haven't caught up with the new indexing changes, so tagging @shmsong

**Review by naoyam — COMMENTED** [review]
Comments so far. Haven't looked at the view changes yet.

File: torch/csrc/jit/codegen/cuda/transform_view.cpp [hunk 11]
```diff
@@ -372,365 +439,254 @@ class AnalyzeViewTransformation {
...
   std::vector<std::shared_ptr<ViewTransform>> view_transforms_;
   std::vector<std::shared_ptr<BroadcastTransform>> broadcast_transforms_;
   std::vector<std::shared_ptr<TrivialReductionTransform>>
       trivial_reduction_transforms_;
 
-  bool default_implicit_broadcast_ = true;
+  // If root domain isn't provided always assume size-1 dimensions are
+  // compile-time dimensions. TODO: Remove runtime size-1 dimension support.
+  // This should be cached higher in the stack.
+  bool root_domain_not_provided_ = true;
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/transform_view.cpp]:
```suggestion
  const bool root_domain_not_provided_ = true;
```

File: torch/csrc/jit/codegen/cuda/arith.cpp (hunk 5 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/arith.cpp:1250]: It generally should not happen and I'd honestly like considering it an error at this point. Size-1 dimensions should always be specialized on and that should happen in this case too. We should just mark it broadcast and not worry about expand in that instance.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 7 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp]: We shouldn't actually expand a tensor until we have to. Until it's resolved expand is just a broadcast. Expand is really just a WAR that when we don't actually resolve the broadcast from an expanded dim, we still have to return its expanded size instead of 1.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp]: We want the expanded extent to be 1 as we just consider it a broadcast dim, not a physical dim. So here we just treat it like a broadcast dim.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 8 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:873]: as above

File: torch/csrc/jit/codegen/cuda/ir_nodes.cpp (hunk 9 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/ir_nodes.cpp:1193]: It can be now, will remove the comment. It's used for transformations to do a view. View concretizes the broadcast dimensions with an expanded extent, so it's really just tracking for view.

File: torch/csrc/jit/codegen/cuda/lower_index_compute.cpp (hunk 10 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_index_compute.cpp:807]: Yeah, I was quite surprised we didn't index consumers all the way back to roots. This was a bug as far as I'm concerned in indexing.

File: torch/csrc/jit/codegen/cuda/transform_view.cpp [hunk 12]
```diff
@@ -372,365 +439,254 @@ class AnalyzeViewTransformation {
...
-        avt_->transform_view_[state_.transform_view_index] /= split_factor_;
-        avt_->addSplitTransform(split_factor_, is_last_axis_rfactor);
-      } else {
-        avt_->addKeepTransform(is_last_axis_rfactor);
+      if ((new_view_index == new_view_.size() ||
+           (new_view_[new_view_index + 1] != 1)) &&
+          original_view_index + 1 < original_view_.size() &&
+          original_view_[original_view_index + 1] == 1 &&
+          !isImplicitBroadcast(original_view_index + 1)) {
+        // Next index in original_view is runtime size 1 and next next new view
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/transform_view.cpp]: nit: "next next"

File: torch/csrc/jit/codegen/cuda/transform_view.h [hunk 13]
```diff
@@ -34,17 +34,71 @@ class ViewTransform;
...
   std::vector<int64_t> original_constraint;
   std::vector<int64_t> new_constraint;
+  // Just the positions of true in AnalyzeViewResult::trivial_reduction_axes
+  std::vector<int64_t> trivial_reduction_string;
+  // Just the positions of true in AnalyzeViewResult:broadcast_axes
+  std::vector<int64_t> broadcast_string;
+  // A stringified version of the transformations:
+  std::vector<int64_t> split_merge_string;
+
+  std::vector<int64_t> conglomerateString() const {
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/transform_view.h:53]: nitpick. `String` in the name is conflicting to the fact that we are returning a vector here. :wink:

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 14]
```diff
@@ -777,13 +777,21 @@ kir::ExpressionEvaluator bindKernelInputs(
...
 
       for (const auto dim : c10::irange(root_domain.size())) {
-        Val* extent = nullptr;
+        const auto extent = root_domain[dim]->extent();
         if (root_domain[dim]->hasExpandedExtent()) {
-          extent = root_domain[dim]->expandedExtent();
-        } else {
-          extent = root_domain[dim]->extent();
+          TORCH_INTERNAL_ASSERT(
+              aten_tensor.strides()[dim] == 0,
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:783]: Nice assert~~

File: torch/csrc/jit/codegen/cuda/transform_view.h (hunk 13 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/transform_view.h:53]: :-/ yeah, I kind of named it like this on purpose as it's not really a useful data structure, it's much more of a "print". Maybe `canonicalSerialization` is a better term? It should have all information in there and is in theory reversible.

**Review by naoyam — COMMENTED** [review]
Just minor comments

**Comment by naoyam** [comment]
It seems there's some problem with predicate elimination. Just modified `FusionExpandReduce` to use a shape of `(3, 4)`, and the validation fails. 

```
TEST_F(NVFuserTest, FusionExpandReduce_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto tv0 = makeConcreteTensor({1, 4});
  fusion->addInput(tv0);

  auto tv1 =
      expand(tv0, {IrBuilder::create<Int>(3), IrBuilder::create<Int>(4)});

  auto tv2 = sum(tv1, {0});
  fusion->addOutput(tv2);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);
  auto t0 = at::randn({1, 4}, options);

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs({t0});

  auto ref = t0.expand({3, 4}).sum({0});

  testValidate(
      executor_cache.fusion(), cg_outputs, {t0}, {ref}, __LINE__, __FILE__);
}
```

It passes with the predicate elimination disabled.

**Comment by naoyam** [comment]
This fusion doesn't give any error, which seems wrong.

```
TEST_F(NVFuserTest, FusionExpandTest_CUDA) {
  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr;
  FusionGuard fg(&fusion);
  std::vector<bool> contiguity{false, false};

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);

  std::vector<IterDomain*> domains = {
    IterDomainBuilder(
        FusionGuard::getCurFusion()->zeroVal(), IrBuilder::create<Int>())
    .build(),
    IterDomainBuilder(
        FusionGuard::getCurFusion()->zeroVal(), IrBuilder::create<Int>(1))
    .expanded_extent(IrBuilder::create<Int>(10))
    .iter_type(IterType::Broadcast)
    .build()};

 // expand to 10
  TensorView* tv22 = IrBuilder::create<TensorView>(
      IrBuilder::create<TensorDomain>(domains, contiguity), DataType::Float);

  fusion.addInput(tv22);

  auto tv3 = add(tv0, tv22);
  fusion.addOutput(tv3);

  fusion.printMath();

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);

 // Incompatible shapes
  at::Tensor input1 = at::randn({2, 3}, options);
 // Passing expand size of 5, not 10. Should cause an error
  at::Tensor input4 = at::randn({2, 1}, options).expand({2, 5});

  std::vector<IValue> aten_inputs = {input1, input4};

  FusionExecutorCache executor_cache(std::move(fusion_ptr));
  auto outputs = executor_cache.runFusionWithInputs(aten_inputs);
}
```

**Review by naoyam — APPROVED** [review]
LGTM. Found some concerning cases while trying the branch. Not sure how critical they are.

**Comment by jjsjann123** [comment]
This PR does fix upstream failures on benchmark. 
Looking forward to have it merged :star_struck:

**Comment by csarofeen** [comment]
Trying to sort out the predicate elimination issue Naoya found, it's a real issue.

**Comment by csarofeen** [comment]
@naoyam I patched predicate elimination for expands going into reduction. I'm going to pull this PR in as we have upstream failures and want to get those patched. However, when you have some time could you review the predicate elimination issue? I've added your repro just disconnected it from the scheduler to make sure scheduler changes don't change that test. I'm having trouble telling if it's an expand only issue, but believe it is as I had trouble reproducing it without the expand which has the broadcast being resolved in the reduction.

Soft tagging @shmsong as I'm worried about how we're making domain's for MMA, as we may want to have the same change for expand in the MMA arith function. We need to put expand support for MMA, as someone could expand then immediately matmul. @shmsong could you make a note somewhere so we don't forget before we enable matmul support.

**Comment by csarofeen** [comment]
Merging as is, tests all passing. CC @jjsjann123
