### PR TITLE
Fix register allocation in MisalignedVectorize

### LINKED ISSUE #1089: MisalignedVectorize uses dynamic indexing to register arrays
This was found with #1088. For example, here's from `FusionVectorizeMisalignedPointwise`:

```
    if ((last_root_domain_index == 0)) {
      #pragma unroll 1
      for(nvfuser_index_t ki145 = 0; ki145 < shift; ++ki145) {
        T4[ki145]
           = T1[(((nvfuser_index_t)blockIdx.x) * (1 * T0.size[1])) + (((ki128 * (64 * 4)) + ((((nvfuser_index_t)threadIdx.x) * 4) + ki145)) * 1)];
      }
```

The `ki145` loop is not unrollable as `shift` is not a static value, so accessing `T4` with `ki145` makes the tensor allocated on a stack frame.

```
ptxas info    : 36 bytes gmem
ptxas info    : Compiling entry function '_ZN11CudaCodeGen7kernel1ENS_6TensorIfLi2EEES1_S1_' for 'sm_75'
ptxas info    : Function properties for _ZN11CudaCodeGen7kernel1ENS_6TensorIfLi2EEES1_S1_
ptxas         .     32 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 28 registers, 472 bytes cmem[0]
```

I haven't evaluated how much penalty this actually causes, but I wonder if loads and stores are actually vectorized if buffers are not allocated using registers.

I think one way we could do would be make `shift` a constant integer and inserts a proper predicate inside the loop body. Not sure how easily this could be done with the existing predicate generator.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #1089 

Make the loop stop value constant and predicate the loop body with `shift`.

Before:
```
#pragma unroll 1
for(nvfuser_index_t ki145 = 0; ki145 < shift; ++ki145) {
  T4[ki145]
       = T1[(((nvfuser_index_t)blockIdx.x) * (1 * T0.size[1])) + (((ki128 * (64 * 4)) + ((((nvfuser_index_t)threadIdx.x) * 4) + ki145)) * 1)];
}
```

After:
```
#pragma unroll
for(nvfuser_index_t ki145 = 0; ki145 < 4; ++ki145) {
   if (ki145 < shift) {
     T4[ki145]
       = T1[(((nvfuser_index_t)blockIdx.x) * (1 * T0.size[1])) + (((ki128 * (64 * 4)) + ((((nvfuser_index_t)threadIdx.x) * 4) + ki145)) * 1)];
    }
}
```

Also, a couple of minor fixes around unrolling.

Confirmed none of `Misaligned*` tests involves stack frame usage.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp [hunk 1]
```diff
@@ -393,14 +395,26 @@ class MisalignedVectorizationModifier {
...
           fl->index(),
           ir_builder.zeroVal(),
-          stop,
+          loop_stop,
           ir_builder.oneVal(),
           vectorize && has_vectorize_op,
           vectorize_shift,
           fl->isUnrollRequired());
 
+      auto body = &new_loop->body();
```
Comment (rdspring1) [inline torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp:404]: Wouldn't we lose access to the for-loop body, since it is replaced with the ITE then body?

I was thinking of this more conservative approach:
```
if (pred_stop != nullptr) {
  // Create new predicate and ITE
  // Add old for-loop expressions to ITE then body
  // Add ITE to new for-loop body
} else {
 // Add old for-loop expressions to new for-loop body
}
```

**Review by rdspring1 — COMMENTED** [review]
LGTM, just a minor comment on adding ITE to the for-loop.

File: torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp:404]: Yes, `body` becomes a pointer to the then body, but that's the only scope we need, isn't it? Do we need to add anything to the loop body but not in the IfThenElse body?

Comment (rdspring1) [reply torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp:404]: Not that I can think of, but it seems odd that the for-loop body scope is lost. In lower_unroll, the for-loop body is preserved when adding predicates. 

https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/lower_unroll.cpp#L119-L129

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_misaligned_vectorization.cpp:404]: Not completely sure what the issue is, but `body` is just a pointer, so we don't really lose the scope. It can be still accessed by `new_loop->body()`.

**Review by rdspring1 — APPROVED** [review]
