### PR TITLE
Fix concrete domain selection with view rfactor domains

### LINKED ISSUE #1493: Indexing failure with view
This test fails at indexing with the TOT branch:

```
TEST_F(NVFuserTest, FusionViewConcreteDomain2_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  auto tv1 = makeContigTensor(2);
  fusion.addInput(tv1);

  auto tv2 = view(tv0, {2, 3}, {6});
  auto tv3 = add(tv2, IrBuilder::create<Double>(1));
  auto tv4 = broadcast(tv3, {true, false});
  auto tv5 = add(tv4, tv1);

  fusion.addOutput(tv5);

  tv5->merge(0);
  tv0->computeAt(tv5, -1);
  tv1->computeAt(tv5, -1);

  fusion.printMath();
  fusion.printKernel();
}
```

```
C++ exception with description "root_ind != nullptrINTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/index_compute.cpp":1492, please report a bug to PyTorch. Couldn't find root mapping for TV1 dim: 1 id: iS21{T1.size[0]}
```

The problem seems to have something to do with how we choose concrete domains.

The failure fusion was based on the failing case of https://github.com/csarofeen/pytorch/pull/1451/files/f582e16adf5d1681d76a181cd3a17c217df6da45?show-viewed-files=true&file-filters%5B%5D=#r813879270, but simplified to reproduce with TOT.

### PR DESCRIPTION
**Pull request by naoyam**
With this change, the loop map of the repro is:

```
Loop map
  disjoint_set{ iS20{T0.size[1]}*, iS18{T0.size[1]} }
  disjoint_set{ iS19{T0.size[0]}*, iS17{T0.size[0]} }
  disjoint_set{ iS14{( T0.size[0] * T0.size[1] )}, iS6{( T0.size[0] * T0.size[1] )}rf, iS7{( T0.size[0] * T0.size[1] )}, iS13{( 1 * ( T0.size[0] * T0.size[1] ) )}, iS9{( T0.size[0] * T0.size[1] )}, iS12{( T1.size[0] * ( T0.size[0] * T0.size[1] ) )}*, iS11{( T0.size[0] * T0.size[1] )}, iS15{( T1.size[0] * T1.size[1] )}, iS22{T1.size[1]} }
  disjoint_set{ bS8{1}, iS16{T1.size[0]}*, iS21{T1.size[0]} }
```

I'm not very confident, but I can't think of any counter example. All the C++ and Python tests pass.

Fixes #1493

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/compute_at_map.cpp [hunk 1]
```diff
@@ -441,16 +441,42 @@ void ComputeAtMap::build(Fusion* fusion, GpuLower* gpu_lower) {
...
-          max_broadcast_count = broadcast_count;
-          concrete_id = id;
+      // If the previous ID is an rfactor, reset the concrete ID with
+      // this ID no matter how many IDs the previous concrete ID has.
+      if (rf_detected) {
+        concrete_id = id;
+        max_concrete_count = n_concrete_ids_.at(id);
+        max_broadcast_count = n_broadcast_ids_.at(id);
+        rf_detected = id->isRFactorProduct();
+      } else {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/compute_at_map.cpp:468]: Wouldn't we still want to prefer rfactor axes with greater `concrete_counts`, just not overwrite an rfactor entry with a non-rfactor entry? i.e. couldn't is_rf be the strongest condition on greater than in this check?

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:468]: An rfactor domain can still reach pre-view concrete root domains, so it has the same number of concrete domains as the pre-view domains. In the repro example, that's this domain: `iS6{( T0.size[0] * T0.size[1] )}rf`. The problem is it is not complete as it does not have the broadcast domain created after the view operation. So, when any domains following view rfactor domains should be prioritized. Within the rest of the domains, I don't think we would need any additional ordering constraints other than we already have.

**Review by csarofeen — APPROVED** [review]
LGTM
