### PR TITLE
Segment independent component on fusion graph

### LINKED ISSUE #1284: codegen error with independent data flow / horizontal fusion
## 🐛 Bug

Horizontal fusion with two independent inputs hits a codegen error:
`unknown file: Failure
C++ exception with description "reference_tv != nullptrINTERNAL ASSERT FAILED at "/raid/pytorch_10_1/torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp":550, please report a bug to PyTorch. Could not find a fully broadcasted output to reference schedule on.`

The fusion pattern is a little awkward, where we have two independent data flow in the fusion.

```
  TensorView* in_0 = makeSymbolicTensor(input_shape_0.size());
  TensorView* in_1 = makeSymbolicTensor(input_shape_1.size());
  fusion.addInput(in_0);
  fusion.addInput(in_1);

  TensorView* out_0 = add(in_0, new Double(0.0));
  TensorView* out_1 = add(in_1, new Double(2.0));

  fusion.addOutput(out_0);
  fusion.addOutput(out_1);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_in_0 = at::randn(input_shape_0, options);
  at::Tensor at_in_1 = at::randn(input_shape_1, options);
  std::vector<IValue> aten_inputs = {at_in_0, at_in_1};

  FusionExecutorCache fec(std::move(fusion_ptr));
  auto outputs = fec.runFusionWithInputs(aten_inputs);
```

Whether we should fuse this case or not is a separate question, but we shouldn't be hitting codegen error. In the worst case where PW scheduler can't handle it, we should separate the kernels into two and still be functional.

### PR DESCRIPTION
**Pull request by shmsong**
Fixes #1284 on the segmenter end. Forces fusions with independent/un-connected components to be in different kernels. 

- Analysis is done in compile time so wouldn't affect runtime heuristic behavior. 
- Also contains a minor fix on segmenter pass on avoiding querying heuristics on empty groups, which will be eliminated following #1371

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp [hunk 1]
```diff
@@ -496,14 +498,25 @@ std::vector<at::Tensor> FusionKernelRuntime::runWithInput(
...
-            output->as<TensorView>()->nDims() == 0 &&
-                output->getDataType().has_value() &&
-                output->getDataType().value() == DataType::Float,
+            empty_tensor_check && empty_type_check,
             "Non empty tensor cannot be found at tensor_map in ",
             __FUNCTION__);
-        fusion_outputs.emplace_back(at::Tensor());
+        const auto tensor_options =
+          at::TensorOptions().dtype(at::kFloat).device(device);
+        fusion_outputs.emplace_back(at::empty({0},tensor_options));
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: @jjsjann123 @rdspring1 some suggestions needed here on `test_batch_norm_half`

2 minor details both related to the empty tensors in inference mode:

1.  [https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/ops/normalization.cpp#L343-L344](https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/ops/normalization.cpp#L343-L344)
The op seems to pass a dim-1 size-0 tensor to represent empty while the check here expects dim-0. I just changed here to support both cases but maybe we could just consistently use one case to represent "empty". 

2. It looks like ShapeAnalysis in torchscript does not like passing to batchnorm backward just an at::Tensor(), though I wasn't sure if we need to test backward when not tracking running stats. A dim-1 size-0 tensor works, but we'd need to actually allocate a tensor in here. 

Would appreciate any suggestions.

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Hmmm, wondering how this slips through our python BN tests. :confused: 

1. good catch with the inconsistencies! Christian wanted a refactor on us generating size-0 tensors. I'll follow up with that and clean things up afterwards. I don't know if there's a canonical way to init size-0 tensors, dim-0 size-0 sounds like a reasonable representation to me, but I think in aten, I've seen all crazy representations (for scalar tensors), so maybe we can put a real check that iterates through all dimensions?
i.e. `TensorView::is_zero_tensor()` and `TensorView::is_scalar_tensor()` Any thoughts? (we don't have to do it in this PR though :heart: )

2. Is it just complaining about missing other tensor options?
> I wasn't sure if we need to test backward when not tracking running stats
There's some CI running that, IIRC, so yes we still do. (And I thought it worked at some point).
Same as above, dim-1 size-0 maybe fine here. Would you mind putting a TODO, so we'll clean it up later as well.

Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Sure I can add a TODO here. 

Regarding 2:
This is the error message if we use a `at::Tensor` as the output. Looks like an arg matching problem at a glance. 

```
torch/csrc/jit/ir/alias_analysis.cpp":611, please report a bug to PyTorch. We don't have an op for aten::_batch_norm_impl_index_backward but it isn't a special case.  Argument types: int, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, bool, float, bool[], Tensor, 

Candidates:
        aten::_batch_norm_impl_index_backward(int impl_index, Tensor input, Tensor grad_output, Tensor? weight, Tensor? running_mean, Tensor? running_var, Tensor? save_mean, Tensor? save_var_transform, bool train, float eps, bool[3] output_mask, Tensor reservedSpace) -> (Tensor, Tensor, Tensor)

```

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: It's the aliasDB entries.
hmmm, that looks strange... as the signature which it complaints seem to match the signature from the candidates, except it's expecting an optional tensor but we are giving a size-0 tensor. No idea why that would trigger an error. :shrug:

Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: I think it's about not having a dtype for the tensor, and Tensor[Undefined] != Tensor in here:
[https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/ir/ir.cpp#L1032-L1034](https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/ir/ir.cpp#L1032-L1034)

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp [hunk 2]
```diff
@@ -2721,8 +2721,10 @@ void SegmentCandidateFinder::findSegments() {
   }
 
   for (auto group : groups()) {
-    // Set heuristics in case single reduction kernels were left out
-    group->setHeuristic(deriveHeuristic(group));
+    if(!group->outputs().empty()){
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp]: Curious why we are getting here with an group that has no outputs. In that case, should we clean and remove this group?

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp [hunk 3]
```diff
@@ -1085,8 +1129,13 @@ bool checkCanSchedule(
   // since for all current use cases
   //  it has to pass all the compile time checks to create a data cache for this
   //  fusion.
-  if (!data_cache && !SchedulerType::canScheduleCompileTime(fusion)) {
-    return false;
+  if (!data_cache){
+    if(!isConnectedFusionGraph(fusion)){
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/scheduler/registry.cpp]: So independent data flow is disabled for all schedulers? I thought it only breaks PW scheduler and we would still want horizontal fusion for others. I could be wrong though.

**Review by jjsjann123 — COMMENTED** [review]
LGTM, a quick question on the scope to disable PW scheduler, I thought the idea is to only limit it to PW schedulers, which can't support outputs with mismatched shapes.

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp (hunk 2 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp]: Yes it's a tech debt that I will cleanup, tracking in #1371.

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp (hunk 3 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp]: My understanding is that independent data flow would not work smoothly on other heuristics either. If even root domain map doesn't have useful info on the un-connected components, it's hard to have a sound analysis on the tensor dimensions and parallelization strategy, unless we restrict some analysis to static shapes I guess.

Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp]: But I guess these cases wouldn't be sent to reduction or persistent schedulers either way, since root domain map was used in the canSchedule check.

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp]: Got ya.

**Review by jjsjann123 — APPROVED** [review]
LGTM.

Note that this WAR being as necessary as it is to give us functional codegen on cases with independent data flow with mis-match shapes, it also disabled proper fusion of shared inputs that does generate the same output shapes, hence undermining the effort of horizontal/sibling fusion. :cry:

**Comment by shmsong** [comment]
> LGTM.
> 
> Note that this WAR being as necessary as it is to give us functional codegen on cases with independent data flow with mis-match shapes, it also disabled proper fusion of shared inputs that does generate the same output shapes, hence undermining the effort of horizontal/sibling fusion. 😢

Thanks for stamping. 

Just curious by horizontal fusion with `shared input` do you mean ops that actually use the same input but do independent computations or ones that are completely independent but just happen to have the same shape?

**Comment by jjsjann123** [comment]
> > LGTM.
> > Note that this WAR being as necessary as it is to give us functional codegen on cases with independent data flow with mis-match shapes, it also disabled proper fusion of shared inputs that does generate the same output shapes, hence undermining the effort of horizontal/sibling fusion. cry
> 
> Thanks for stamping.
> 
> Just curious by horizontal fusion with `shared input` do you mean ops that actually use the same input but do independent computations or ones that are completely independent but just happen to have the same shape?

Oops,
We are looking at shared inputs that are used by different operators producing mis-match outputs. Which doesn't seem to be disabled in this PR? So you are not disabling that. I was talking non-sense. :stuck_out_tongue_closed_eyes: 

IIRC, that case also breaks PW scheduler. Can you quickly add another cpp example for that?

```
output0 = input0 + input1
output1 = input0 + input2
return output0, output1
```
where shape-wise we'll have maybe `input0@[4,4]`, `input1@[3, 4, 4]` and `input2@[2, 8, 4, 4]` something like this.

**Comment by shmsong** [comment]
> > > LGTM.
> > > Note that this WAR being as necessary as it is to give us functional codegen on cases with independent data flow with mis-match shapes, it also disabled proper fusion of shared inputs that does generate the same output shapes, hence undermining the effort of horizontal/sibling fusion. cry
> > 
> > 
> > Thanks for stamping.
> > Just curious by horizontal fusion with `shared input` do you mean ops that actually use the same input but do independent computations or ones that are completely independent but just happen to have the same shape?
> 
> Oops, We are looking at shared inputs that are used by different operators producing mis-match outputs. Which doesn't seem to be disabled in this PR? So you are not disabling that. I was talking non-sense. 😝
> 
> IIRC, that case also breaks PW scheduler. Can you quickly add another cpp example for that?
> 
> ```
> output0 = input0 + input1
> output1 = input0 + input2
> return output0, output1
> ```
> 
> where shape-wise we'll have maybe `input0@[4,4]`, `input1@[3, 4, 4]` and `input2@[2, 8, 4, 4]` something like this.

I see. This fails too. Thanks for pointing this out. 

This one looks different from independent dataflow which I thought was what needed disabling. This issue affects any fusion with an unmapped branching. I'll take a look.

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp [hunk 4]
```diff
@@ -857,6 +903,14 @@ class PointWiseScheduler : public SchedulerEntry {
   }
 
   static bool canScheduleCompileTime(Fusion* fusion) {
+    // TODO: extend this for view support
+    //   Currently using the same path as the scheduler
+    // to eliminate mismatch between canSchedule and
+    // schedule pointwise.
+    if (!hasReferenceTensorView(fusion)) {
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:909]: @csarofeen I think we want to use the same code path for this check for `canSchedule` and `schedule` to ensure not hitting similar errors. This will unblock the current issue. 

Could we use this as an intermediate state and later maybe build out on `DomainMap` for view support?

File: test/cpp/jit/test_gpu.cpp [hunk 5]
```diff
@@ -19663,6 +19663,84 @@ TEST_F(NVFuserTest, FusionNonDivisibleSplitVectorize2_CUDA) {
...
+  at::Tensor at_in_1 = at::randn(input_shape_1, options);
+  std::vector<IValue> aten_inputs = {at_in_0, at_in_1};
+
+  FusionExecutorCache fec(std::move(fusion_ptr));
+  auto outputs = fec.runFusionWithInputs(aten_inputs);
+
+  auto t1 = at_in_1 + 2;
+
+  testValidate(
+      &fusion, outputs, {at_in_0, at_in_1}, {at_in_0, t1}, __LINE__, __FILE__);
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu.cpp:19700]: Could you also check it's segmented?

File: test/cpp/jit/test_gpu.cpp [hunk 6]
```diff
@@ -19663,6 +19663,84 @@ TEST_F(NVFuserTest, FusionNonDivisibleSplitVectorize2_CUDA) {
...
+  auto t0 = at_in_0 + at_in_1;
+  auto t1 = at_in_0 + at_in_2;
+
+  testValidate(
+      &fusion,
+      outputs,
+      {at_in_0, at_in_1, at_in_2},
+      {t0, t1},
+      __LINE__,
+      __FILE__);
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu.cpp:19749]: Could you also check it's segmented?

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp [hunk 7]
```diff
@@ -496,14 +498,29 @@ std::vector<at::Tensor> FusionKernelRuntime::runWithInput(
       if (iter != runtime_workspace_.tensor_map.end()) {
         fusion_outputs.push_back(iter->second);
       } else {
+        bool empty_type_check = output->getDataType().has_value() &&
+            output->getDataType().value() == DataType::Float;
+
+        // Only support two cases of empty tensor here, since
+        //   this is hot path.
+        auto out_tv = output->as<TensorView>();
+        bool empty_tensor_check = out_tv->nDims() == 0;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Can you put this as a member to TensorView similar to hasReduction?

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp [hunk 8]
```diff
@@ -496,14 +498,29 @@ std::vector<at::Tensor> FusionKernelRuntime::runWithInput(
       if (iter != runtime_workspace_.tensor_map.end()) {
         fusion_outputs.push_back(iter->second);
       } else {
+        bool empty_type_check = output->getDataType().has_value() &&
+            output->getDataType().value() == DataType::Float;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/kernel_cache.cpp:502]: Are empty tensors only allowed to have Float type? Can we not have any other type that's empty?

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp [hunk 9]
```diff
@@ -391,6 +391,12 @@ class DomainMap {
     return nullptr;
   }
 
+  static bool hasReferenceTensorView(Fusion* fusion) {
+    FusionGuard fg(fusion);
+    DomainMap domain_map(fusion);
+    return domain_map.findReferenceTensorView() != nullptr;
+  }
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp:398]: Is `areAllMapped` correct? A little worried about line 420/426 below, we could skip mapping any axes that map to an output broadcast, but why would we skip a broadcast on an input if it is resolved? I think it should be:
```.cpp
    for (auto in_id : input_tv->getMaybeRFactorDomain()) {
      if (!ca_index_map_.getConcreteMappedID(in_id)->isBroadcast() && !in_id->isReduction()) {
        in_concrete_ids.insert(ca_index_map_.getConcreteMappedID(in_id));
      }
    }
```

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp:398]: I think the view portion looks fine, but please double check that as well as this.

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp [hunk 10]
```diff
@@ -355,6 +357,50 @@ class SchedulerTopologyChecker {
     return true;
   }
 };
+
+bool isConnectedFusionGraph(Fusion* fusion) {
+  if (fusion->outputs().empty()) {
+    // Trivial case interpreted as connected
+    return true;
+  }
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:365]: I think what you built is that empty kernels will just not do anything, is that correct? If only an empty kernel is sent to fusion executor cache will it also be skipped?

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp (hunk 4 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:909]: I think the reference check correctly handles view, I forgot we even had that logic, thanks for tracking it down. I don't know if there's anything else we need to worry about. Is there another case that will fail today?

**Review by csarofeen — APPROVED** [review]
After you look into the one part  mentioned in grabbing the reference tensor you can merge this in. Thanks!

**Comment by rdspring1** [comment]
Just as a reminder for myself. In a follow-up PR, we could have the segmenter cache the reference tensor for the scheduler, since creating the `DomainMap` is an expensive operation.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp (hunk 9 above)
Comment (rdspring1) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp:398]: It makes sense to check any input broadcast axes if they are mapped to a concrete iterDomain (e.g., resolved broadcast).

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp (hunk 4 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:909]: I see. The reference check looks fine for now. Didn't see more failure cases. Updated comment to remove "TODO".

File: test/cpp/jit/test_gpu.cpp (hunk 5 above)
Comment (shmsong) [reply test/cpp/jit/test_gpu.cpp:19700]: Updated Thanks!

File: test/cpp/jit/test_gpu.cpp (hunk 6 above)
Comment (shmsong) [reply test/cpp/jit/test_gpu.cpp:19749]: Updated Thanks!

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp (hunk 7 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Updated Thanks!

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp (hunk 8 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp:502]: This is just legacy code movement but I think we should handle other types in empty tensors once the empty tensor definition is uniform. Will address this in a follow up.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp (hunk 9 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp:398]: Updated. Thanks!

File: torch/csrc/jit/codegen/cuda/scheduler/registry.cpp (hunk 10 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/scheduler/registry.cpp:365]: This is boundary case handling. An empty graph is considered "connected" in this check, so yes this check would not do anything. 

Skipping empty fusion looks like a separate issue to address. There are a few cases we need to define the right behavior. Thanks for pointing this out 👍 . Tracking this in #1385, with more details and will handle in a separate PR.
