### PR TITLE
Disable reuse of x_mean_sub in translateSingleWelford

### LINKED ISSUE #2321: Disable reuse of x_mean_sub in translateSingleWelford
### 🐛 Describe the bug

Tested NVFuserTest.FusionMagicSchedulerLayerNormalization_CUDA with shape of 2048 x 10240 in half precision:
if set reuse_x_mean_sub = true, generated kernel will use  float T3[((10 * 1) * 8)]; to store input and then x_mean_sub.
if set reuse_x_mean_sub = false, generated kernel will use Array<__half, ((10 * 1) * 8), 8> T30; to store input and x_mean_sub will be re-calculated.
--------------------------------- reason:

Reusing the existing tensors results in causing T10 to be persistent, which makes sense as its use paths go through the reduction+broadcast path. Not reusing it does not cause it as it effectively recomputes T10. When T10 is determined as persistent, since it's not possible to be projected, the buffer is allocated as a buffer of float, so that's why T3 is cached as a float buffer.

(Projection of persistent buffers means that caching an input as its original type rather than its upcast type. When an input is half, we always cast it to float before doing any arithmetic computations. Our analysis first detects an upcast tensor must be persistent, and then the projection analysis determines if it's possible to cache the input tensor in its original type. This only matters when an input type is lower precision than the type it's actually used)

This is a rather complex unexpected interaction with the translation, and I think it deserves its own PR so that we could easily look back. Could you please create a new separate PR that just disables the reuse? Please also add a unit test. I don't know if there's any case we wanted to reuse, so it should be fine to always not reuse it.

https://github.com/csarofeen/pytorch/pull/2302#:~:text=Reusing%20the%20existing,not%20reuse%20it.

### Versions

207e7ca85f48520688a7eac34e382ee254cdfac2

### PR DESCRIPTION
**Pull request by liqiangxl**
Fixes #2321

### CODE REVIEW

**Comment by naoyam** [comment]
Could you please add a unit test that verifies the persistent buffer is created as a half tensor?

File: third_party/nvfuser/csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -1949,7 +1952,7 @@ bool TranslateApplicableWelford::wouldTranslateToPersistent(
   return isValidPersistentFusion(test_copy.get(), runtime_info);
 }
 
-void TranslateApplicableWelford::translateSingleWelford(WelfordOp* welford) {
+void TranslateApplicableWelford::translateSingleWelford(WelfordOp* welford, bool reuse_x_mean_sub) {
```
Comment (naoyam) [inline third_party/nvfuser/csrc/fusion_segmenter.cpp]: Do you think there's a case where this flag should be `true`? If not let's delete it.

**Comment by naoyam** [comment]
> Could you please add a unit test that verifies the persistent buffer is created as a half tensor?

Some of the unit tests do validation of generated code by examining the lowered `Kernel`, so those would be helpful to look at. In this case, you'd probably first need to detect the persistent buffer, which should be the buffer loaded from the input. You'd need to make sure it's type half and the computeAt position is set such that it's allocated as the persistent buffer. Let me know if you'd need any help.

File: third_party/nvfuser/test/test_gpu1.cpp [hunk 2]
```diff
@@ -7715,6 +7715,83 @@ TEST_F(NVFuserTest, FusionMagicSchedulerLayerNormalization_CUDA) {
       "");
 }
 
+TEST_F(
```
Comment (naoyam) [inline third_party/nvfuser/test/test_gpu1.cpp]: Please mention the issue or PR number as a comment here.

Comment (naoyam) [reply third_party/nvfuser/test/test_gpu1.cpp]: Also, please move this to test_gpu3.cpp.

File: third_party/nvfuser/test/test_gpu1.cpp [hunk 3]
```diff
@@ -7715,6 +7715,83 @@ TEST_F(NVFuserTest, FusionMagicSchedulerLayerNormalization_CUDA) {
...
+  // welford translate
+  KernelArgumentHolder runtime_inputs =
+      KernelArgumentHolder::createKernelArgumentHolder(
+          {aten_input, aten_weight, aten_bias});
+  bool isTranslated =
+      SegmentCandidateFinder::TranslateWelfordInFusion(&fusion, runtime_inputs);
+  TORCH_INTERNAL_ASSERT(isTranslated);
+
+  // project persistent buffer to input
+  reduction_scheduler_utils::projectPersistentBuffers(&fusion);
```
Comment (naoyam) [inline third_party/nvfuser/test/test_gpu1.cpp]: No need to do this, and actually I'm not sure if it should work. `projectPersistentBuffers` may add dummy outputs, which are subsequently removed when used in schedulers, but here they seem to remain, which may result in unexpected outputs.

Instead, I believe you can just assert that :

```
auto persistent_buffer_info = scheduler_utils::persistentBuffers(&fusion);
persistent_buffer_info.projectable_buffers().size() == 1
persistent_buffer_info.projectable_buffer_inputs().size() == 1
persistent_buffer_info.projectable_buffer_inputs()[0] == input_half
```

**Review by naoyam — APPROVED** [review]
Looks good. The only remaining question is whether the broadcast should be reused. I have a PR to fix the segmentation issue (#2350), so reusing should be fine.
