### PR TITLE
Detect non-concretized broadcast domains

### LINKED ISSUE #1410: Error with too many blocks when launching a cooperative kernel
```
import torch
from torch import fx

def forward(sqrt, div_1, neg):
    div_2 = torch.ops.aten.div(div_1, sqrt);  div_1 = None
    mul_12 = torch.ops.aten.mul(neg, div_2);  neg = div_2 = None
    sum_4 = torch.ops.aten.sum(mul_12, [1], True);  mul_12 = None
    mul_13 = torch.ops.aten.mul(sqrt, 2);  sqrt = None
    div_4 = torch.ops.aten.div(sum_4, mul_13);  sum_4 = mul_13 = None
    return (div_4,)

inps = [(torch.Size([8, 1, 128, 128]), torch.float32), (torch.Size([8, 192, 128, 128]), torch.float32), (torch.Size([8, 192, 128, 128]), torch.float32)]
inps = [torch.randn(shape, dtype=dtype, device='cuda') for shape, dtype in inps]
f = torch.jit.script(forward)
with torch.jit.fuser("fuser2"):
  for _ in range(5):
    f(*inps)
```

```
RuntimeError: (int64_t)( num_blocks_per_SM * at::cuda::getDeviceProperties(options_.device.index()) ->multiProcessorCount) >= launch_params.gdimx() * launch_params.gdimy() * launch_params.gdimz()INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":711, please report a bug to PyTorch. Wanted to launch a cooperative kernel, however the number of blocks is greater than what can be resident on the GPU at once. Need: 2048 but limited to 3 * 108
```

### PR DESCRIPTION
**Pull request by naoyam**
Detect non-concretized broadcast domains so that unnecessary parallel broadcast operations should not be generated.

Needed to clean up the thread predicate info passed to Kernel. The only necessary information is which parallel types are in fact parallel in broadcast ops, so a map holding that information is added to KernelSummary. ThreadPredicateMap is dropped from Kernel.

The repro of #1410 no longer generates a grid broadcast call.

Closes #1410 and #1411

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+namespace cuda {
+
+namespace {
+
+class ConcretizedBroadcastDomains : private IterVisitor {
+ public:
+  ConcretizedBroadcastDomains(Fusion* fusion) {
+    for (const auto fusion_input_tv :
+         ir_utils::filterByType<TensorView>(fusion->inputs())) {
+      for (auto root_id : fusion_input_tv->getRootDomain()) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Is this okay to not be rfactor, if a fusion input is the input to a view, does this track through merges? I imagine we could merge broadcast root domains with non-broadcast root domains. On second thought I think this would be normally tracked through replay tracking.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 2]
```diff
@@ -0,0 +1,176 @@
...
+  void handle(BroadcastOp* bop) final {
+    const auto& pred_map = GpuLower::current()->threadPredMap();
+    auto out_tv = bop->out()->as<TensorView>();
+    const auto domains = pred_map.getParallelBroadcastDomains(out_tv);
+    if (domains.none()) {
+      std::cerr << "No parallel bcast: " << bop->toString() << std::endl;
+      trivial_bops_.insert(bop);
+      return;
+    }
+    bool is_trivial = true;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: I assume you're not done yet, but I think the logic is check all inputs of the parallel broadcast dimensions. If none of them are concretized then it's a trivial broadcast op.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 1 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Yeah, I think this is fine.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Yes, the code below should do that. I'll clean it up and add comments.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 1 above)
Comment (rdspring1) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: We shouldn't merge broadcast root domains with non-broadcast root domains. For that case, we remove them with a trivial reduction before the view op.

https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/ops/alias.cpp#L63-L65

Broadcast root domains could be passed through the view to the rfactor domain.

**Comment by naoyam** [comment]
Still working on this. 

I mentioned I was planning to replace trivial broadcasts with Set. I realized it's not a good idea. Broadcast adds a new root domain, whereas Set does not. The fact that an expression is `BroadcastOp` is used to detect new broadcast domains (along with `BroadcastOp::getBroadcastDimFlags()`. Such information would be lost if translated to `SetOp`.

File: torch/csrc/jit/codegen/cuda/ir_iostream.cpp [hunk 3]
```diff
@@ -521,6 +521,7 @@ void IrPrinter::handle(const kir::TensorIndex* ti) {
     }
   }
   os_ << "]";
+  os_ << " view( T" << varName(ti->view()) << " )";
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/ir_iostream.cpp:524]: I think it's useful to show which TensorView this TensorIndex corresponds to.

File: torch/csrc/jit/codegen/cuda/kernel.cpp [hunk 4]
```diff
@@ -263,8 +273,6 @@ class ValidateAllocation : private OptOutConstDispatch {
 void Kernel::finalize(std::vector<Expr*> top_level_exprs) {
   TORCH_INTERNAL_ASSERT(top_level_exprs_.empty());
   top_level_exprs_ = std::move(top_level_exprs);
-  predicate_map_ = std::make_unique<ThreadPredicateMap>(
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/kernel.cpp:266]: No longer necessary.

File: torch/csrc/jit/codegen/cuda/kernel.h [hunk 5]
```diff
@@ -72,6 +74,10 @@ struct KernelSummary {
 
   //! ceilDiv extents that must be divisible
   std::vector<std::pair<const Val*, const Val*>> splits_to_validate;
+
+  //! Effective ParallelTypes of broadcast ops
+  std::unordered_map<const BroadcastOp*, ParallelTypeBitmap>
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/kernel.h:79]: This effectively replaces `Kernel::predicate_map_`.

File: torch/csrc/jit/codegen/cuda/lower2device.h [hunk 6]
```diff
@@ -132,12 +142,14 @@ class TORCH_CUDA_CU_API GpuLower : public NonCopyable {
...
 
   // Some stateful information during lowering
+  ConcretizedBroadcastDomains concretized_broadcast_domains_;
   ThreadPredicateMap thread_pred_map_;
   PredicateElimination pred_elimination_;
   ComputeAtMap ca_loop_map_;
   ComputeAtMap ca_index_map_;
   ComputeAtMap ca_parallel_map_;
   TrivialReductionInfo trivial_reduction_info_;
+  TrivialBroadcastInfo trivial_broadcast_info_;
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower2device.h]: Turns out this isn't used. Will remove.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+ public:
+  void build(Fusion* fusion);
+
+  //! Return true when a broadcast expression is trivial
+  bool isTrivial(BroadcastOp* bop) const;
+
+ private:
+  //! Set of trivial broadcast domains
+  std::unordered_set<BroadcastOp*> trivial_bops_;
+};
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h]: It turned out that this isn't needed. Is there any potential use case? Otherwise, I'll remove it.

File: test/cpp/jit/test_gpu.cpp [hunk 8]
```diff
@@ -20268,6 +20268,173 @@ TEST_F(NVFuserTest, FusionIntermediateTensorVectorize_CUDA) {
...
+
+  tv2->merge(0, 1);
+  tv2->axis(0)->parallelize(ParallelType::TIDx);
+
+  tv3->merge(0, 1);
+  tv3->axis(0)->parallelize(ParallelType::TIDx);
+
+  fusion.printMath();
+  fusion.printKernel();
+}
```
Comment (naoyam) [inline test/cpp/jit/test_gpu.cpp]: Wanted to test merged broadcast domains, but this test fails even with `devel`. See #1418

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Added a test with view.

I have a question on merging broadcast and non-broadcast domains. Please see #1418

File: torch/csrc/jit/codegen/cuda/ir_iostream.cpp (hunk 3 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/ir_iostream.cpp:524]: Would it be better to make this a little simpler as: `"T"<<ti->view()->name()`

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+  }
+}
+
+void ConcretizedBroadcastDomains::handle(Expr* expr) {
+  IterVisitor::handle(expr);
+
+  // Propagate broadcast origin info from producers to consumers
+  for (auto producer : ir_utils::filterByType<TensorView>(expr->inputs())) {
+    std::unordered_set<IterDomain*> producer_broadcasts;
+    for (auto producer_id : producer->getMaybeRFactorDomain()) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp:53]: Can you mention this assumes broadcast axes are not merged ~with non-broadcast axes~ between root and rfactor?

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 10]
```diff
@@ -0,0 +1,176 @@
...
+}
+
+void ConcretizedBroadcastDomains::markAsConcretized(IterDomain* root_domain) {
+  concretized_domains_.emplace(root_domain);
+  std::deque<IterDomain*> child_domains({root_domain});
+  while (!child_domains.empty()) {
+    auto child = child_domains.front();
+    child_domains.pop_front();
+    const auto& child_uses = child->uses();
+    if (child_uses.size() == 1 && !child_uses[0]->outputs().empty() &&
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Why not just go through all uses and mark every iter domain as concretized?
Couldn't we even use `DependencyChain::getAllDependentVals` to do this?

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 11]
```diff
@@ -0,0 +1,176 @@
...
+
+  using IterVisitor::handle;
+
+  //! Check if a broadcast op is trivial.
+  void handle(BroadcastOp* bop) final {
+    const auto& pred_map = GpuLower::current()->threadPredMap();
+    auto out_tv = bop->out()->as<TensorView>();
+    // ConcretizedBroadcastDomains is used inside
+    // getParallelBroadcastDomains so non-concrete domains are not returned.
+    const auto parallel_types = pred_map.getParallelBroadcastDomains(out_tv);
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: nit on the name: `parallel_broadcast_ids`

**Review by csarofeen — COMMENTED** [review]
Minor changes requested.
Still thinking about the merging of bcast-iter domain issue

File: torch/csrc/jit/codegen/cuda/ir_iostream.cpp (hunk 3 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/ir_iostream.cpp:524]: I'm blind, you had it right 🤦‍♂️

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h (hunk 7 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h]: I think doing what you do in codegen is more convenient than blanket marking broadcast ops as trivial or not. The only thing I might suggest in a follow up is just avoid generating GridBroadcast is it's not broadcasted on the grid. I wonder if we should have explicit blockBroadcast/Reduce nodes, so we can do the same and avoid the complexity later in codegen. If so to be done in a follow up PR, not this one.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 11 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: Code was removed based on https://github.com/csarofeen/pytorch/pull/1412#discussion_r794234903

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 10 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: `DependencyChain::getAllDependentVals` goes in the wrong direction, and the use versions in dependency check just do fusion traversal which starts at terminating outputs, so we'd have to enable the full recursive version of iter visitor which I'm not really ready to do because of perf impact.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: I made this more aggressive in the last commit I pushed, if you don't like this or think it's wrong feel free to revert. I didn't think this condition was important, but I might be wrong as I didn't understand why.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp (hunk 9 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp:53]: Added a comment.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h (hunk 7 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h]: Removed this code.

**Review by csarofeen — APPROVED** [review]

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp [hunk 12]
```diff
@@ -96,27 +96,27 @@ void ConcretizedBroadcastDomains::handle(Expr* expr) {
...
-        std::all_of(
-            child_uses[0]->outputs().begin(),
-            child_uses[0]->outputs().end(),
-            [](const Val* out) { return out->isA<IterDomain>(); })) {
-      for (auto out : child_uses[0]->outputs()) {
-        child_domains.push_back(out->as<IterDomain>());
+    for (auto child_use : child_uses) {
+      for (auto out_id :
+           ir_utils::filterByType<IterDomain>(child_use->outputs())) {
+        if (visited.find(out_id) == visited.end()) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.cpp]: It seems `visited` never gets inserted. This seems to continue traversing as long as `IterDomain` is found in the outputs of `child_use`.

File: torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h (hunk 7 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_trivial_broadcast.h]: Naoya mentioned to me `lower_index` checks `getParallelBroadcastDomains` before it generates a grid broadcast, so it won't generate a node anymore if not a real grid broadcast.
