### PR TITLE
Segmenter bug fix, and deterministic iteration ordering. 

### LINKED ISSUE #1859: Nondeterministic fusion segmentation
### 🐛 Describe the bug

`python.exe test/test_ops.py -k test_python_ref_executor__refs_nn_functional_layer_norm_executor_nvfuser_cuda_float32 -v -f`

run into the issue in the test above.
Notice that on the MSVC build, the last fusion breaks on expanded tensor T22_g, instead of on ubuntu build where it breaks on broadcasted tensor T11_g.

On a ubuntu build, segmentation gives me:
```
Segmented_Fusion Dump: -- Re-written complete fusion:{
Inputs:
  T0_g[ bS0{1}, iS1{i2}, iS2{i3} ], float
  i4, int64_t
  i5, int64_t
  i6, int64_t
  T1_g[ bS3{1}, iS4{i7}, iS5{i8} ], float
  T2_g[ bS6{1}, iS7{i9}, iS8{i10} ], float
  d11, double
Outputs:
  T26_g[ bS75{1}, iS76{i2}, iS77{i3} ], float

%kernel_math {
T12_l[ bS33{1}, iS34{i2}, iS35{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T13_g[ rS36{1}, rS37{i2}, rS38{i3} ]
   = reduction( T12_l[ bS33{1}, iS34{i2}, iS35{i3} ], op = add, initial value = double(0), allreduce = 0 )
T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   = broadcast( T13_g[ rS36{1}, rS37{i2}, rS38{i3} ] )
T15_l[ bS42{1}, bS43{1}, bS44{1} ]
   = T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   / double(6);
T18_g[ bS51{1}, bS52{1}, bS53{1} ]
   = T15_l[ bS42{1}, bS43{1}, bS44{1} ];
T19_l[ bS54{1}, bS55{2}, bS56{3} ] = expand( T18_g[ bS51{1}, bS52{1}, bS53{1} ], {1, 2, 3} )
T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ]
   - T19_l[ bS54{1}, bS55{2}, bS56{3} ];
T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T4_g[ rS12{1}, rS13{i2}, rS14{i3} ]
   = reduction( T3_g[ bS9{1}, iS10{i2}, iS11{i3} ], op = add, initial value = double(0), allreduce = 0 )
T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   = broadcast( T4_g[ rS12{1}, rS13{i2}, rS14{i3} ] )
d18 = (double)(1);
d19 = double(1) * d18;
d20 = (double)(i2);
d21 = d19 * d20;
d22 = (double)(i3);
d23 = d21 * d22;
T6_l[ bS18{1}, bS19{1}, bS20{1} ]
   = T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   / d23;
T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]
   = T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   - T6_l[ bS18{1}, bS19{1}, bS20{1} ];
T8_g[ bS24{1}, iS25{i2}, iS26{i3} ]
   = T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]
   * T7_g[ bS21{1}, iS22{i2}, iS23{i3} ];
T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   = reduction( T8_g[ bS24{1}, iS25{i2}, iS26{i3} ], op = add, initial value = double(0), allreduce = 0 )
d34 = (double)(1);
d35 = double(1) * d34;
d36 = (double)(i2);
d37 = d35 * d36;
d38 = (double)(i3);
d39 = d37 * d38;
T10_g[ 0 ]
   = T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   / d39;
T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   = broadcast( T10_g[ 0 ] )
T16_l[ bS45{1}, bS46{1}, bS47{1} ]
   = T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   + double(0.5);
T17_g[ bS48{1}, bS49{1}, bS50{1} ]
   = rsqrtf(T16_l[ bS45{1}, bS46{1}, bS47{1} ]);
T21_g[ bS60{1}, bS61{1}, bS62{1} ]
   = T17_g[ bS48{1}, bS49{1}, bS50{1} ];
T22_l[ bS63{1}, bS64{2}, bS65{3} ] = expand( T21_g[ bS60{1}, bS61{1}, bS62{1} ], {1, 2, 3} )
T23_g[ bS66{1}, iS67{i2}, iS68{i3} ]
   = T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   * T22_l[ bS63{1}, bS64{2}, bS65{3} ];
T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   = T23_g[ bS66{1}, iS67{i2}, iS68{i3} ]
   * T1_g[ bS3{1}, iS4{i7}, iS5{i8} ];
T25_g[ bS72{1}, iS73{i2}, iS74{i3} ]
   = T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   + T2_g[ bS6{1}, iS7{i9}, iS8{i10} ];
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ]
   = T25_g[ bS72{1}, iS73{i2}, iS74{i3} ];
}

} // {Re-written complete fusion}
Segmented_Fusion Dump: -- fusion segments:
Segmented_Fusion{ 
groups: 
g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

g{11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

g{21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35}

edges: 
e{ g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
 -> g{11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
(T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]) }

e{ g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
 -> g{11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
(T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]) }

e{ g{11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
 -> g{21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35}
(T11_g[ bS30{1}, bS31{1}, bS32{1} ]) }


group details:
g{(persistent)
inputs: 
T0_g[ bS0{1}, iS1{i2}, iS2{i3} ] float
i2 int64_t
i3 int64_t
outputs: 
T7_g[ bS21{1}, iS22{i2}, iS23{i3} ] float


T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T4_g[ rS12{1}, rS13{i2}, rS14{i3} ]
   = reduction( T3_g[ bS9{1}, iS10{i2}, iS11{i3} ], op = add, initial value = double(0), allreduce = 0 )
T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   = broadcast( T4_g[ rS12{1}, rS13{i2}, rS14{i3} ] )
d22 = (double)(i3);
d20 = (double)(i2);
d18 = (double)(1);
d19 = double(1) * d18;
d21 = d19 * d20;
d23 = d21 * d22;
T6_l[ bS18{1}, bS19{1}, bS20{1} ]
   = T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   / d23;
T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]
   = T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   - T6_l[ bS18{1}, bS19{1}, bS20{1} ];
}

g{(reduction)
inputs: 
i2 int64_t
i3 int64_t
T7_g[ bS21{1}, iS22{i2}, iS23{i3} ] float
outputs: 
T11_g[ bS30{1}, bS31{1}, bS32{1} ] float


T8_g[ bS24{1}, iS25{i2}, iS26{i3} ]
   = T7_g[ bS21{1}, iS22{i2}, iS23{i3} ]
   * T7_g[ bS21{1}, iS22{i2}, iS23{i3} ];
T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   = reduction( T8_g[ bS24{1}, iS25{i2}, iS26{i3} ], op = add, initial value = double(0), allreduce = 0 )
d38 = (double)(i3);
d36 = (double)(i2);
d34 = (double)(1);
d35 = double(1) * d34;
d37 = d35 * d36;
d39 = d37 * d38;
T10_g[ 0 ]
   = T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   / d39;
T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   = broadcast( T10_g[ 0 ] )
}

g{(persistent)
inputs: 
T0_g[ bS0{1}, iS1{i2}, iS2{i3} ] float
T1_g[ bS3{1}, iS4{i7}, iS5{i8} ] float
T2_g[ bS6{1}, iS7{i9}, iS8{i10} ] float
T11_g[ bS30{1}, bS31{1}, bS32{1} ] float
outputs: 
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ] float


T12_l[ bS33{1}, iS34{i2}, iS35{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T13_g[ rS36{1}, rS37{i2}, rS38{i3} ]
   = reduction( T12_l[ bS33{1}, iS34{i2}, iS35{i3} ], op = add, initial value = double(0), allreduce = 0 )
T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   = broadcast( T13_g[ rS36{1}, rS37{i2}, rS38{i3} ] )
T15_l[ bS42{1}, bS43{1}, bS44{1} ]
   = T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   / double(6);
T18_g[ bS51{1}, bS52{1}, bS53{1} ]
   = T15_l[ bS42{1}, bS43{1}, bS44{1} ];
T19_l[ bS54{1}, bS55{2}, bS56{3} ] = expand( T18_g[ bS51{1}, bS52{1}, bS53{1} ], {1, 2, 3} )
T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ]
   - T19_l[ bS54{1}, bS55{2}, bS56{3} ];
T16_l[ bS45{1}, bS46{1}, bS47{1} ]
   = T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   + double(0.5);
T17_g[ bS48{1}, bS49{1}, bS50{1} ]
   = rsqrtf(T16_l[ bS45{1}, bS46{1}, bS47{1} ]);
T21_g[ bS60{1}, bS61{1}, bS62{1} ]
   = T17_g[ bS48{1}, bS49{1}, bS50{1} ];
T22_l[ bS63{1}, bS64{2}, bS65{3} ] = expand( T21_g[ bS60{1}, bS61{1}, bS62{1} ], {1, 2, 3} )
T23_g[ bS66{1}, iS67{i2}, iS68{i3} ]
   = T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   * T22_l[ bS63{1}, bS64{2}, bS65{3} ];
T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   = T23_g[ bS66{1}, iS67{i2}, iS68{i3} ]
   * T1_g[ bS3{1}, iS4{i7}, iS5{i8} ];
T25_g[ bS72{1}, iS73{i2}, iS74{i3} ]
   = T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   + T2_g[ bS6{1}, iS7{i9}, iS8{i10} ];
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ]
   = T25_g[ bS72{1}, iS73{i2}, iS74{i3} ];
}

} //Segmented_Fusion

```

Running the same code on a MSVC build, gives a different segmentation

```
Segmented_Fusion Dump: -- Re-written complete fusion:{
Inputs:
  T0_g[ bS0{1}, iS1{i2}, iS2{i3} ], float
  i4, int64_t
  i5, int64_t
  i6, int64_t
  T1_g[ bS3{1}, iS4{i7}, iS5{i8} ], float
  T2_g[ bS6{1}, iS7{i9}, iS8{i10} ], float
  d11, double
Outputs:
  T26_g[ bS75{1}, iS76{i2}, iS77{i3} ], float

%kernel_math {
T12_l[ bS33{1}, iS34{i2}, iS35{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T13_g[ rS36{1}, rS37{i2}, rS38{i3} ]
   = reduction( T12_l[ bS33{1}, iS34{i2}, iS35{i3} ], op = add, initial value = double(0), allreduce = 0 )
T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   = broadcast( T13_g[ rS36{1}, rS37{i2}, rS38{i3} ] )
T15_l[ bS42{1}, bS43{1}, bS44{1} ]
   = T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   / double(6);
T18_g[ bS51{1}, bS52{1}, bS53{1} ]
   = T15_l[ bS42{1}, bS43{1}, bS44{1} ];
T19_l[ bS54{1}, bS55{2}, bS56{3} ] = expand( T18_g[ bS51{1}, bS52{1}, bS53{1} ], {1, 2, 3} )
T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ]
   - T19_l[ bS54{1}, bS55{2}, bS56{3} ];
T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T4_g[ rS12{1}, rS13{i2}, rS14{i3} ]
   = reduction( T3_g[ bS9{1}, iS10{i2}, iS11{i3} ], op = add, initial value = double(0), allreduce = 0 )
T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   = broadcast( T4_g[ rS12{1}, rS13{i2}, rS14{i3} ] )
d18 = (double)(1);
d19 = double(1) * d18;
d20 = (double)(i2);
d21 = d19 * d20;
d22 = (double)(i3);
d23 = d21 * d22;
T6_g[ bS18{1}, bS19{1}, bS20{1} ]
   = T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   / d23;
T7_l[ bS21{1}, iS22{i2}, iS23{i3} ]
   = T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   - T6_g[ bS18{1}, bS19{1}, bS20{1} ];
T8_g[ bS24{1}, iS25{i2}, iS26{i3} ]
   = T7_l[ bS21{1}, iS22{i2}, iS23{i3} ]
   * T7_l[ bS21{1}, iS22{i2}, iS23{i3} ];
T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   = reduction( T8_g[ bS24{1}, iS25{i2}, iS26{i3} ], op = add, initial value = double(0), allreduce = 0 )
d34 = (double)(1);
d35 = double(1) * d34;
d36 = (double)(i2);
d37 = d35 * d36;
d38 = (double)(i3);
d39 = d37 * d38;
T10_l[ 0 ]
   = T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   / d39;
T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   = broadcast( T10_l[ 0 ] )
T16_g[ bS45{1}, bS46{1}, bS47{1} ]
   = T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   + double(0.5);
T17_l[ bS48{1}, bS49{1}, bS50{1} ]
   = rsqrtf(T16_g[ bS45{1}, bS46{1}, bS47{1} ]);
T21_g[ bS60{1}, bS61{1}, bS62{1} ]
   = T17_l[ bS48{1}, bS49{1}, bS50{1} ];
T22_g[ bS63{1}, bS64{2}, bS65{3} ] = expand( T21_g[ bS60{1}, bS61{1}, bS62{1} ], {1, 2, 3} )
T23_l[ bS66{1}, iS67{i2}, iS68{i3} ]
   = T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   * T22_g[ bS63{1}, bS64{2}, bS65{3} ];
T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   = T23_l[ bS66{1}, iS67{i2}, iS68{i3} ]
   * T1_g[ bS3{1}, iS4{i7}, iS5{i8} ];
T25_g[ bS72{1}, iS73{i2}, iS74{i3} ]
   = T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   + T2_g[ bS6{1}, iS7{i9}, iS8{i10} ];
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ]
   = T25_g[ bS72{1}, iS73{i2}, iS74{i3} ];
}

} // {Re-written complete fusion}
Segmented_Fusion Dump: -- fusion segments:
Segmented_Fusion{
groups:
g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

g{10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 30, 31}

g{21, 22, 23, 24, 27, 28, 29, 32, 33, 34, 35}

edges:
e{ g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
 -> g{10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 30, 31}
(T6_g[ bS18{1}, bS19{1}, bS20{1} ]) }

e{ g{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
 -> g{10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 30, 31}
(T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]) }

e{ g{10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 30, 31}
 -> g{21, 22, 23, 24, 27, 28, 29, 32, 33, 34, 35}
(T22_g[ bS63{1}, bS64{2}, bS65{3} ]) }


group details:
g{(reduction)
inputs:
T0_g[ bS0{1}, iS1{i2}, iS2{i3} ] float
i2 int64_t
i3 int64_t
outputs:
T3_g[ bS9{1}, iS10{i2}, iS11{i3} ] float
T6_g[ bS18{1}, bS19{1}, bS20{1} ] float


T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T4_g[ rS12{1}, rS13{i2}, rS14{i3} ]
   = reduction( T3_g[ bS9{1}, iS10{i2}, iS11{i3} ], op = add, initial value = double(0), allreduce = 0 )
T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   = broadcast( T4_g[ rS12{1}, rS13{i2}, rS14{i3} ] )
d22 = (double)(i3);
d20 = (double)(i2);
d18 = (double)(1);
d19 = double(1) * d18;
d21 = d19 * d20;
d23 = d21 * d22;
T6_g[ bS18{1}, bS19{1}, bS20{1} ]
   = T5_g[ bS15{1}, bS16{1}, bS17{1} ]
   / d23;
}

g{(reduction)
inputs:
i2 int64_t
T3_g[ bS9{1}, iS10{i2}, iS11{i3} ] float
i3 int64_t
T6_g[ bS18{1}, bS19{1}, bS20{1} ] float
outputs:
T22_g[ bS63{1}, bS64{2}, bS65{3} ] float


T7_l[ bS21{1}, iS22{i2}, iS23{i3} ]
   = T3_g[ bS9{1}, iS10{i2}, iS11{i3} ]
   - T6_g[ bS18{1}, bS19{1}, bS20{1} ];
T8_g[ bS24{1}, iS25{i2}, iS26{i3} ]
   = T7_l[ bS21{1}, iS22{i2}, iS23{i3} ]
   * T7_l[ bS21{1}, iS22{i2}, iS23{i3} ];
T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   = reduction( T8_g[ bS24{1}, iS25{i2}, iS26{i3} ], op = add, initial value = double(0), allreduce = 0 )
d38 = (double)(i3);
d36 = (double)(i2);
d34 = (double)(1);
d35 = double(1) * d34;
d37 = d35 * d36;
d39 = d37 * d38;
T10_l[ 0 ]
   = T9_g[ rS27{1}, rS28{i2}, rS29{i3} ]
   / d39;
T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   = broadcast( T10_l[ 0 ] )
T16_g[ bS45{1}, bS46{1}, bS47{1} ]
   = T11_g[ bS30{1}, bS31{1}, bS32{1} ]
   + double(0.5);
T17_l[ bS48{1}, bS49{1}, bS50{1} ]
   = rsqrtf(T16_g[ bS45{1}, bS46{1}, bS47{1} ]);
T21_g[ bS60{1}, bS61{1}, bS62{1} ]
   = T17_l[ bS48{1}, bS49{1}, bS50{1} ];
T22_g[ bS63{1}, bS64{2}, bS65{3} ] = expand( T21_g[ bS60{1}, bS61{1}, bS62{1} ], {1, 2, 3} )
}

g{(persistent)
inputs:
T0_g[ bS0{1}, iS1{i2}, iS2{i3} ] float
T1_g[ bS3{1}, iS4{i7}, iS5{i8} ] float
T2_g[ bS6{1}, iS7{i9}, iS8{i10} ] float
T22_g[ bS63{1}, bS64{2}, bS65{3} ] float
outputs:
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ] float


T12_l[ bS33{1}, iS34{i2}, iS35{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ];
T13_g[ rS36{1}, rS37{i2}, rS38{i3} ]
   = reduction( T12_l[ bS33{1}, iS34{i2}, iS35{i3} ], op = add, initial value = double(0), allreduce = 0 )
T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   = broadcast( T13_g[ rS36{1}, rS37{i2}, rS38{i3} ] )
T15_l[ bS42{1}, bS43{1}, bS44{1} ]
   = T14_g[ bS39{1}, bS40{1}, bS41{1} ]
   / double(6);
T18_g[ bS51{1}, bS52{1}, bS53{1} ]
   = T15_l[ bS42{1}, bS43{1}, bS44{1} ];
T19_l[ bS54{1}, bS55{2}, bS56{3} ] = expand( T18_g[ bS51{1}, bS52{1}, bS53{1} ], {1, 2, 3} )
T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   = T0_g[ bS0{1}, iS1{i2}, iS2{i3} ]
   - T19_l[ bS54{1}, bS55{2}, bS56{3} ];
T23_l[ bS66{1}, iS67{i2}, iS68{i3} ]
   = T20_g[ bS57{1}, iS58{i2}, iS59{i3} ]
   * T22_g[ bS63{1}, bS64{2}, bS65{3} ];
T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   = T23_l[ bS66{1}, iS67{i2}, iS68{i3} ]
   * T1_g[ bS3{1}, iS4{i7}, iS5{i8} ];
T25_g[ bS72{1}, iS73{i2}, iS74{i3} ]
   = T24_g[ bS69{1}, iS70{i2}, iS71{i3} ]
   + T2_g[ bS6{1}, iS7{i9}, iS8{i10} ];
T26_g[ bS75{1}, iS76{i2}, iS77{i3} ]
   = T25_g[ bS72{1}, iS73{i2}, iS74{i3} ];
}

} //Segmented_Fusion
```

### Versions

Upstream code bump push: https://github.com/pytorch/pytorch/pull/81861

commit: 0cd50c71d65d0d8d3d5fc3c7679ebe9da4d4288b

### PR DESCRIPTION
**Pull request by shmsong**
Fixes #1859 .

1. Fixed a few undeterministic iterations in segmenter pass, 
```
PYTORCH_NVFUSER_DUMP=segmenter_logging test_ops.py -k test_python_ref_executor__refs_nn_functional_layer_norm_executor_nvfuser_cuda_float32 -v
```
now outputs the same segmenter trace on Win and ubuntu builds. 

2. Also a bug fix in neighbor group function.

TODO: 

This PR is used to unblock and quite a bit of clean up possible in a follow up. Would consider further consolidate the introduced `DeterministicSet` and `VectorOfUniqueEntries`.

### CODE REVIEW

**Comment by jjsjann123** [comment]
> This PR is used to unblock and quite a bit of clean up possible in a follow up. Would consider further consolidate the introduced DeterministicSet and VectorOfUniqueEntries.

Note, we don't need to rush this PR in if you think it's not in a good state yet. The upstream push has been resolve via updating the input check, so the msvc segmentation is no longer failing.

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp [hunk 1]
```diff
@@ -16,6 +16,64 @@ namespace jit {
...
+// Deterministic set implementation using vector of unique entries
+//  Tries to support the basic API's that std::unordered_set has
+// and provides a deterministic iteration order.
+// TODO:
+//  1. Both this class and VectorOfUniqueEntries should go into
+// a new ADT file.
+//  2. Should use this class for a lot of set/vec pair implementation
+// logic.
+template <typename T>
+class DeterministicSet : public VectorOfUniqueEntries<T> {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp]: Do we need another class? Can we just add the new methods to `VectorOfUniqueEntries`?

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp [hunk 2]
```diff
@@ -75,7 +133,7 @@ std::vector<SegmentedGroup::NeighborGroup> SegmentedGroup::
     return {};
   }
 
-  std::vector<bool> can_merge(true, neighbors.size());
+  std::vector<bool> can_merge(neighbors.size(), true);
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:84]: 😨

Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:84]: Was a tricky one to find and it made quite far...

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp (hunk 1 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp]: I guess not. Just thought if we'd want to expand `VectorOfUniqueEntries` we'd benefit from a `set-like` interface and a `vector-like` interface, as it could be used as both a `vec` and a `set`. But trying to add std like interfaces of both `set` and `vec` in a single class could make it quite crowded. 

Not any concern for now. Just removed it. Thanks.

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:84]: That's why I almost always use `at()` rather than `[]`. This type of memory violations is really annoying to debug.

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for the fix!
