### PR TITLE
Fix expand

### LINKED ISSUE #1751: Broken expand op
### 🐛 Describe the bug

```
TEST_F(NVFuserTest, FusionExpandRepro_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto x = 3, y = 4, z = 5;

  // x  
  auto tv0 = makeSymbolicTensor(2);
  fusion->addInput(tv0);

  auto tv1 = broadcast(tv0, {true, false, false});

  auto tv2 = expand(
      tv1,  
      {IrBuilder::create<Int>(x),
       tv1->axis(0)->extent(),
       tv1->axis(1)->extent()});

  fusion->addOutput(tv2);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({y, z}, options);

  FusionExecutorCache executor_cache(std::move(fusion));

  auto cg_outputs = executor_cache.runFusionWithInputs({t0});
  auto cg_out = cg_outputs[1];

  TORCH_INTERNAL_ASSERT(cg_out.size(0) == x);
  TORCH_INTERNAL_ASSERT(cg_out.size(1) == y);
  TORCH_INTERNAL_ASSERT(cg_out.size(2) == z);

  auto t2 = t0.expand({x, y, z});

  testValidate(
      executor_cache.fusion(),
      cg_outputs,
      {t0}, 
      {t2}, 
      __LINE__,
      __FILE__);
}
```

This simple expand hits an assert
```
unknown file: Failure
C++ exception with description "expanded_extent->isA<Int>() INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/ir_nodes.cpp":747, please report a bug to PyTorch. Expanded extents must be of Int type.
Exception raised from ExpandOp at /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/ir_nodes.cpp:747 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f2083c27b2c in /opt/pytorch/pytorch/build/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7f2083bfefd8 in /opt/pytorch/pytorch/build/lib/libc10.so)
frame #2: c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, char const*) + 0x57 (0x7f2083c257d7 in /opt/pytorch/pytorch/build/lib/libc10.so)
frame #3: torch::jit::fuser::cuda::ExpandOp::ExpandOp(torch::jit::fuser::cuda::IrBuilderPasskey, torch::jit::fuser::cuda::TensorView*, torch::jit::fuser::cuda::TensorView*, std::vector<torch::jit::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >) + 0x1a6 (0x7f2086da4746 in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #4: torch::jit::fuser::cuda::OptOutMutator::mutate(torch::jit::fuser::cuda::ExpandOp*) + 0x375 (0x7f2086e56d55 in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31537db (0x7f2086db57db in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31bf582 (0x7f2086e21582 in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #7: torch::jit::fuser::cuda::GpuLower::lower(torch::jit::fuser::cuda::Fusion*, torch::jit::fuser::cuda::DataType) + 0x9cf (0x7f2086e4b78f in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #8: torch::jit::fuser::cuda::FusionExecutor::compileFusion(torch::jit::fuser::cuda::Fusion*, c10::ArrayRef<c10::IValue> const&, torch::jit::fuser::cuda::LaunchParams const&, torch::jit::fuser::cuda::CompileOptions) + 0xc48 (0x7f2086d19cf8 in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #9: torch::jit::fuser::cuda::FusionKernelRuntime::runKernelWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long, torch::jit::fuser::cuda::SegmentedGroup*) + 0x342 (0x7f2086dd0e12 in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #10: torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long) + 0x4ff (0x7f2086dd21df in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #11: torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) + 0x11e (0x7f2086dd500e in /opt/pytorch/pytorch/build/lib/libtorch_cuda.so)
frame #12: torch::jit::NVFuserTest_FusionExpandRepro_CUDA_Test::TestBody() + 0x46b (0x55e9bd0fb1bb in /opt/pytorch/pytorch/build/bin/test_jit)
frame #13: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x51 (0x55e9bd13a691 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #14: <unknown function> + 0x721d30 (0x55e9bd12dd30 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #15: <unknown function> + 0x7221c5 (0x55e9bd12e1c5 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #16: <unknown function> + 0x722921 (0x55e9bd12e921 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #17: testing::internal::UnitTestImpl::RunAllTests() + 0x10e9 (0x55e9bd1300a9 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #18: testing::UnitTest::Run() + 0x98 (0x55e9bd1305c8 in /opt/pytorch/pytorch/build/bin/test_jit)
frame #19: main + 0xcc (0x55e9bcc8de5c in /opt/pytorch/pytorch/build/bin/test_jit)
frame #20: __libc_start_main + 0xf3 (0x7f2083741083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #21: _start + 0x2e (0x55e9bccd799e in /opt/pytorch/pytorch/build/bin/test_jit)
```

gdb BT:
```
(gdb) bt
#0  0x00007fff9b34ecd0 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@plt ()
   from /opt/pytorch/pytorch/torch/lib/libc10.so
#1  0x00007fff9b3777d7 in c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, char const*) () from /opt/pytorch/pytorch/torch/lib/libc10.so
#2  0x00007fff9e54ed16 in torch::jit::fuser::cuda::ExpandOp::ExpandOp(torch::jit::fuser::cuda::IrBuilderPasskey, torch::jit::fuser::cuda::TensorView*, torch::jit::fuser::cuda::TensorView*, std::vector<torch::jit
::fuser::cuda::Val*, std::allocator<torch::jit::fuser::cuda::Val*> >) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#3  0x00007fff9e601325 in torch::jit::fuser::cuda::OptOutMutator::mutate(torch::jit::fuser::cuda::ExpandOp*) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#4  0x00007fff9e55fdab in torch::jit::fuser::cuda::ir_utils::replaceValue(torch::jit::fuser::cuda::Fusion*, std::unordered_map<torch::jit::fuser::cuda::Val*, torch::jit::fuser::cuda::Val*, std::hash<torch::jit::fuser::cuda::Val*>, std::equal_to<torch::jit::fuser::cuda::Val*>, std::allocator<std::pair<torch::jit::fuser::cuda::Val* const, torch::jit::fuser::cuda::Val*> > > const&) ()
   from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#5  0x00007fff9e5cbb52 in torch::jit::fuser::cuda::replaceSymbolicSizes(torch::jit::fuser::cuda::Fusion*) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#6  0x00007fff9e5f5d5f in torch::jit::fuser::cuda::GpuLower::lower(torch::jit::fuser::cuda::Fusion*, torch::jit::fuser::cuda::DataType) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#7  0x00007fff9e4c4258 in torch::jit::fuser::cuda::FusionExecutor::compileFusion(torch::jit::fuser::cuda::Fusion*, c10::ArrayRef<c10::IValue> const&, torch::jit::fuser::cuda::LaunchParams const&, torch::jit::fuser::cuda::CompileOptions) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#8  0x00007fff9e57b3e2 in torch::jit::fuser::cuda::FusionKernelRuntime::runKernelWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long, torch::jit::fuser::cuda::SegmentedGroup*) ()
   from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#9  0x00007fff9e57c7af in torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput(c10::ArrayRef<c10::IValue> const&, unsigned long) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#10 0x00007fff9e57f5de in torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#11 0x00007fff9e57fc87 in torch::jit::fuser::cuda::GraphCache::runGraphWithInputs(c10::ArrayRef<c10::IValue> const&) () from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
#12 0x00007fff9e5f8e6b in torch::jit::fuser::cuda::runCudaFusionGroup(torch::jit::Node const*, std::vector<c10::IValue, std::allocator<c10::IValue> >&)::{lambda()#3}::operator()() const [clone .isra.0] ()
   from /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so
```

### Versions

Repro's on ToT devel `8a69aa320bd7629e1709fe5ceb7104d2c88ec84c`

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #1751 

Also added a C++ test that concretizes a symbolic domain. The concrete size information is not used in the generated kernel, which should be addresses as a separate PR.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/arith.cpp [hunk 1]
```diff
@@ -993,18 +993,39 @@ TensorView* expand(TensorView* inp, const std::vector<Val*>& expanded_sizes) {
...
+      // the extent to the given expanded size.
+      // Note that expansion to 1 just means its extent becomes 1 and
+      // does not mean the ID becomes a broadcast.
       out_id_builder.extent(expanded_sizes[i]);
+    } else {
+      // Input id is non-broadcast and its extent is concrete. Nothing
+      // to expand, but the input and expanded sizes should match if
+      // the expanded size is also concrete.
+      auto inp_id_size_int = inp_id->extent()->getInt();
+      if (expanded_size_int.has_value()) {
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/arith.cpp:1021]: Nice~

**Review by jjsjann123 — APPROVED** [review]
LGTM
