### PR TITLE
Fix issues in reductions and thread predicates

### LINKED ISSUE #367: Issue with block reduction then grid reduction
When splitting a block reduction from grid reduction there's an error in the work buffer computation. It goes out of memory and in the below case it ends up screwing up the sync buffer so nothing is ever written.
Repro:
```.cpp
  Fusion fusion;
  FusionGuard fg(&fusion);

  // Symbolic integers we will use for runtime tiling
  Int* symbolic_m_tile_dim = new Int();
  Int* symbolic_split_k_tile_dim = new Int();
  Int* symbolic_block_k_tile_dim = new Int();
  // Compile-time integer for tiling
  int n_smem_tile = 32;

  // Symbolic 2D tensors TV0[M, K], TV1[K, N]
  TensorView* tv0 = makeDummyTensor(2);
  TensorView* tv1 = makeDummyTensor(2);

  // Broadcast tv0 to [M, K, *]
  TensorView* tv2 = broadcast(tv0, {false, false, true});
  // Broadcast tv1 to [*, K, N]
  TensorView* tv3 = broadcast(tv1, {true, false, false});

  // Pointwise multiplication resulting in tv3[M, K, N]
  TensorView* tv4 = mul(tv2, tv3);

  // Sum the K-dim
  TensorView* tv5 = sum(tv4, {1});

  // Register inputs and outputs
  fusion.addInput(tv0);
  fusion.addInput(tv1);
  fusion.addOutput(tv5);

  // Register runtime tile dims as inputs
  fusion.addInput(symbolic_m_tile_dim);
  fusion.addInput(symbolic_split_k_tile_dim);
  fusion.addInput(symbolic_block_k_tile_dim);

  // Make a 3D tile, mix of symbolic and constant, do in reverse order because
  // dims are inserted
  tv5->split(2, n_smem_tile);
  tv5->split(1, symbolic_block_k_tile_dim);
  tv5->split(1, symbolic_split_k_tile_dim);
  tv5->split(0, symbolic_m_tile_dim);

  // tv5[M/m_tile, m_tile, r{K/split_k/block_k}, r{split_k}, r{block_k}, N/32,
  // 32]
  tv5->reorder({{1, 5}, {5, 1}});
  // tv5[M/m_tile, N/32, r{K/split_k/block_k}, r{split_k}, r{block_k},  m_tile,
  // 32]

  auto tv6 = tv5->rFactor({2});
  auto tv7 = tv5->rFactor({2});

  // Scope computations
  tv6->computeAt(tv5, 2);

  tv6->reorder({
      {2, -2},
      {3, -1},
      {4, 2},
      {5, 3},
      {6, 4},
  });

  tv0->computeAt(tv6, 3);
  tv1->computeAt(tv6, 3);
  tv4->computeAt(tv6, -1);

  // Cache smem tiles
  tv2->setMemoryType(MemoryType::Shared);
  tv3->setMemoryType(MemoryType::Shared);
  tv4->setMemoryType(MemoryType::Local);
  tv6->setMemoryType(MemoryType::Local);
  tv7->setMemoryType(MemoryType::Local);

  tv5->axis(0)->parallelize(ParallelType::BIDz);
  tv5->axis(1)->parallelize(ParallelType::BIDy);

  std::vector<TensorView*> tv_list = {tv2, tv3, tv4, tv5, tv6, tv7};
  for (auto tv : tv_list) {
    tv->axis(-2)->parallelize(ParallelType::TIDz);
    tv->axis(-1)->parallelize(ParallelType::TIDy);
  }
  tv2->axis(3)->parallelize(ParallelType::TIDx);
  tv3->axis(3)->parallelize(ParallelType::TIDx);
  tv4->axis(3)->parallelize(ParallelType::TIDx);
  tv6->axis(3)->parallelize(ParallelType::TIDx);
  tv7->axis(2)->parallelize(ParallelType::TIDx);

  tv2->axis(4)->parallelize(ParallelType::BIDx);
  tv3->axis(4)->parallelize(ParallelType::BIDx);
  tv4->axis(4)->parallelize(ParallelType::BIDx);
  tv6->axis(4)->parallelize(ParallelType::BIDx);
  tv7->axis(3)->parallelize(ParallelType::BIDx);
  tv5->axis(2)->parallelize(ParallelType::BIDx);

  fusion.printMath();
  fusion.printKernel();

  constexpr int M = 3, K = 6, N = 16;

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({M, K}, options);
  at::Tensor t1 = at::randn({K, N}, options);

  torch::jit::fuser::cuda::FusionExecutor fe;
  fe.compileFusion(&fusion);
  auto outputs = fe.runFusion(
      {t0, t1, 2, 2, 3},
      torch::jit::fuser::cuda::LaunchParams(-1, -1, -1, -1, -1, -1));

  at::Tensor aten_output = mul(t0.unsqueeze(2), t1.unsqueeze(0)).sum(1);
  std::cout << aten_output << "\n" << outputs[0] << std::endl;
  TORCH_CHECK(
      aten_output.allclose(outputs[0], 1e-5, 1e-5),
      "Error of: ",
      aten_output.sub(outputs[0]).abs().max());
```
Removing the TV7 rfactor and parallelizing for block and grid reduce on TV5 seems to work (with other modifications from today's ToT).

### LINKED ISSUE #468: ReductionOp ignores thread predicates
## 🐛 Bug

Thread predicates are not used in `ReductionOp`, both for block and grid reductions. This fusion, e.g., fails at the validation:

```
  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  auto tv1 = sum(tv0, {1});
  auto tv2 = sum(tv1, {0});
  fusion.addOutput(tv2);

  tv1->axis(0)->parallelize(ParallelType::TIDy);
  tv1->axis(1)->parallelize(ParallelType::TIDx);

  tv2->axis(0)->parallelize(ParallelType::TIDy);
```

The generated kernel:
```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 0> T2) {
  alignas(4) extern __shared__ char array[];
  void* shared_mem = array;
  T2[0] = float(0);
  float T1[1];
  T1[0] = float(0);
  blockReduce<true, false, false>(
    T1[0],
    T0[(threadIdx.y * T0.stride[0]) + (threadIdx.x * T0.stride[1])],
    [](float &a, float b) { a = a + b; },
    threadIdx,
    blockDim,
    static_cast<float*>(shared_mem),
    1,
    float(0));
  blockReduce<false, true, false>(
    T2[0],
    T1[0],
    [](float &a, float b) { a = a + b; },
    threadIdx,
    blockDim,
    static_cast<float*>(shared_mem),
    1,
    float(0));
}
```
After the first `blockReduce`, threads with `threadIdx.x > 0` don't have a valid value, so their values should not be used in the second `blockReduce`.

This is likely related to #367.

### PR DESCRIPTION
**Pull request by naoyam**
Thread predicates are ignored when calling `blockReduce` and `gridReduce`. See #468 for a reproducer of the problem when it is ignored for `blockReduce`. See #367 for a reproducer of `gridReduce`. This PR also adds the reproducers as new tests.

For `gridReduce`, the best way to apply thread predicates is, IMO, to set the `TIDx/y/z` template parameters as false. An assumption I have is that the thread predicate of a GridReduction must not include `BIDx/y/z` since we don't allow multiple calls to `gridReduce` in a single kernel.

 To pass around the predicate info until the CUDA code for calling `gridReduce` is generated, a new field of type `ParallelTypeBitmap` is added to `kir::GridReduction`. To use `ParalleTypeBitmap` from kernel_ir.h, I also extracted the class from lower_utils.h into its own header file.

For `blockReduce`, the change is much more trivial (`IndexLowering::visit(kir::ReductionOp*)`. 

Fixes #367 
Fixes #468

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
This looks good to me. Do we assert somewhere if someone attempts to use 2 grid reductions in the same kernel? We actually may want to do this at some point and just want to make sure until then we throw a hard error.

Can you also please update the issues with the code that is now generated?
Thanks!

**Comment by naoyam** [comment]
Added an issue of detecting multiple grid reductions (#475).

**Comment by naoyam** [comment]
Updated issue #367 with the generated kernel.

**Comment by naoyam** [comment]
Updated issue #468 with the generated kernel.

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -8635,6 +8635,161 @@ TEST(NVFuserTest, FusionCacheBeforeReduction2_CUDA) {
...
+  auto tv1 = sum(tv0, {1});
+  auto tv2 = sum(tv1, {0});
+  fusion.addOutput(tv2);
+
+  tv1->axis(0)->parallelize(ParallelType::TIDy);
+  tv1->axis(1)->parallelize(ParallelType::TIDx);
+
+  tv2->axis(0)->parallelize(ParallelType::TIDy);
+
+  fusion.printMath();
```
Comment (tlemo) [inline test/cpp/jit/test_gpu.cpp]: I suspect this is to be removed, right?

File: torch/csrc/jit/codegen/cuda/codegen.cpp [hunk 2]
```diff
@@ -461,6 +461,47 @@ class CudaKernelGenerator : private kir::IrVisitor {
     }
   }
 
+  std::string generateGridReduceTemplateFlags(
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/codegen.cpp:464]: Please place this local helper in a anonymous namespace

File: torch/csrc/jit/codegen/cuda/codegen.cpp [hunk 3]
```diff
@@ -461,6 +461,47 @@ class CudaKernelGenerator : private kir::IrVisitor {
...
+      const ParallelTypeBitmap& thread_pred) {
+    const auto par_domains = rop->getParallelReductionDomains();
+    const std::array<ParallelType, 6> ptypes{ParallelType::BIDx,
+                                             ParallelType::BIDy,
+                                             ParallelType::BIDz,
+                                             ParallelType::TIDx,
+                                             ParallelType::TIDy,
+                                             ParallelType::TIDz};
+    std::stringstream flags;
+    std::transform(
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/codegen.cpp]: I think a plain loop would look more readable than the std::transform() in this case

File: torch/csrc/jit/codegen/cuda/kernel_ir.h [hunk 4]
```diff
@@ -1082,7 +1083,8 @@ class TORCH_CUDA_API GridReduction final : public Expr {
       Passkey passkey,
       ReductionOp* reduction_op,
       Allocate* reduction_buffer,
-      Allocate* sync_buffer);
+      Allocate* sync_buffer,
+      const ParallelTypeBitmap& thread_pred);
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/kernel_ir.h]: I'd like to avoid large parameter list. How about a `GridReduction::setThreadPred()` method instead?

File: torch/csrc/jit/codegen/cuda/kernel_ir.h [hunk 5]
```diff
@@ -1096,13 +1098,18 @@ class TORCH_CUDA_API GridReduction final : public Expr {
     return sync_buffer_;
   }
 
+  const ParallelTypeBitmap& thread_pred() const {
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/kernel_ir.h]: If we use `setThreadPred()` we should probably name this `threadPred()` for consistency

File: torch/csrc/jit/codegen/cuda/lower_index.h [hunk 6]
```diff
@@ -16,15 +16,16 @@ namespace cuda {
...
     FUSER_PERF_SCOPE("IndexLowering::getIndexedExprs");
-    IndexLowering il;
+    IndexLowering il(thread_predicates);
     il.generate(incoming_exprs);
     return il.lowered_exprs_;
   }
 
  private:
-  IndexLowering();
+  IndexLowering(const ThreadPredicateMap& thread_predicates);
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/lower_index.h]: `explicit`

File: torch/csrc/jit/codegen/cuda/kernel_ir.h [hunk 7]
```diff
@@ -1096,13 +1098,18 @@ class TORCH_CUDA_API GridReduction final : public Expr {
...
+  }
+
   static std::string getPredicateFlagName(const TensorView* val);
   static std::string getPredicateFlagName(const fuser::cuda::TensorView* val);
 
  private:
   ReductionOp* reduction_op_ = nullptr;
   Allocate* reduction_buffer_ = nullptr;
   Allocate* sync_buffer_ = nullptr;
+  ParallelTypeBitmap thread_pred_;
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/kernel_ir.h]: Why can't we use the "normal" predicate (Expr::predicate_) instead of this?

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp [hunk 8]
```diff
@@ -263,7 +263,6 @@ void ThreadPredicateMap::print() const {
   std::cout << "--------------------------------\n";
   for (const auto& kv : thread_predicates_) {
     std::cout << "T" << kv.first->name() << " {";
-    // ir_utils::ParallelTypeBitmap
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:266]: This comment was indicating which part is printed (since it's a complex data structure). Can you leave it in place, with the `ir_utils::` prefix removed?

**Review by tlemo — APPROVED** [review]

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: Yes, forgot to remove. Thanks.

File: torch/csrc/jit/codegen/cuda/codegen.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/codegen.cpp:464]: It's already in a class defined in an anonymous namespace.

File: torch/csrc/jit/codegen/cuda/codegen.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/codegen.cpp]: Agreed. Changed.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h (hunk 4 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/kernel_ir.h]: Sounds good. Updated.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/kernel_ir.h]: Changed it to `threadPredicate` and added `setThreadPredicate`. There is `setPredicate`, so I used `setThreadPredicate` instead of `setThreadPred`. Perhaps, we should rename `setPredicate` so that the difference with thread predicates can be clear.

File: torch/csrc/jit/codegen/cuda/lower_index.h (hunk 6 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_index.h]: Thanks. Added.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h (hunk 7 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/kernel_ir.h]: We could. We would need to make some changes to `gridReduce`. In particular, indexing the work buffer written by each thread block needs some non-significant change. 

However, `gridReduce` does have template bool parameters exactly for predicating based on block and thread indices being zero, so using those template flags should make more sense. The normal predicate is not for thread/block indices, so it can't be mapped to the template flags, and that's why we need to separate them for `gridReduce`. Note that for other expressions, we just combine them by `&&`.

File: torch/csrc/jit/codegen/cuda/codegen.cpp (hunk 2 above)
Comment (tlemo) [reply torch/csrc/jit/codegen/cuda/codegen.cpp:464]: Ah, right. One reason I don't like anonymous namespaces, you have to scroll around a lot to find them :(

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp (hunk 8 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:266]: Sorry, reverted.

File: torch/csrc/jit/codegen/cuda/codegen.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/codegen.cpp:464]: Yeah, that's a downside.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h (hunk 7 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/kernel_ir.h]: Added a comment to the code itself too.
