### PR TITLE
Fix vec validation on expanded broadcasting

### LINKED ISSUE #1843: TIMM Stride Vectorization Error
### 🐛 Describe the bug

Fusion fails with fallback path with channels_last + amp + batch_size > 1

Steps to reproduce:
`PYTORCH_NVFUSER_DISABLE_FALLBACK=1 python benchmark.py --bench train --model rexnet_100 --img-size 224 -b 2 --amp --torchscript --channels-last --no-retry`

Failing networks:
- rexnet_100
- rexnet_130
- rexnet_150
- rexnet_200

General Error:

> RuntimeError: `stride == cur_contig_stride || size == 1 || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0)` 
> INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor_utils.cpp":591, please report a bug to PyTorch. 
> `Vectorization of T2_g[ iS128{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * ( T0.size[1] * ( T0.size[2] * T0.size[3] ) ) ), 4) ), 1) ), 128) )}, iS127{1}, iS125{4}, iS129{128} ] with word size **XXX** not possible due to invalid stride. Domain: iS125{4}, stride: **XXX**`

### Versions

1. nvfuser devel branch

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/csarofeen/pytorch/issues/1843. Thanks, @jjsjann123 for the test and discussion.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp [hunk 1]
```diff
@@ -6507,6 +6507,39 @@ TEST_F(NVFuserTest, FusionSimpleAmperePipeline_CUDA) {
   testValidate(&fusion, cg_outputs, {input1}, {input1}, __LINE__, __FILE__);
 }
 
+TEST_F(NVFuserTest, FusionVectorizeRepro_CUDA) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: Please add this:

```
// Repro of issue #1843
```

File: torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp [hunk 2]
```diff
@@ -6507,6 +6507,39 @@ TEST_F(NVFuserTest, FusionSimpleAmperePipeline_CUDA) {
...
+  fusion->addInput(tv1);
+  fusion->addInput(tv0);
+
+  auto tv7 = sum(tv0, {1}, true);
+  auto tv_exp =
+      expand(tv7, {tv0->axis(0)->extent(), IrBuilder::create<Int>(32128)});
+  auto tv3 = exp(tv1);
+  auto tv8 = mul(tv3, tv_exp);
+  auto tv13 = sub(tv0, tv8);
+  fusion->addOutput(tv13);
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: Does this actually reproduce the issue? It seems this PR addresses an issue with validation vectorization of input and output tensors with an expanded broadcast IterDomain. This test has an expanded broadcast, but that isn't in any of input or output tensors. Am I missing anything?

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: Haha, the test is tricky, there's a fusion segmentation happening right at the expand op.

I tried to get a repro without that segmentation, somehow that doesn't trigger the issue cold_sweat

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 3]
```diff
@@ -617,11 +617,23 @@ void validateAlignedVectorizedFusionInputOutput(
   for (auto i = aten_tensor.ndimension() - 1; i >= 0; --i) {
     const auto stride = aten_tensor.strides().at(i);
     const auto size = aten_tensor.sizes().at(i);
+    auto root_id = tv->getMaybeRFactorDomain()[i];
+    const auto is_expanded_broadcasting =
+        root_id->isBroadcast() && root_id->hasExpandedExtent();
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:602]: Do we need to check for expanded broadcast here? I was under the impression that even a normal broadcast with an arbitrary stride should also pass the test, since we never index into broadcast dimension and it shouldn't break vectorization.

File: torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: Hmm. Can you please add that as a comment to the test? It'd be great if we could understand why it wouldn't fail without segmentation.

**Review by csarofeen — COMMENTED** [review]
Fix looks good, but test needs repro in title, and we might want to make one that doesn't rely on how segmentation is applied to the fusion.

For the repro we should probably just mark `tv7_exp` as an input.

**Comment by jjsjann123** [comment]
> For the repro we should probably just mark `tv7_exp` as an input.

Maybe I did something stupid when I was trying to repro it, but having `tv7_exp` as an input, even with the fastest dim implicitly broadcasted with correct shape and 0-stride seems to make it pick up only the pointwise scheduler and doesn't repro the problem.

Hopefully Xiang can easily get a repro with a simplified definition. :crossed_fingers:

File: torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp (hunk 1 above)
Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/test/test_gpu3.cpp]: added

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 3 above)
Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:602]: Non-expanded broadcasting is covered by the `size == 1` check below. I keep "expanded broadcast" a separate case because I want to check that, if it is an expanded broadcast, then it needs to have stride 0. But for regular broadcast, there is no such limitation.

**Comment by jjsjann123** [comment]
Noticed that this one hasn't been merged yet. Would be nice to get it. :bow: 
cc'ing @kevinstephano We'd probably want to cherry-pick this one as well.

**Review by csarofeen — APPROVED** [review]
Test references the issue at hand mentioning segmentation requirement for reproduction. Merging as is.

**Comment by csarofeen** [comment]
@zasdfgbnm to rebase when you have a chance.
