### PR TITLE
Verify vectorization eligibility for intermediate tensors

### LINKED ISSUE #1391: Vector load from SMEM
Vector load from SMEM seems to have a problem.

```
TEST_F(NVFuserTest, FusionSmemVectorize_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeContigTensor(1);
  fusion.addInput(tv0);

  auto tv1 = set(tv0);
  auto tv2 = set(tv1);
  auto tv3 = set(tv2);
  fusion.addOutput(tv3);

  tv1->setMemoryType(MemoryType::Shared);

  tv3->split(-1, 4);
  TransformPropagator::from(tv3);

  tv1->computeAt(tv3, -2);

  tv2->axis(-1)->parallelize(ParallelType::Vectorize);

  FusionExecutor fe;
  fe.compileFusion(&fusion);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);
  // Fail when the size is not divisible by the vector length
  auto t0 = at::randn({199}, options);
  auto cg_outputs = fe.runFusion({t0});

  auto ref = t0;

  testValidate(&fusion, cg_outputs, {t0}, {ref}, __LINE__, __FILE__);
}
```

The generated kernel:
```
__global__ void kernel1(Tensor<float, 1> T0, Tensor<float, 1> T3) {
  NVFUSER_DEFINE_MAGIC_ZERO
  __shared__ float T1[4];
  #pragma unroll 1
  for(nvfuser_index_t ki49 = 0; ki49 < (ceilDiv(T0.size[0], 4)); ++ki49) {
    #pragma unroll
    for(nvfuser_index_t ki59 = 0; ki59 < 4; ++ki59) {
      if ((((ki49 * 4) + (ki59 + nvfuser_zero)) < T0.size[0])) {
        T1[ki59]
           = T0[(((ki49 * 4) + (ki59 + nvfuser_zero)) * 1)];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    __barrier_sync(0);
    float T2[4];
    if ((((ki49 * 4) + 3) < T0.size[0])) {
      *reinterpret_cast<Array<float, 4>*>(&T2[0]) = *reinterpret_cast<Array<float, 4>*>(&T1[0]);
    }
    #pragma unroll
    for(nvfuser_index_t ki51 = 0; ki51 < 4; ++ki51) {
      if ((((ki49 * 4) + (ki51 + nvfuser_zero)) < T0.size[0])) {
        T3[(((ki49 * 4) + (ki51 + nvfuser_zero)) * 1)]
           = T2[ki51];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    __barrier_sync(0);
  }
}
```

Test output:
```
C++ exception with description "aten_output_tensor.allclose( fusion_output_tensor.to(aten_output_tensor.dtype()), tolerance_values.second, tolerance_values.first)INTERNAL ASSERT FAILED at "../test/cpp/jit/test_gpu_validator.h":420, please report a bug to PyTorch.

Validation error in output 0 on line 19724 in file ../test/cpp/jit/test_gpu.cpp.
  Detected abs error of: 1.54733
    absolute tolerance was set to 1.51992e-06
    and relative tolerance set to 2.23704e-06
```

The vectorized load from `T1` to `T2` works fine when `T0.size[0]` is divisible by 4, but otherwise, the load is not done for the last remaining elements.

This problem doesn't seem like a new problem, but I don't exactly remember it's supposed to have been fixed or it's still a known problem.

### PR DESCRIPTION
**Pull request by naoyam**
This PR adds validation of intermediate vectorized tensors with `ParallelType::Vectorize`. 

For tensors vectorized with `MisalignedVectorize`, it would throw an exception when an input nor output tensor is used, which isn't necessarily required, so should be possible to relax, but for now that's an assumption in place.

A next step is to eliminate predicates when safe as we do for register-based tensors.

Fixes #1391

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 1]
```diff
@@ -446,10 +481,14 @@ std::unique_ptr<caching::VectorizedTensorInfo> getVectorizedTensorValidationInfo
         vector_word_size.has_value(),
         "Non constant vector dimension found in ",
         out_tv);
-    tv_to_vector_word_size[out_tv] = vector_word_size.value();
-    tv_to_vector_word_size[in_tv] = vector_word_size.value();
+
+    auto tv_to_verify = out_tv->isFusionOutput() ? out_tv : in_tv;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:489]: Why only checking the output of the fusion otherwise the input? Do we not need to check both?

**Review by csarofeen — COMMENTED** [review]
Looks fine to me, just one thing I don't understand here.

**Comment by csarofeen** [comment]
Just some notes:
Vectorized TV and word size doesn't change and is compile time constant, we should probably move this information to kernel summary so we don't refetch it later. We also need to use this during code generation where we're reassembling it. There's quite a bit of opportunity for cleanup here.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:489]: Ah, I should have added a comment here. The expression is just a Set op, so the extents of the input and output must be equal, so just checking either of them should be sufficient. 

The reason to check the output when it's a fusion output is just because the size information of fusion outputs (and inputs) are readily available without relying on the expression evaluator, so it's just for efficiency.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:489]: Added a comment

**Review by csarofeen — APPROVED** [review]

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 2]
```diff
@@ -370,7 +372,40 @@ bool canVectorize(const IValue& aten_val, int word_size) {
...
+    }
+    last_root_dim = r_id;
+    break;
+  }
+
+  if (last_root_dim == nullptr) {
+    return false;
+  }
+
+  auto last_dim_size = expr_eval.evaluate(last_root_dim->extent());
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:397]: This path should be precomputed so expr eval should be just one look up. Note to myself to double check for intermediate tensors.

**Review by shmsong — APPROVED** [review]
LGTM. Thanks for fixing this. 👍
