### PR TITLE
Fix self mapping

### LINKED ISSUE #2068: codegen error: Unsupported domain mapping detected
### 🐛 Describe the bug

python repro
```
import torch
from torch._C._nvfuser import FusionDefinition, Fusion, DataType

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1], contiguous=[True, True, True], dtype=DataType.Float)
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T2 = fd.define_tensor(symbolic_sizes=[-1, -1, -1], contiguous=[True, True, True], dtype=DataType.Float)
    T3 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T4 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, -1], contiguous=[True, True, True, True], dtype=DataType.Float)
    T5 = fd.ops.broadcast_in_dim(T0, output_shape=[32, 56, 56, 1], broadcast_dims=[0, 1, 2])
    T6 = fd.ops.broadcast_in_dim(T1, output_shape=[32, 56, 56, 128], broadcast_dims=[3])
    T7 = fd.ops.broadcast_in_dim(T2, output_shape=[32, 56, 56, 1], broadcast_dims=[0, 1, 2])
    T8 = fd.ops.broadcast_in_dim(T3, output_shape=[32, 56, 56, 128], broadcast_dims=[3])
    T9 = fd.ops.broadcast_in_dim(T5, output_shape=[32, 56, 56, 128], broadcast_dims=[0, 1, 2, 3])
    S10 = fd.define_constant(1.00000e-06)
    T11 = fd.ops.add(T7, S10)
    T12 = fd.ops.sub(T4, T9)
    T13 = fd.ops.rsqrt(T11)
    T14 = fd.ops.broadcast_in_dim(T13, output_shape=[32, 56, 56, 128], broadcast_dims=[0, 1, 2, 3])
    T15 = fd.ops.mul(T12, T14)
    T16 = fd.ops.mul(T15, T6)
    T17 = fd.ops.add(T16, T8)
    T18 = fd.ops.cast(T17, dtype=DataType.Float)
    fd.add_output(T5)
    fd.add_output(T13)
    fd.add_output(T18)

inputs = [
    torch.randn(32, 56, 56, device='cuda'),
    torch.randn(128, device='cuda'),
    torch.randn(32, 56, 56, device='cuda'),
    torch.randn(128, device='cuda'),
    torch.randn(32, 56, 56, 128, device='cuda'),
]

fs = Fusion()
with FusionDefinition(fs) as fd:
    nvfuser_fusion_id1(fd)

for _ in range(5) :
    fs.execute(inputs)
```

Error message:
```
RuntimeError: !hasSelfMapping() INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/compute_at_map.cpp":38, please report a bug to PyTorch. Unsupported domain mapping detected in T5_l[ iS267{( ceilDiv(( ceilDiv(( i2 * 1 ), 4) ), blockDim.x) )}, iS270{( ceilDiv(( i0 * i1 ), 1) )}, iS271{1}, iS266{4}, iS268{blockDim.x} ]. Root domains, iS14{i2} and bS15{1}, are mapped with each other.
```

### Versions

`torchbenchPerf`

### PR DESCRIPTION
**Pull request by csarofeen**
Fixes #2068
Permissive for self mapping was too strict.

https://github.com/csarofeen/pytorch/pull/1941 was just a bit too strict.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/compute_at_map.cpp [hunk 1]
```diff
@@ -249,8 +262,8 @@ findFirstSelfMapping(Fusion* fusion, const IterDomainGraph& id_graph) {
     }
 
     // Leaf domains
-    auto self_mappped_leaf_pair =
-        detectMappablePair(tv->domain()->domain(), id_graph);
+    auto self_mappped_leaf_pair = detectMappablePair(
+        tv->domain()->domain(), id_graph, IdMappingMode::LOOP);
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: I see that why the PERMISSIVE mapping is too strict for root domains.

For leaf domains, I also see that CA domains should not be even permissively mapped. But LOOP doesn't map anything for domains right of CA points. I can't think of anything that could actually trigger self mapping in those domains, though, as at this point we already have verified there's no self mapping in root domains, so I *think* checking with LOOP is sufficient.

Let me know if I misunderstood anything.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: So you think we should just check leaf nodes here, nothing else? I thought the self mapping logic got moved primarily to compute at map, so I thought we need a check on root/rfactor too.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: No, we should check root domains. I was wondering why we use LOOP for leaves instead of EXACT. For CA leaf domains, even permissive mappings shouldn't be allowed, which LOOP verifies. For non-CA leaf domains (right of CA point), LOOP won't catch anything as it doesn't map any non-CA domains, effectively meaning we don't do any check of non-CA leaf domains. I think that's fine as long as roots are checked.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: To be clear, the PR makes sense to me. I just want to confirm I understand it correctly.

Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: > I was wondering why we use LOOP for leaves instead of EXACT.

I think it makes sense to use LOOP instead of EXACT. As long as different for loops in the same loop nest are not mapped, we should be fine with it. For example, for the following fusion

```
T0[I1, I2] = input
T1 = transpose(T0, 0, 1) 
T2 = T1 + T0
output = T2
```

I think the exact map has self-mapping, but as long as we are not inlining, that will not be a problem: We can generate code
```
float T1[I1, I2];
for i2 in I2:
  for i1 in I1:
    T1[i2, i1] = T0[i1, i2]
for i2 in I2:
  for i1 in I1:
    T1[i2, i1] = T1[i2, i1] + T0[i1, i2]
```
And this code is totally valid

(probably we should add the above example as a unit test?)

Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: If what I said above is the case, should we move the check for self-mapping from CA map to the loop nest generator?

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: Yeah, this is more about historical technical debt that it has been generally assumed that there's no mapping between domains in a tensor domain. Although I don't know if the assumption is still there, just lifting it without making sure there's no code based on that assumption seems risky.

Comment (zasdfgbnm) [reply torch/csrc/jit/codegen/cuda/compute_at_map.cpp:266]: Just checked the following test with this branch

```C++
TEST_F(NVFuserTest, FusionSelfMappingExactMap_CUDA) {
  // Check that even if there is self mapping in the exact compute at map, as
  // long as there is no self mapping in the loop map, we will be fine.
  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  auto tv0 = makeConcreteTensor({5, 5});
  fusion.addInput(tv0);

  auto tv1 = transpose(tv0, 0, 1);
  auto tv2 = add(tv0, tv1);

  fusion.addOutput(tv2);

  // no inlining

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn({5, 5}, options);

  FusionExecutor fe;
  fe.compileFusion(&fusion, {t0});
  auto cg_outputs = fe.runFusion({t0});

  auto ref = t0.t() + t0;

  testValidate(&fusion, cg_outputs, {t0}, {ref}, __LINE__, __FILE__);
}
```
I hit a `TORCH_INTERNAL_ASSERT` in indexing. After removing all failing `TORCH_INTERNAL_ASSERT`s, I start to get segfault. So yes, we do have lot of technical debts that prevent us from supporting this case.

**Comment by csarofeen** [comment]
@naoyam @zasdfgbnm what do we want to do with this?
@naoyam your understanding matches my own.

**Comment by zasdfgbnm** [comment]
I am OK with merging this PR as is. In the future, we might want to lift the constraint on root and rfactor domain to support cases like https://github.com/csarofeen/pytorch/pull/2070#discussion_r997545221, but for today, this PR is totally fine. I will leave the "LGTM" stamp to @naoyam though.

**Review by naoyam — APPROVED** [review]
LGTM
