### PR TITLE
Use ParallelMap in expr sorting

### LINKED ISSUE #1430: Expr sort issue
### 🐛 Describe the bug

Repro:
```.cpp

TEST_F(NVFuserTest, FusionTestWelfordPersistent_CUDA) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);



  int V = 32, W = 16, X = 80, Y = 384, Z = 8;

  // setup fusion
  auto tv0 = TensorViewBuilder()
      .ndims(5)
      .dtype(DataType::Half)
      .contiguity(std::vector<bool>(5, true))
      .shape({V, W, X, Y, Z})
      .build();

  fusion.addInput(tv0);
  auto tv1 = set(tv0);
  auto tv2 = castOp(DataType::Float, tv1);

  auto tvs = Welford(tv2, {1, 2, 3, 4});
  auto tv3 = tvs.avg;
  auto tv4 = tvs.var_sum;
  auto tv5 = tvs.n;
  
  // avg
  auto tv6 = broadcast(tvs.avg, {false, true, true, true, true});

  // var
  auto tv7 = mul(tv4, IrBuilder::create<Double>(1./(W*X*Y*Z)));
  auto tv8 = add(tv7, IrBuilder::create<Double>(1.e-6));
  auto tv9 = broadcast(tv8, {false, true, true, true, true});
  auto tv10 = rsqrt(tv9);
  
  auto tv11 = castOp(DataType::Float, tv1);
  auto tv12 = sub(tv11, tv6);
  auto tv13 = mul(tv12, tv10);
  
  auto tv14 = set(tv13);
  fusion.addOutput(tv14);

  tv3->axis(0)->parallelize(ParallelType::BIDy);
  tv3->axis(2)->parallelize(ParallelType::BIDx);
  tv3->axis(3)->parallelize(ParallelType::TIDx);
  tv3->axis(4)->parallelize(ParallelType::Vectorize);

  // tv3->reorder({{1, -2}});

  auto rfactor = ir_utils::rfactorHelper(tv3, {1, 4});

  scheduler_utils::parallelizeAllLike(rfactor, ir_utils::allTvs(&fusion));

  
  for(auto tv : ir_utils::allTvs(&fusion)){
    if(tv != tv1 || tv != tv3){
      for(auto i : c10::irange(tv->nDims())){
        if(isParallelTypeVectorize(tv->axis(i)->getParallelType())){
          tv->axis(i)->parallelize(ParallelType::Serial);
        }
      }
    }
  }

  tv0->computeAt(tv14, 1);
  tv13->computeAt(tv14, -2);
  tv2->computeAt(tv14, -1, ComputeAtMode::MostInlined);
  tv11->computeAt(tv14, -1, ComputeAtMode::MostInlined);

  auto options = at::TensorOptions().dtype(at::kHalf).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({V, W, X, Y, Z}, options);
  
    fusion.printMath();
  fusion.printKernel();
  // FusionExecutor fe;
  // fe.compileFusion(&fusion);
  // auto cg_outputs = fe.runFusion({t0}, LaunchParams(X, V, -1, Y, -1, -1));

  // // by default Welford outputs sum of square diff so need to divide to get var
  
  // auto t0_double = t0.to(at::kDouble);

  // auto at_mu = at::mean(t0_double, {1, 2, 3, 4}).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1);
  // auto at_var = at::var(t0_double, {1, 2, 3, 4}, false).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1);

  // auto at_out = t0_double.sub(at_mu).div(at_var.add(1.e-6).sqrt());

  // testValidate(&fusion, cg_outputs, {t0}, {at_out}, __LINE__, __FILE__, "", LaunchParams(X, V, -1, Y, -1, -1));
}
```

This case is causing a hang in expr sorting, because we fall into an infinite loop. This seems to be caused because the dim of size 16 moves across the fusion. Expr sorting is using loop map to get a global ordering of iteration domains, and because of this it thinks 16 should be in multiple positions so it fails to finish ID sorting. I believe we should be using Parallel Map in sorting instead of Loop Map since Parallel Map does not map to the right of the compute at position, so it would see there's "multiple" instances of the size-16 dimension.

### Versions

TOT Devel

### PR DESCRIPTION
**Pull request by csarofeen**
Fixes #1430

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/lower_expr_sort.cpp [hunk 1]
```diff
@@ -1145,7 +1180,7 @@ bool ExprSegmentationSorter::supportedMerge(ExprGroup* sg1, ExprGroup* sg2) {
     return false;
   }
 
-  const auto& loop_map = GpuLower::current()->caLoopMap();
+  const auto& loop_map = GpuLower::current()->caParallelMap();
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_expr_sort.cpp]: This is so confusing 😆

**Review by naoyam — APPROVED** [review]
Makes sense to me.
