### PR TITLE
Fix div(Val, TensorView)

### LINKED ISSUE #1777: Incorrect kernel for binaryOp(scalar, tensor)
### 🐛 Describe the bug

```python
import torch
from torch._C._nvfuser import Fusion, FusionDefinition, DataType

# Construct and Define Fusion
fusion = Fusion()

with FusionDefinition(fusion) as fd :
    t0 = fd.define_tensor(0)
    fd.add_input(t0)
    c0 = fd.define_constant(1.5)
    t1 = fd.Ops.div(c0, t0)
    fd.add_output(t1)

fusion.print_ir()
```
Output:
```
Inputs:
  T0_g[ iS0{i0}, iS1{i2} ], float
Outputs:
  T1_g[ iS2{i0}, iS3{i2} ], float

%kernel_math {
T1_g[ iS2{i0}, iS3{i2} ]
   = T0_g[ iS0{i0}, iS1{i2} ] # this should be double(1.5)
   / T0_g[ iS0{i0}, iS1{i2} ];
}

```

The bug is on this line https://github.com/csarofeen/pytorch/blob/a054b3efcf5af58ea518de283f55aaf9fe06ff5f/torch/csrc/jit/codegen/cuda/arith.cpp#L736

### Versions

.

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Fixes https://github.com/csarofeen/pytorch/issues/1777

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
😵‍💫 good catch.

**Comment by csarofeen** [comment]
@jjsjann123 looks like a 1 line cherry-pick, I assume this won't conflict for you in any significant way.

File: torch/csrc/jit/codegen/cuda/test/test_gpu.cpp [hunk 1]
```diff
@@ -23354,6 +23354,30 @@ TEST_F(NVFuserTest, FusionContigPredicate_CUDA) {
   testValidate(fe.kernel(), cg_outputs, {t0}, {ref}, __LINE__, __FILE__);
 }
 
+// Repro of https://github.com/csarofeen/pytorch/issues/1777
+TEST_F(NVFuserTest, FusionDivScalarLhs_CUDA) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/test/test_gpu.cpp:23358]: Thanks for also including the test.

File: torch/csrc/jit/codegen/cuda/arith.cpp [hunk 2]
```diff
@@ -733,7 +733,7 @@ TensorView* binaryOp(
   }                                                                     \
   TensorView* op_name(Val* v1, TensorView* v2) {                        \
     return binaryOp(                                                    \
-        BinaryOpType::op_type, v2, v2, TypePromotion::float_op_config); \
+        BinaryOpType::op_type, v1, v2, TypePromotion::float_op_config); \
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/arith.cpp:736]: How did we pass our python test?!?!?!

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/arith.cpp:736]: 😮

Comment (IvanYashchuk) [reply torch/csrc/jit/codegen/cuda/arith.cpp:736]: Because in the TorchScript world it seems there's no `div(Scalar, Tensor)`, it's replaced with `reciprocal` and `mul`:
```py
import torch # Colab's 1.11.0+cu113

@torch.jit.script
def f(a):
  return torch.div(1.5, a)

print(f.graph)
```
```
graph(%a.1 : Tensor):
  %1 : float = prim::Constant[value=1.5]() # <ipython-input-19-8e64aa4eb1a0>:3:19
  %3 : Tensor = aten::reciprocal(%a.1) # <string>:21:9
  %4 : Tensor = aten::mul(%3, %1) # <string>:21:9
  return (%4)
```
