### PR TITLE
Val::isOneInt

### LINKED ISSUE #203: Val::isOneInt failure
## 🐛 Bug

```
    Int* x = new Int(1);
    Int* y = new Int(1);
    Val* z = mul(x, y);
    z->isOneInt(); <-- An exception is thrown here
```
An exception is thrown as:

```
C++ exception with description "bad optional access" thrown in the test body.
```

`Val::isZeroInt` has the same problem.

### PR DESCRIPTION
**Pull request by naoyam**
Fix #203

### CODE REVIEW

**Comment by csarofeen** [comment]
Thanks, can you just remove the prints in the test please?

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -4477,6 +4477,39 @@ void testGPU_FusionUnrollWithAlloc() {
...
+    TORCH_CHECK(x->isOneInt());
+    TORCH_CHECK(y->isOneInt());
+    if (z->isOneInt()) {
+      std::cout << "z is one int: " << z << std::endl;
+    } else {
+      std::cout << "z is not one int: " << z << std::endl;
+    }
+  }
+
+  // Test isZeroInt
```
Comment (tlemo) [inline test/cpp/jit/test_gpu.cpp]: please move this one to a dedicated test case

**Review by tlemo — CHANGES_REQUESTED** [review]

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp]: Done.

**Review by tlemo — APPROVED** [review]
