### PR TITLE
Fix cache_before

### LINKED ISSUE #408: cache_before problem
## 🐛 Bug

The following fusion fails at the call to `cache_before`:

```
TEST(NVFuserTest, FusionCacheBeforeTest) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeDummyTensor(2);
  fusion.addInput(tv0);
  auto tv1 = add(tv0, new Float(1.0));
  auto tv2 = sum(tv1, {1});
  fusion.addOutput(tv2);

  tv2->split(0, 4);
  tv0->computeAt(tv2, -1);

  tv2->cache_before();
}
```

```
[ RUN      ] NVFuserTest.FusionCacheBeforeTest
unknown file: Failure
C++ exception with description "Compute at called on an axis outside valid range.
Exception raised from computeAt at ../torch/csrc/jit/codegen/cuda/tensor_view.cpp:281 (most recent call first):
frame #0: <unknown function> + 0xf1401 (0x7f2e0caf1401 in /home/nmaruyama/pytorch/debug2/build/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4c (0x563d5274e6fe in ./build/bin/test_jit)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x40 (0x7f2e0caf0696 in /home/nmaruyama/pytorch/debug2/build/lib/libc10.so)
frame #3: torch::jit::fuser::TensorView::computeAt(torch::jit::fuser::TensorView*, int) + 0x270 (0x7f2e1138a698 in /home/nmaruyama/pytorch/debug2/build/lib/libtorch_cuda.so)
frame #4: torch::jit::fuser::TensorView::cache_before() + 0x96c (0x7f2e1138c228 in /home/nmaruyama/pytorch/debug2/build/lib/libtorch_cuda.so)
frame #5: torch::jit::NVFuserTest_FusionCacheBeforeTest_Test::TestBody() + 0x197 (0x563d52724fe7 in ./build/bin/test_jit)
frame #6: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x65 (0x563d52790cd1 in ./build/bin/test_jit)
frame #7: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x5a (0x563d5278b5ad in ./build/bin/test_jit)
frame #8: testing::Test::Run() + 0xd2 (0x563d5276b168 in ./build/bin/test_jit)
frame #9: testing::TestInfo::Run() + 0xf3 (0x563d5276babf in ./build/bin/test_jit)
frame #10: testing::TestCase::Run() + 0x104 (0x563d5276c140 in ./build/bin/test_jit)
frame #11: testing::internal::UnitTestImpl::RunAllTests() + 0x2a6 (0x563d52776f2a in ./build/bin/test_jit)
frame #12: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x65 (0x563d52791ce2 in ./build/bin/test_jit)
frame #13: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 0x5a (0x563d5278c2b3 in ./build/bin/test_jit)
frame #14: testing::UnitTest::Run() + 0xc0 (0x563d527759ae in ./build/bin/test_jit)
frame #15: <unknown function> + 0x26c6b8 (0x563d524b46b8 in ./build/bin/test_jit)
frame #16: main + 0x18a (0x563d524b45d5 in ./build/bin/test_jit)
frame #17: __libc_start_main + 0xe7 (0x7f2e0c292b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #18: _start + 0x2a (0x563d524b42ca in ./build/bin/test_jit)
" thrown in the test body.
```

For the complete test, see https://github.com/csarofeen/pytorch/blob/cache-problem/test/cpp/jit/test_gpu.cpp#L7179.

I think that the problem is caused by the logic of handling reduction domains, which are removed from the original tensor. When they are removed, the new tensor domain is set with the root domain minus the reduction domains, but then the new tensor domain is not transformed back from the root domain. So, all the IterDomain expressions previously applied to the tensor domain are lost. Therefore, for example, `getThisComputeAtAxis()` at line 453 of tensor_view.cpp can return an invalid position, which is exactly what happens with the above example.

### PR DESCRIPTION
**Pull request by naoyam**
Currently, cache_before seems to have two problems. First, when the
cached tensor has reductions, its IterDomain expression history is lost
as it gets a new TensorDomain with only its root domains minus the
reduction domains.

Second, using computeAt does not necessarily generate correct computeAt
relationships. For example, in the CacheBefore test, T1's computeAt
tensor is still T2 even after cache_before. It should be the cache
tensor instead.

A test case is also added. See #408 as well.

Fixes #408

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp [hunk 1]
```diff
@@ -435,28 +450,77 @@ TensorView* TensorView::cache_before() {
...
-      if (origin_input->hasComputeAt() &&
-          origin_input->getComputeAtView() == this) {
+    if (!cache_replayed) {
+      TransformReplay::replayPasC(producer, consumer, -1);
+      cache_replayed = true;
+    }
+    producer->setComputeAt(consumer, (int)getThisComputeAtAxis());
+  }
+
+  // If the consumer was the target of computeAt by its input input
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/tensor_view.cpp]: nit, `input input`, should this be `producer's inputs`

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp [hunk 2]
```diff
@@ -435,28 +450,77 @@ TensorView* TensorView::cache_before() {
   // Expr* producer_uses =
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/tensor_view.cpp:450]: Small nit above, not related to this PR. origin_expr is no longer valid because we replaced it, may be safe for future updates if we set it to nulllptr.

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp [hunk 3]
```diff
@@ -435,28 +450,77 @@ TensorView* TensorView::cache_before() {
...
+  for (TensorView* origin_input :
+       ir_utils::filterByType<TensorView>(expr_inputs)) {
+    if (origin_input->hasComputeAt() &&
+        origin_input->getComputeAtView() == this) {
+      if (!cache_replayed) {
         TransformReplay::replayPasC(producer, consumer, -1);
+        cache_replayed = true;
+      }
+      auto origin_rel_ca_pos = origin_input->getRelativeComputeAtAxis();
+      origin_input->setComputeAt(producer, origin_rel_ca_pos);
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/tensor_view.cpp]: You can use this function instead as this and relative position don't need to be recomputed:
```.cpp
  // Set all computeAt members without checking any correctness. Useful for
  // computeAt with outputs relative to eachother
  void setComputeAt(TensorView* computeAtView, int thisPos, int relPos);
```

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp [hunk 4]
```diff
@@ -435,28 +450,77 @@ TensorView* TensorView::cache_before() {
...
-        origin_input->computeAt(producer, origin_ca_pos);
-        producer->setComputeAt(consumer, origin_rel_ca_pos);
+  // Finally, make the cache tensor computed at the consumer. The
+  // position is set at the deepest position among the position where
+  // its inputs are computed at. If that position is equial or smaller
+  // than the position already set by the case where the consumer has
+  // computeAt, nothing needs to be done.
+  // Note that this step isn't strictly necessary in terms of the
+  // Fusion IR semantics, but it's likely what users would want to do
+  // anyway.
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/tensor_view.cpp:513]: 👍

**Review by csarofeen — CHANGES_REQUESTED** [review]
Mostly looks good to me, just uncertain about my last question.

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/tensor_view.cpp]: Thanks. Changed to use that version of setComputeAt.

File: torch/csrc/jit/codegen/cuda/tensor_view.cpp [hunk 5]
```diff
@@ -435,28 +450,82 @@ TensorView* TensorView::cache_before() {
...
+  if (producer_this_pos > producer->getThisComputeAtAxis()) {
+    // The relative position at the consumer must not include the
+    // reduction domains.
+    auto rel_pos = producer_this_pos;
+    for (size_t i = 0; i < producer_this_pos; ++i) {
+      if (i < producer->getThisComputeAtAxis()) {
+        // No CA axes can be reduction.
+        TORCH_INTERNAL_ASSERT(!producer->axis(i)->isReduction());
+      } else if (producer->axis(i)->isReduction()) {
+        rel_pos = i;
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/tensor_view.cpp:523]: Changed to stop moving the position when a reduction axis is found.

**Review by csarofeen — APPROVED** [review]
