### PR TITLE
Fix placement of block sync with halo loop

### LINKED ISSUE #893: RAW sync must not be placed inside halo-extended parallel loops
Still working on a simpler reproducer, but first noticed this error with the horizontal diffusion test (#887). The error looks like this:

```
__shared__ T0[N];
T0[threadIdx.x] = ...;
for (i = threadIdx.x; i < N+1; i += blockDim.x) {
  syncthreads();
  if (i < N) {
    T1[i] = T0[i] + ...;
  }
}
```

The `syncthreads` isn't uniformly called by all the threads in a thread block, so it should hang.

The logic of the RAW placement is correct as long as all parallelized loops have an extent of equal size as the number of threads, which may not be the case with halo.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #893 

The fix is ad-hoc, making the logic rather convoluted. I'm not very satisfied, but wanted to make progress.

Also adds a horizontal-diffusion test, which is based on CUDA code provided by Vishal Mehta (he agrees to use the code as a test).

### CODE REVIEW

File: test/cpp/jit/test_gpu_shift.cpp [hunk 1]
```diff
@@ -1907,6 +1907,297 @@ TEST(NVFuserTest, FusionShiftBcast3_CUDA) {
...
+  auto tv2 = add(tv1, new Double(2));
+  auto tv3 = shift(tv2, {1});
+  fusion.addOutput(tv3);
+
+  // This doesn't work. syncthreads is needed between tv1 and tv2, but
+  // both the loop extent of both tv1 and tv2 has halo, so the loop is
+  // not eliminated even though it is parallelized. Moving syncthreads
+  // out of the loop would make it placed before tv1, which would make
+  // it meaningless.
+  // Ideally, an exception should be through at this computeAt, but at
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu_shift.cpp]: nit: thrown not through

Comment (csarofeen) [reply test/cpp/jit/test_gpu_shift.cpp]: Isn't this only an issue if we have cross-talk on the threads through shared memory? In this particular case, do we need a syncthreads since each thread reads the value it just wrote? Potentially we could even reduce this to a threadfence.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp [hunk 2]
```diff
@@ -256,8 +256,101 @@ class ExprFlattener : private kir::IrVisitor {
   }
 };
 
+class ValidatePlacementAfterWrites : private kir::IrVisitor {
+ public:
+  //! Validate no expr in writes found under loop
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:261]: This is asserting if an expr is found within a scope (including nested scopes)?

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp [hunk 3]
```diff
@@ -351,31 +451,31 @@ class ReadAfterWriteSyncs : public kir::MutableIrVisitor {
...
-    for (auto& item : smem) {
-      item.second = false;
-    }
+  static void cleanSharedMemory(
+      std::unordered_map<kir::Val*, kir::Expr*>& smem) {
+    smem.clear();
   }
 
   // Return the status of the shared memory buffer
   // False if TensorView is not shared memory buffer
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp]: Comment no longer makes sense

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp [hunk 4]
```diff
@@ -351,31 +451,31 @@ class ReadAfterWriteSyncs : public kir::MutableIrVisitor {
...
-      return false;
-    });
+    }
+    return last_writes;
   }
 
   ReadAfterWriteSyncs(std::vector<kir::Expr*> _loop_nests)
       : loop_nests_(std::move(_loop_nests)) {
     // Fusion shared_memory values
     // Tracks if shared memory is modified
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:478]: I don't understand how this is the case. You changed the map from bool to Expr*, having trouble understanding why.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp [hunk 5]
```diff
@@ -419,6 +520,8 @@ class ReadAfterWriteSyncs : public kir::MutableIrVisitor {
  private:
   //! Keep track of expressions that must be followed by syncthreads
   std::deque<kir::Expr*> sync_after_;
+  //! Keep track of write expressions that must be placed before syncthreads
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp]: I think this tracks the last write to the shared memory buffer we're trying to sync? Comment is a little unclear had to gather what's going on from context.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp [hunk 6]
```diff
@@ -256,8 +256,101 @@ class ExprFlattener : private kir::IrVisitor {
...
+    if (!halo_loop_found) {
+      return false;
+    }
+
+    auto halo_loop = *halo_loop_it;
+
+    // Make sure the writes to the smem buffer are located before the
+    // halo loop. It should be sufficient to validate no write is
+    // found under the halo loop.
+    ValidatePlacementAfterWrites::validate(halo_loop, writes);
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:338]: Seems this just makes sure there's no writes to the smem buffer we're trying to sync the writes of in the halo loop we need to sync before.

**Review by csarofeen — CHANGES_REQUESTED** [review]
I'm having a little trouble understand how you've implemented this. I don't get isModifiedSharedMemory, and I don't really understand last_writes. I think it would be helpful to have some more comments, or maybe expand on it in the PR description.

File: test/cpp/jit/test_gpu_shift.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu_shift.cpp]: Technically, that's true, but the current sync insertion logic does not differentiate whether there really exists dependencies between threads through a smem buffer. This can be fixed.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:261]: Yes

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 4 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:478]: The change of `bool` to `Expr*` doesn't really affect the original logic since `bool` was only used to indicate if there's any mapping from `Val*`. `smem` didn't need to be a map but could be just a set.

What I changed is to keep track of write expressions as well. Since the boolean value wasn't necessary, I just changed the map to hold `Expr*`.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp]: Updated.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp]: Yes. Added more comments.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 6 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:338]: Yes. Updated the comment. Hopefully it's more clear.

File: test/cpp/jit/test_gpu_shift.cpp (hunk 1 above)
Comment (csarofeen) [reply test/cpp/jit/test_gpu_shift.cpp]: Thanks, yeah that makes sense. Was just asking since it's being placed as a test may be worth mentioning that if we change the behavior. I think it would be good to reduce syncthreads when not needed, but that can definitely be left for later work.

File: torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp (hunk 4 above)
Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/lower_insert_syncs.cpp:478]: Thank you, this makes more sense to me now.

**Review by csarofeen — APPROVED** [review]
Thank you, this makes a lot more sense to me now. LGTM.
