### PR TITLE
Collect thread predicates when generating unswitch conditions

### LINKED ISSUE #1129: Thread predicates missing in unswitch conditions
Looks like we are missing thread predicates in unswitch conditions.

Example:

```
  auto tv0 = makeConcreteTensor({10, 1024});
  fusion.addInput(tv0);

  auto tv1 = sum(tv0, {1});
  auto tv2 = add(tv1, new Double(1));
  auto tv3 = add(tv2, new Double(1));

  fusion.addOutput(tv3);

  tv1->axis(-1)->parallelize(ParallelType::TIDx);
  tv2->computeAt(tv3, -1);
  tv3->axis(0)->parallelize(ParallelType::Unswitch);
```

```
Inputs:
  T0_g[ iS0{10}, iS1{1024} ], float
Outputs:
  T3_g[ iUS5{10} ] produce_pos( 1), float

%kernel_math {
T1_l[ iS2{10}, rthreadIdx.x3{1024} ] = reduction( T0_g[ iS0{10}, iS1{1024} ], op = add, initial value = double(0) )
T2_l[ iS4{10} ] ca_pos( 1 )
   = T1_l[ iS2{10}, rthreadIdx.x3{1024} ]
   + double(1);
T3_g[ iUS5{10} ] produce_pos( 1)
   = T2_l[ iS4{10} ] ca_pos( 1 )
   + double(1);
}
```

```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 1> T3) {
  alignas(4) extern __shared__ char array[];
  void* shared_mem = array;
  NVFUSER_DEFINE_MAGIC_ZERO
  float T1[10];
  #pragma unroll
  for(nvfuser_index_t ki58 = 0; ki58 < 10; ++ki58) {
    T1[ki58] = 0;
  }
  NVFUSER_UPDATE_MAGIC_ZERO
  #pragma unroll
  for(nvfuser_index_t ki52 = 0; ki52 < 10; ++ki52) {
    blockReduce<true, false, false>(
      T1[ki52],
      T0[((ki52 + nvfuser_zero) * T0.stride[0]) + (((nvfuser_index_t)threadIdx.x) * T0.stride[1])],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      ((ki52 + nvfuser_zero) < 10),
      float(0));
  }
  NVFUSER_UPDATE_MAGIC_ZERO
  if (((10 - 1) < 10)) {
    #pragma unroll
    for(nvfuser_index_t ki44 = 0; ki44 < 10; ++ki44) {
      float T2[1];
      T2[0]
        = T1[ki44]
        + (float) 1;
      T3[((ki44 + nvfuser_zero) * 1)]
        = T2[0]
        + (float) 1;
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  } else {
    #pragma unroll
    for(nvfuser_index_t ki44 = 0; ki44 < 10; ++ki44) {
      float T2[1];
      T2[0]
        = T1[ki44]
        + (float) 1;
      if ((((ki44 + nvfuser_zero) < 10) && (((nvfuser_index_t)threadIdx.x) == 0))) {
        T3[((ki44 + nvfuser_zero) * 1)]
          = T2[0]
          + (float) 1;
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
}
```

Notice that `threadIdx.x == 0` for `T3` in the else case of the unswitch branch is missing in the unswitched case. Running the kernels fails at result validation.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #1129 

Thread predicates are missing in generating unswitch conditions. This PR collects thread predicates from unswitched expressions, merge them and append the merged one into the generated unswitch Bool val.

The main new logic is the merging of thread predicates at: `ThreadPredicateMap::mergeForUnswitch`. Other changes are mostly minor cosmetic ones.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp [hunk 1]
```diff
@@ -414,6 +418,38 @@ void ThreadPredicateMap::print() const {
...
+        const ThreadPredicateMap::PredicateInfo& info_x,
+        const ThreadPredicateMap::PredicateInfo& info_y) {
+  // Generally, we just need to take a union of two
+  // ParallelTypeBitmaps. However, when source_map isn't empty for BID
+  // types, it's not valid to just merge source tensors. For example, when
+  // one pred_info has a non-empty source map, and another has an
+  // empty map, it would need a predicate like "T1_pred && blockIdx.x
+  // == 0". This isn't expressible in the current PredicateInfo
+  // logic since when source map isn't empty for BID, it would only
+  // generate the flags based on source tensors and ignore blockDim.x ==
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp]: Nit: `blockIdx.x`

**Review by csarofeen — APPROVED** [review]
Instead of adding the thread predicates to the unswitch predicate. Can we use thread predicates in the unswitch block. It seems to me like this PR provides correctness (so will approve as of now since it is strictly better), but it removes almost entirely the point of having an unswitch block.

Instead of:
```
  if ((((((((nvfuser_index_t)blockIdx.x) * 1) + (1 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * 2) + (2 - 1)) < T0.size[1])) && (((nvfuser_index_t)threadIdx.x) == 0))) {
    constexpr nvfuser_index_t ki100 = 0;
    float T1[1];
    T1[0] = 0;
    float T3[1];
    T3[0] = 0;
    #pragma unroll
    for(nvfuser_index_t ki110 = 0; ki110 < 2; ++ki110) {
      T3[0]
        = T3[0]
        + T0[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * 2) + (ki110 + nvfuser_zero)) * T0.stride[1])];
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    blockReduce<true, false, false>(
      T1[0],
      T3[0],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      true,
      true,
      float(0));
    T2[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * 1)]
       = T1[0];
  } else {...
  ```
  
  I would really like to see:
  ```
    if ((((((((nvfuser_index_t)blockIdx.x) * 1) + (1 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * 2) + (2 - 1)) < T0.size[1])))) {
    constexpr nvfuser_index_t ki100 = 0;
    float T1[1];
    T1[0] = 0;
    float T3[1];
    T3[0] = 0;
    #pragma unroll
    for(nvfuser_index_t ki110 = 0; ki110 < 2; ++ki110) {
      T3[0]
        = T3[0]
        + T0[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * 2) + (ki110 + nvfuser_zero)) * T0.stride[1])];
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    blockReduce<true, false, false>(
      T1[0],
      T3[0],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      true,
      true,
      float(0));
  if ((((nvfuser_index_t)threadIdx.x) == 0)){
    T2[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * 1)]
       = T1[0];
  }
  } else {...
  ```

**Comment by naoyam** [comment]
> Instead of adding the thread predicates to the unswitch predicate. Can we use thread predicates in the unswitch block. It seems to me like this PR provides correctness (so will approve as of now since it is strictly better), but it removes almost entirely the point of having an unswitch block.
> 
> Instead of:
> 
> ```
>   if ((((((((nvfuser_index_t)blockIdx.x) * 1) + (1 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * 2) + (2 - 1)) < T0.size[1])) && (((nvfuser_index_t)threadIdx.x) == 0))) {
>     constexpr nvfuser_index_t ki100 = 0;
>     float T1[1];
>     T1[0] = 0;
>     float T3[1];
>     T3[0] = 0;
>     #pragma unroll
>     for(nvfuser_index_t ki110 = 0; ki110 < 2; ++ki110) {
>       T3[0]
>         = T3[0]
>         + T0[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * 2) + (ki110 + nvfuser_zero)) * T0.stride[1])];
>     }
>     NVFUSER_UPDATE_MAGIC_ZERO
>     blockReduce<true, false, false>(
>       T1[0],
>       T3[0],
>       [](float &a, float b) { a = a + b; },
>       threadIdx,
>       blockDim,
>       static_cast<float*>(shared_mem),
>       true,
>       true,
>       float(0));
>     T2[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * 1)]
>        = T1[0];
>   } else {...
> ```
> 
> I would really like to see:
> 
> ```
>   if ((((((((nvfuser_index_t)blockIdx.x) * 1) + (1 - 1)) < T0.size[0]) && (((((nvfuser_index_t)threadIdx.x) * 2) + (2 - 1)) < T0.size[1])))) {
>   constexpr nvfuser_index_t ki100 = 0;
>   float T1[1];
>   T1[0] = 0;
>   float T3[1];
>   T3[0] = 0;
>   #pragma unroll
>   for(nvfuser_index_t ki110 = 0; ki110 < 2; ++ki110) {
>     T3[0]
>       = T3[0]
>       + T0[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * T0.stride[0]) + (((((nvfuser_index_t)threadIdx.x) * 2) + (ki110 + nvfuser_zero)) * T0.stride[1])];
>   }
>   NVFUSER_UPDATE_MAGIC_ZERO
>   blockReduce<true, false, false>(
>     T1[0],
>     T3[0],
>     [](float &a, float b) { a = a + b; },
>     threadIdx,
>     blockDim,
>     static_cast<float*>(shared_mem),
>     true,
>     true,
>     float(0));
> if ((((nvfuser_index_t)threadIdx.x) == 0)){
>   T2[(((((nvfuser_index_t)blockIdx.x) * 1) + ki100) * 1)]
>      = T1[0];
> }
> } else {...
> ```

That makes sense. It'll need some further changes, so I'll work on it as a follow-up PR.
