### PR TITLE
Fixes validation of vectorization with contig indexing

### LINKED ISSUE #1534: Vectorization validation still fails to detect invalid vectorization with contig indexing
Contig indexing and vectorization still has a problem. This fusion doesn't trigger any validation error but fails at run time due to a misaligned access:

```
  std::vector<int64_t> shape1{2, 3, 2};
  std::vector<int64_t> shape2{2, 2};

  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeContigConcreteTensor(shape1);
  fusion.addInput(tv0);
  auto tv1 = makeContigConcreteTensor(shape2);
  fusion.addInput(tv1);

  auto tv2 = set(tv1);
  auto tv3 = broadcast(tv2, {false, true, false});
  auto tv4 = add(tv0, tv3);
  fusion.addOutput(tv4);

  tv4->merge(1, 2);
  tv4->merge(0, 1);
  tv4->split(0, 4);
  TransformPropagator::from(tv4);

  tv0->computeAt(tv4, -2);
  tv1->computeAt(tv4, -2);

  // Vectorize by 4. Validation passes as axes 0 an 1 are contig merged.
  tv2->axis(-1)->parallelize(ParallelType::Vectorize);

  fusion.printMath();
  fusion.printKernel();

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn(shape1, options);
  auto t1 = at::randn(shape2, options);

  FusionExecutor fe;
  fe.compileFusion(&fusion, {t0, t1});
  auto cg_outputs = fe.runFusion({t0, t1});

  auto ref = t0 + t1.unsqueeze(1);

  testValidate(&fusion, cg_outputs, {t0, t1}, {ref}, __LINE__, __FILE__);
}
```

```
Inputs:
  T0_g[ iS19{( ceilDiv(( 2 * ( 3 * 2 ) ), 4) )}, iS20{4} ], float
  T1_g[ iS29{( ceilDiv(( 2 * 2 ), 4) )}, iS30{4} ], float
Outputs:
  T4_g[ iS15{( ceilDiv(( 2 * ( 3 * 2 ) ), 4) )}, iS16{4} ] produce_pos( 1), float

%kernel_math {
T2_l[ iS26{( ceilDiv(( 2 * 2 ), 4) )}, iV27{4} ] ca_pos( 1 )
   = T1_g[ iS29{( ceilDiv(( 2 * 2 ), 4) )}, iS30{4} ];
T3_l[ iS23{( ceilDiv(( 2 * ( 1 * 2 ) ), 4) )}, iS24{4} ] ca_pos( 1 ) produce_pos( 1) = broadcast( T2_l[ iS26{( ceilDiv(( 2 * 2 ), 4) )}, iV27{4} ] ca_pos( 1 ) )
T4_g[ iS15{( ceilDiv(( 2 * ( 3 * 2 ) ), 4) )}, iS16{4} ] produce_pos( 1)
   = T0_g[ iS19{( ceilDiv(( 2 * ( 3 * 2 ) ), 4) )}, iS20{4} ]
   + T3_l[ iS23{( ceilDiv(( 2 * ( 1 * 2 ) ), 4) )}, iS24{4} ] ca_pos( 1 ) produce_pos( 1);
}
```

The misaligned access happens with `T2_l[ iS26{( ceilDiv(( 2 * 2 ), 4) )}, iV27{4} ] ca_pos( 1 )`. This looks fine, but the issue is the computeAt. The actual outer domain where `T2` is defined is `iS15{( ceilDiv(( 2 * ( 3 * 2 ) ), 4) )}`, and that isn't mapped with the outer domain of `T2`, contig indexing of `T2` isn't actually used, so vectorization can only be done with the innermost domain, whose extent is 2. 

This issue is also addressed in a recent PR by @csarofeen for index hoisting (https://github.com/csarofeen/pytorch/pull/1528/files#diff-9f41b1a1bfad1876bed2c932742e3972d25772d142b1b9331f47583c8fa8ae43R1072-R1085). Validation also needs a similar fix, but at the time of validation, we don't have reference tensors nor index maps. It may make more sense to delay filling this information until the time of indexing.

Edit: We could probably look at concrete domains of the CA parallel map, and if it's a non-broadcast domain while the corresponding domain of the vectorized tensor is a broadcast, we could know contig indexing would fail.

### PR DESCRIPTION
**Pull request by naoyam**
True contig indexing needs reference tensors, so finding vectorized
contig domains at the initial validation time can result in false
positives and negatives. Fixed by filling that information at the time
of indexing.

Also considered to keep it separated from indexing and fill it at the
validation time, but it would end up replicating the same logic as reference
replay.

As a side effect, conting indexing becomes a little less conservative. The fusion of `FusionVectorizeContigIndexWithBroadcast` was not contig indexed previously, and similarly vectorization was not allowed.

Closes #1534

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 1]
```diff
@@ -1433,9 +1449,52 @@ std::vector<Val*> Index::getGlobalProducerStridedIndices(
...
+      producer_tv, consumer_tv, c2p_map, contig_finder);
+
   return strided_inds;
 }
 
+namespace {
+
+// Maps all producer domains to consumer with broadcast
+// forwarding. Used to find the allocation position.
+std::unordered_map<IterDomain*, IterDomain*> mapAllProducerDomainsToConsumer(
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp:1463]: Moved this to its own function. I incorrectly used `replay_PasC` created here to find mapped domains that should really be done using the CA index map. Extracted that part of the code so as to avoid the same error.

File: test/cpp/jit/test_gpu.cpp [hunk 2]
```diff
@@ -21393,6 +21403,103 @@ TEST_F(NVFuserTest, FusionContigIndexingWithBroadcast_CUDA) {
...
+  std::vector<int64_t> shape1{2, 2, 2};
+  std::vector<int64_t> shape2{1, 2, 2};
+
+  Fusion fusion;
+  FusionGuard fg(&fusion);
+
+  auto tv0 = makeContigTensor(shape1.size());
+  fusion.addInput(tv0);
+
+  std::vector<IterDomain*> dom;
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu.cpp]: Shouldn't you use: `makeContigConcreteTensor` for this with sizes {1, -1, -1}?

File: torch/csrc/jit/codegen/cuda/contiguity.h [hunk 3]
```diff
@@ -24,15 +24,25 @@ class ContigIDs : public OptInDispatch {
...
-  // In this case we can linearize indexing of any ID that only consists of
-  // merge operations.
+  //! Check through the history of ids whose inputs map to root_domain with
+  //! contiguity root_contiguity. Return unordered_set of all merges that are
+  //! contiguous. Ignore root order is primarily used for predicate generation.
+  //! In this case we can linearize indexing of any ID that only consists of
+  //! merge operations.
+  //!
+  //! Mapping information from CA Index concrete to reference domains
+  //! is used to find merge output domains can be indexed. If there's
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/contiguity.h]: Nit: Think this should be `if merged output domains can be indexed`

File: torch/csrc/jit/codegen/cuda/contiguity.h [hunk 4]
```diff
@@ -24,15 +24,25 @@ class ContigIDs : public OptInDispatch {
...
+  //!
+  //! id_map can be used when replayed producer domains are
+  //! analyzed, in which case producer-to-consumer maps should be passed.
   ContigIDs(
       const std::vector<IterDomain*>& ids,
       const std::vector<IterDomain*>& root_domain,
-      const std::vector<bool>& root_contiguity);
+      const std::vector<bool>& root_contiguity,
+      const std::unordered_map<IterDomain*, IterDomain*>& concrete_to_ref,
+      const std::unordered_map<IterDomain*, IterDomain*>& id_map = {});
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/contiguity.h]: Nit name: `id_map` -> `p2c_id_map`

File: torch/csrc/jit/codegen/cuda/contiguity.h [hunk 5]
```diff
@@ -65,11 +75,27 @@ class ContigIDs : public OptInDispatch {
 
   void handle(Merge* merge) override;
 
+  IterDomain* getCAIndexConcreteId(IterDomain* id) const;
+
+  //! True if an ID is indexable.
+  //! E.g., a merged domain with broadcast may not be indexable when
+  //! its corresponding reference tensor has non-broadcast domains.
+  bool isIndexable(IterDomain* id) const;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/contiguity.h:87]: If we didn't use a reference and instead had direct indexing on the index map, would this still be an issue? or we could confidently just use the index in the index map?

**Review by csarofeen — COMMENTED** [review]
I really hope if we move indexing to be directly on the index map this logic would be way more straight forward 🤞

**Review by csarofeen — APPROVED** [review]
LGTM Thanks!

File: torch/csrc/jit/codegen/cuda/contiguity.h (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/contiguity.h:87]: I think in either case we would need to check if an IterDomain is indexable, which is equivalent to saying a mapped index for the IterDomain is found in the index map.
