### PR TITLE
Propagate root domain mappings from rfactor to root domains

### LINKED ISSUE #1551: ComputeAtRootDomainMap with view likely broken
I suspect `ComputeAtRootDomainMap` is broken for views. The main purpose of the map is to detect invalid computeAt patterns such as a reduction followed by broadcast. These patterns are detected by traversing root domains backwards, but we only visit arithmetic expressions, so no information is propagated from the rfactor domain of a tensor to its root domain. For example, this would not be flagged as invalid:

```
tv1 = sum(tv0, {1});
tv2 = broadcast(tv1, {false, true});
tv3 = view(tv2, shape1, shape2);
tv4 = view(tv0, shape1, shape2);
tv5 = add(tv3, tv4);

tv1->computeAt(tv1, -1);
```

This would be flagged as invalid without the two `view` ops, but the current `ComputeAtRootDomainMap` would not be able to detect the invalid pattern.

### PR DESCRIPTION
**Pull request by naoyam**
Closes #1551 

The main purpose of ComputeAtRootDomainMap is to find unmappable domains
for comptueAt. This analyais is done by traversing a fusion in a
backward direction. Currently, the traversal only visits arithmetic
expressions, so information propagation is done from consumer tensors to
producer tensors. This propagation is also required from rfactor domains
to root domains. Previously it doesn't really matter as rfactor is
limited reduction domains, but that's not the case with view.

This change also means that ComputeAtRootDomain does not guarantee
one-to-one mappings. For example,

```
tv0: [I0, I1]
tv1 = view(tv0); // tv1: [I0*I1/N, N]
```

I.e., the view op is done first merging the two domains of `tv0` and
then splitting it by N. Note that both of the two rfactor axes of `tv1`
are now mapped with the two axes of `tv0`.

Because of this change, `ComputeAtRootDomainMap:mapBestEffort` and other
mapping functions between a producer and a consumer that is supposed to
return a one-to-one map can fail.
`ComputeAtRootDomainMap::getMappableDims` is fine as it just grabs any
domain that is mappable.

`ComputeAtRootDomainMap::mapConsumerToProducer` and
`ComputeAtRootDomainMap::mapProducerToConsumer` were used in
`TransformReplay::replayPasC` and `TransformReplay::replayCasP`, but
they don't really need to use `ComputeAtRootDomainMap` but just
`PairwiseRootDomainMap` is sufficient, so replaed the usages with the
pairwise variant.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/compute_at.cpp [hunk 1]
```diff
@@ -472,7 +472,10 @@ unsigned int ComputeAt::backwardComputeAt_impl(
   }
 
   auto replay_producer_pair = TransformReplay::replayPasC(
-      producer, consumer, (int)consumer_compute_at_pos, root_map_);
+      producer,
+      consumer,
+      (int)consumer_compute_at_pos,
+      PairwiseRootDomainMap(producer, consumer));
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/compute_at.cpp:478]: We don't need to use `ComputeAtRootDomaiMap` here, and it can fail to generate one-to-one mappings with views. `PairwiseRootDomainMap` is sufficient.

File: test/cpp/jit/test_gpu_view.cpp [hunk 2]
```diff
@@ -922,6 +922,45 @@ TEST_F(NVFuserTest, FusionFlattenAfterUnsqueezeOutput_CUDA) {
...
+  fusion.addInput(tv0);
+
+  auto tv1 = add(tv0, IrBuilder::create<Double>(1));
+
+  // reduction followed by broadcast
+  auto tv2 = sum(tv1, {1});
+  auto tv3 = broadcast(tv2, {false, true, true});
+
+  // Path with a view
+  auto tv4 = view(tv1, input_shape1, input_shape2);
```
Comment (csarofeen) [inline test/cpp/jit/test_gpu_view.cpp:942]: Wow, really didn't even think about this case. Nice catch.

**Review by csarofeen — APPROVED** [review]
LGTM Thanks!

File: test/cpp/jit/test_gpu_view.cpp [hunk 3]
```diff
@@ -922,6 +922,45 @@ TEST_F(NVFuserTest, FusionFlattenAfterUnsqueezeOutput_CUDA) {
...
+
+  // Join the reduciton+broadcast and view paths together
+  auto tv5 = add(tv3, tv4);
+  fusion.addOutput(tv5);
+
+  fusion.printMath();
```
Comment (zasdfgbnm) [inline test/cpp/jit/test_gpu_view.cpp:948]: Is this a debugging print you forget to remove?

Comment (naoyam) [reply test/cpp/jit/test_gpu_view.cpp:948]: My bad, sorry, I'll remove it.
