### PR TITLE
Fix issue #1081

### LINKED ISSUE #1081: Bug with serial and parallel indexing
```
  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);

  auto tv1 = add(tv0, new Double(1));
  auto tv2 = add(tv1, new Double(1));
  fusion.addOutput(tv2);

  tv2->split(-1, 4);
  tv0->computeAt(tv2, -2);

  tv2->axis(-1)->parallelize(ParallelType::TIDx);
```

This results in:

```
__global__ void kernel1(Tensor<float, 1> T0, Tensor<float, 1> T2) {
  NVFUSER_DEFINE_MAGIC_ZERO
  #pragma unroll 1
  for(nvfuser_index_t ki41 = 0; ki41 < (ceilDiv(T0.size[0], 4)); ++ki41) {
    float T1[4];
    #pragma unroll
    for(nvfuser_index_t ki49 = 0; ki49 < 4; ++ki49) {
      if ((((ki41 * 4) + (ki49 + nvfuser_zero)) < T0.size[0])) {
        T1[ki49]
          = T0[(((ki41 * 4) + (ki49 + nvfuser_zero)) * T0.stride[0])]
          + (float) 1;
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    if ((((ki41 * 4) + ((nvfuser_index_t)threadIdx.x)) < T0.size[0])) {
      T2[(((ki41 * 4) + ((nvfuser_index_t)threadIdx.x)) * 1)]
        = T1[0]
        + (float) 1;
    }
  }
}
```

The producer indexing of `T1` is wrong. It should be `T1[threadIdx.x]`. 

The problem occurs when a domain on local memory is computed serially but used by parallel threads. 

```
%kernel_math {
T1_l[ iS5{( ceilDiv(i1, 4) )}, iS6{4} ] ca_pos( 1 )
   = T0_g[ iS7{( ceilDiv(i1, 4) )}, iS8{4} ]
   + double(1);
T2_g[ iS3{( ceilDiv(i1, 4) )}, ithreadIdx.x4{4} ] produce_pos( 1)
   = T1_l[ iS5{( ceilDiv(i1, 4) )}, iS6{4} ] ca_pos( 1 )
   + double(1);
}
```

In this case, the combination of `iS6{4}` of `T1` and `ithreadIdx.x4{4}` of `T2` cause the problem.

We could also say that parallelizing just `T2` would be inefficient  and `T1` should be parallelized in the same way, but it's not incorrect either. 

As far as I see, the same inconsistency can happen with:

- Local memory tensor computed serially and used in parallel
- Shared memory tensor computed serially and used by GID
- Shared memory tensor computed by TID and used by GID

None of them should be considered an invalid pattern of parallelization memory usage, although not ideal in terms of efficiency. I think this is fixable.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #1081 

- Added a reproducer of #1081 (`FusionSerialAndParallelIndexing_CUDA`)
- Added an additional check in `indexMapFromTv` when using zero as an index
- Moved `derivedFromRootCAAxes to lower_utils as it's now also used in index_compute

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 1]
```diff
@@ -1183,8 +1184,38 @@ std::unordered_map<kir::ForLoop*, kir::Val*> indexMapFromTV(
 
   std::unordered_map<kir::ForLoop*, kir::Val*> loop_to_ind_map;
 
+  // When indexed as a producer, the parallel types of the the
+  // producer domains may not be the same as those of the loops, but
+  // that's still valid parallelization. However, in that case, using
+  // the parallel types of the loops to decide replacement of indices
+  // with zero isn't valid. That's only valid when there's a matching
+  // IterDomain in the producer tensor that has the same paralle
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp]: Nit: Parallel

**Review by csarofeen — APPROVED** [review]
LGTM, minor nit in one comment.
