### PR TITLE
Disallow passing immediate scalars as inputs

### LINKED ISSUE #1521: Support scalars with default value
### 🐛 Describe the bug

Not really a bug, but specifying a value for a scalar and adding it as a fusion input causes JIT compilation to fail with `CUDA NVRTC compile error: default_program(3257): error: expected a ")"`
due to a constant value being specified:
` __global__ void kernel1(double 9.9999997473787516e-06, Tensor<float, 5> T0, int64_t i5, int64_t i4, int64_t i3, Tensor<float, 2> T18, Tensor<float, 2> T19, Tensor<float, 5> T14) {`

repro:
clone the https://github.com/eqy/apex/tree/instance_norm_nvfuser branch
edit the `IrBuilder::create<Double>` lines to use a (default) value:
```
Double* _momentum = IrBuilder::create<Double>();
Double* _eps = IrBuilder::create<Double>();
```
```
Double* _momentum = IrBuilder::create<Double>(momentum);
Double* _eps = IrBuilder::create<Double>(eps);
```
build apex with the environment variable `PYTORCH_HOME=/path/to/pytorch/`
run apex L0 tests `python tests/L0/run_test.py`

### Versions

```
PyTorch version: 1.11.0a0+2c916ef
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+2c916ef
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.13.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+2c916ef           dev_0    <develop>
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by naoyam**
Closes #1521

### CODE REVIEW

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -21648,6 +21648,30 @@ TEST_F(NVFuserTest, FusionViewConcreteDomain_CUDA) {
...
+TEST_F(NVFuserTest, FusionImmediateValueAsInput_CUDA) {
+  Fusion fusion;
+  FusionGuard fg(&fusion);
+
+  auto tv0 = makeSymbolicTensor(1);
+  fusion.addInput(tv0);
+
+  auto immediate_scalr = IrBuilder::create<Double>(0.1);
+  // Adding an immediate scalar value as an input is not allowed
+  ASSERT_ANY_THROW(fusion.addInput(immediate_scalr));
```
Comment (jjsjann123) [inline test/cpp/jit/test_gpu.cpp:21661]: Nice!

**Review by jjsjann123 — APPROVED** [review]
LGTM
