### PR TITLE
Forward input tensor dimensions to segmented groups

### LINKED ISSUE #659: Codegen spits illegal code with undefined identifier
## 🐛 Bug

Codebase is here: https://github.com/csarofeen/pytorch/pull/658, built and run with 
`python test_jit_cuda_fuser.py TestCudaFuser.test_layer_norm_autodiff_repro`

The codegen fails in a segmented fusion (`relu_backward` + `native_layer_norm_backwards`), I did create a dangling tensor as return value there: https://github.com/csarofeen/pytorch/pull/658/files#diff-9738ee51d55cdf479f41b018d61ca43ed2ae10c13a20e21ec45b7578e82a23d2R1004, maybe that's causing the issue?

### PR DESCRIPTION
**Pull request by shmsong**
Fixes #659

The segmented groups may have scalar expressions that take input tensor dimensions as input. This PR adds them as needed. A more general issue of supporting scalar expressions in between segmented kernels is tracked in #660

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp [hunk 1]
```diff
@@ -156,11 +156,20 @@ void insertUniquePredicated(
...
-  // Move all the edgees to group input/output
+  // Move all the edges to group input/output
   // Inputs
   insertUniquePredicated(
       input_vals, producer_edges, [](Val* v) { return !v->isFusionInput(); });
 
+  for (auto expr : exprs_) {
+    for (auto i : expr->inputs()) {
+      if (i->isAnInt() && i->definition() == nullptr && !i->isConstScalar() &&
+          !i->isFusionInput()) {
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:167]: dumb question, are we skipping `isFusionInput()` because fusion inputs are available by default to every segmented group?

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:167]: nvm, I saw the section below that seems to be doing that with tensor_map already.

**Review by jjsjann123 — APPROVED** [review]
LGTM.

File: torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp (hunk 1 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/fusion_segmenter.cpp:167]: Yes. The segmented groups would know it if the scalars are input. This fix is just for the scalars that don't know where they came from. One example is extents of `TensorView`. Currently the tv's know where to find its extents but unfortunately there's not a way to specify a clear `definition()` for these scalars.
