### PR TITLE
Clear thread predicates when RAW sync is used

### LINKED ISSUE #2459: Thread predicate map should be cleared if a RAW sync is inserted
Repro:

```
TEST_F(NVFuserTest, FusionClearThreadPredicateByRAWSync_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);

  auto tv1 = sum(tv0, {1});
  auto tv2 = set(tv1);
  auto tv3 = sum(tv2, {0});
  fusion.addOutput(tv3);

  // tv1 is predicated with tidx
  tv1->axis(0)->parallelize(ParallelType::TIDy);
  tv1->axis(1)->parallelize(ParallelType::TIDx);

  // Upload to shmem. Still predicated with tidx, so only the threads
  // with tidx == 0 should be active.
  tv2->axis(0)->parallelize(ParallelType::TIDy);
  tv2->setMemoryType(MemoryType::Shared);

  // Remap the parallelization from tidy to tidx. This should work as
  // tv2 is in shared memory and SyncMap should correctly insert a RAW
  // sync between tv2 and tv3. However, ThreadPredicateMap still marks
  // tv3 as predicated by tidx, and since it is invalid to parallelize
  // by a predicated parallel type, this results in an error.
  tv3->axis(0)->parallelize(ParallelType::TIDx);

  fusion.printMath();
  fusion.printKernel();
}
```
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from NVFuserTest
[ RUN      ] NVFuserTest.FusionClearThreadPredicateByRAWSync_CUDA
Inputs:
  T0_g[ iS0{i0}, iS1{i2} ], float
Outputs:
  T3_g[ rthreadIdx.x5{i0} ], float

%kernel_math {
T1_l[ ithreadIdx.y2{i0}, rthreadIdx.x3{i2} ]
   = reduction( T0_g[ iS0{i0}, iS1{i2} ], op = add, initial value = double(0), allreduce = false )
T2_s[ ithreadIdx.y4{i0} ]
   = T1_l[ ithreadIdx.y2{i0}, rthreadIdx.x3{i2} ];
T3_g[ rthreadIdx.x5{i0} ]
   = reduction( T2_s[ ithreadIdx.y4{i0} ], op = add, initial value = double(0), allreduce = false )
}

unknown file: Failure
C++ exception with description "predicated_parallel_types.none() INTERNAL ASSERT FAILED at "/raid/tmp/nmaruyama/debug1/third_party/nvfuser/csrc/lower_sync_information.cpp":61, please report a bug to PyTorch. Invalid parallelization of tensor t3. The tensor is parallelized with (threadIdx.x), but it's invalid to use the types as the tensor is also predicated with them., thread pred: (threadIdx.x)
Exception raised from validateParallelizationOfTensor at /raid/tmp/nmaruyama/debug1/third_party/nvfuser/csrc/lower_sync_information.cpp:61 (most recent call first):
frame #0: <unknown function> + 0xd48a0 (0x7f1a228d68a0 in /raid/tmp/nmaruyama/debug1/build/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x48 (0x7f1a34d59098 in /raid/tmp/nmaruyama/debug1/build/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x62 (0x7f1a228d6fb2 in /raid/tmp/nmaruyama/debug1/build/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7a (0x7f1a228d4c2a in /raid/tmp/nmaruyama/debug1/build/lib/libc10.so)
```

Likely the same root cause as #2458

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #2459

### CODE REVIEW

**Comment by naoyam** [comment]
Also fixes #2458 

```
    NVFUSER_UPDATE_MAGIC_ZERO
    float T5[1];
    T5[0] = 0.00000000000000000e+00;
    warp::warpReduceTIDX<true>(
      T5[0],
      T11[0],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      true,
      float(0.00000000000000000e+00));
    if (((((nvfuser_index_t)threadIdx.x) == 0) && ((((nvfuser_index_t)threadIdx.y) + (5 * (((nvfuser_index_t)blockIdx.y) + (216 * i78)))) < T0.size[1]))) {
      T2[(((nvfuser_index_t)threadIdx.y) + (5 * (((nvfuser_index_t)blockIdx.y) + (216 * i78))))]
         = T5[0];
    }
  }
}
```

**Comment by liqiangxl** [comment]
confirmed the fix of issue https://github.com/csarofeen/pytorch/issues/2458
thanks for the quick fix!

File: third_party/nvfuser/csrc/lower_thread_predicate.cpp [hunk 1]
```diff
@@ -264,6 +275,21 @@ void ThreadPredicateMap::updateBitSet(const Expr* expr) {
...
+    // If the input is on shared or global memory and is predicated,
+    // and the output is parallelized by the predicate type, a RAW
+    // sync is automatically inserted, so the predication can be
+    // cleared.
+    if (tv_inp->getMemoryType() == MemoryType::Shared ||
+        tv_inp->getMemoryType() == MemoryType::Global) {
+      auto preds_to_clear = (this_input_preds & output_ptypes);
+      // If it's on shared memory, only TID predicates can be
+      // cleared.
+      if (tv_inp->getMemoryType() == MemoryType::Shared) {
```
Comment (csarofeen) [inline third_party/nvfuser/csrc/lower_thread_predicate.cpp:287]: Should the same thing in global memory not clear all threads?

**Review by csarofeen — APPROVED** [review]
LGTM, just curious why a similar clear of all thread dims doesn't happen if in gmem if a grid sync would be inserted

File: third_party/nvfuser/csrc/lower_thread_predicate.cpp (hunk 1 above)
Comment (naoyam) [reply third_party/nvfuser/csrc/lower_thread_predicate.cpp:287]: This disables clearing of the BID flags in the case of shared memory. Since with gmem both TID and BID flags can be cleared, nothing needs to be done. 

I realized this is double negative. I'll see if I could make it more clear.

Comment (csarofeen) [reply third_party/nvfuser/csrc/lower_thread_predicate.cpp:287]: Ah I got it, no worries, you're fine.

Comment (naoyam) [reply third_party/nvfuser/csrc/lower_thread_predicate.cpp:287]: I changed a little anyway.
