### PR TITLE
Fix grid reduction predication

### LINKED ISSUE #219: Proper predication of grid-reduced tensors
Currently, using output tensors of grid reductions is not supported. Expressions can be created using such tensors, but correctness is not guaranteed. Because of this, for example, casting reduction outputs is not supported.

Example:
```
  TensorView* tv1 = reductionOp(BinaryOpType::Add, {1}, new Float(0), tv0);
  TensorView* tv2 = unaryOp(UnaryOpType::Neg, tv1);
  tv1->split(1, bdimx);
  tv1->split(1, gdimx);

  TensorView* tv1_rf = tv1->rFactor({1});

  tv1->computeAt(tv2, -1);

  tv1->axis(0)->parallelize(ParallelType::BIDy);
  tv1_rf->axis(0)->parallelize(ParallelType::BIDy);
  tv2->axis(0)->parallelize(ParallelType::BIDy);
  tv1->axis(-2)->parallelize(ParallelType::BIDx);
  tv1_rf->axis(-2)->parallelize(ParallelType::BIDx);
  tv1->axis(-1)->parallelize(ParallelType::TIDx);
  tv1_rf->axis(-1)->parallelize(ParallelType::TIDx);
```

See `testGPU_FusionGridReduction7` in https://github.com/naoyam/pytorch/blob/fix-gridreduction-predicate/test/cpp/jit/test_gpu.cpp for the full test case. The test case should complete successfully when `gdimx` is 1 since there will be only one thread block along the gridDim.x dimension. Anything larger than that should almost always fail.

The generated code would look like:

```
__global__ void kernel1(Tensor<float, 2> T0, Tensor<float, 2> T3, Tensor<float, 1> T2, Tensor<float, 1> T7, Tensor<int64_t, 1> T8){
  __shared__ float shared_mem[1024];
  float T4[1];
  if ( ( ( ( ( ( 0 * 1 ) + blockIdx.x ) * 128 ) + threadIdx.x ) < T3.size[1] ) ) {
    T4[ 0 ]
       = float(0);
  }
  for(size_t i29 = 0; i29 < ( ceilDiv(( ceilDiv(T3.size[1], 128) ), 1) ); ++i29 ) {
    if ( ( ( ( ( ( i29 * 1 ) + blockIdx.x ) * 128 ) + threadIdx.x ) < T3.size[1] ) ) {
      T4[ 0 ]
         = T4[ 0 ]
         + T0[ ( blockIdx.y * T0.stride[0] ) + ( ( ( ( ( i29 * 1 ) + blockIdx.x ) * 128 ) + threadIdx.x ) * T0.stride[1] ) ];
    }
  }
  float T1[1];
  T1[ 0 ]
     = float(0);
  float block_result;
  blockReduce< true, false, false > ( block_result, T4[ 0 ], reduction_add_float, threadIdx, blockDim, reinterpret_cast<float*>(shared_mem));
  // Allocate global tensor float T7[( T0.size[0] * 1 )];
  // Allocate global tensor int64_t T8[T0.size[0]];
  reduction::gridReduce< true, false, false, false, true, true > ( T1[ 0 ], block_result, reduction_add_float, &T7[0], T8, reinterpret_cast<float*>(shared_mem));
  if ( ( ( blockIdx.x == 0 ) && ( threadIdx.x == 0 ) ) ) {
    T2[ ( blockIdx.y * T2.stride[0] ) ]
       = -T1[ 0 ];
  }
```

Notice that the `Neg` unary op is predicated with `blockIdx.x == 0`. That's not necessarily the right thread block holding the valid output of the `gridReduce`, thus the `Neg` unary operation may use invalid values.

### PR DESCRIPTION
**Pull request by naoyam**
This PR is to fix thread predicate after grid reductions. As summarized in #219, in our current implementation, the code after grid reductions looks like this:

```
  reduction::gridReduce< true, false, false, false, true, true > ( T1[ 0 ], block_result, reduction_add_float, &T7[0], T8, 
  reinterpret_cast<float*>(shared_mem));
  if ( ( ( blockIdx.x == 0 ) && ( threadIdx.x == 0 ) ) ) {
    T2[ ( blockIdx.y * T2.stride[0] ) ]
       = -T1[ 0 ];
  }
```
We generate the predicate expression for `T2 = -T1`. The predicate is correct for `threadIdx` as 0-th threads always have valid reduction results. However, that is random for `blockIdx`, so using 0-th blocks as shown above isn't correct.

With this PR, the generated code looks like this:

```
  bool T1_pred = reduction::gridReduce< true, false, false, false, true, true > ( T1[ 0 ], block_result, reduction_add_float, &T7[0], T8, reinterpret_cast<float*>(shared_mem));
  if ( ( T1_pred && ( threadIdx.x == 0 ) ) ) {
    T2[ ( blockIdx.y * T2.stride[0] ) ]
       = -T1[ 0 ];
  }
```

`gridReduce` now returns a validity flag indicating whether the calling block gets valid results. Expressions using the reduction results use the predicate flag instead of just always using 0-th blocks.

To do so, this PR extends class `ThreadPredicateMap` so that it also records for each tensor its source tensor that cause predication, if exists. More specifically, for each of `TIDx/y/z` and `BIDx/y/z`, it associates a set of `TensorView` that are outputs of reductions and cause predication on that `ParallelType`. There can be multiple such tensors for `TIDx/y/z`, but there must be at most one for `BIDx/y/z` since for `TIDx/y/z` we just use 0-th threads no matter which tensors are associated, but for `BIDx/y/z`, having multiple source tensors mean that there would be multiple predicate flags, but we can't guarantee there exists a thread block that have `true` for all of the flags.

Fixes #219

### CODE REVIEW

**Comment by naoyam** [comment]
Deprecates #170

**Review by csarofeen — APPROVED** [review]

**Comment by naoyam** [comment]
At this point, code around predicate flag variables isn't very robust and should be better structured. Specifically, declaring flag variables is done at the IR printing time, whereas expressions using them are created at the lowering time. Variable definitions and usage are only associated with variable names. If we have a notion of variable declaration in the kernel IR, this could be made more robust.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h [hunk 1]
```diff
@@ -279,6 +279,8 @@ class TORCH_CUDA_API GridReduction : public Expr {
   Allocate* sync_buffer_ = nullptr;
 };
 
+std::string getPredicateFlagName(const TensorView* val);
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/kernel_ir.h:282]: nice. wouldn't this fit better in `lower_thread_predicate.h` though?

I'd like to keep the IR as lightweight as possible (just a data structure). This means keeping lowering and the IR as decoupled as possible.

File: torch/csrc/jit/codegen/cuda/ir_base_nodes.cpp [hunk 2]
```diff
@@ -142,6 +142,10 @@ Expr* Val::getOrigin() {
   return (fusion_->origin(this));
 }
 
+const Expr* Val::getOrigin() const {
+  return (fusion_->origin(this));
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/ir_base_nodes.cpp:146]: nit: ( ) not needed

File: torch/csrc/jit/codegen/cuda/kernel_resource_strings.h [hunk 3]
```diff
@@ -522,7 +524,7 @@ final results.
 template <bool X_BLOCK, bool Y_BLOCK, bool Z_BLOCK,
           bool X_THREAD, bool Y_THREAD, bool Z_THREAD,
           typename T, typename Func>
-__device__ void gridReduce(T& out, T inp_val, Func reduction_op,
+__device__ bool gridReduce(T& out, T inp_val, Func reduction_op,
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/kernel_resource_strings.h:527]: yes!

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp [hunk 4]
```diff
@@ -10,11 +10,24 @@ namespace fuser {
...
+    auto src = *sources.begin();
+    auto flag_name = kir::getPredicateFlagName(src);
+    return new NamedScalar(flag_name, DataType::Bool);
+  } else {
+    return eq(NamedScalar::getParallelIndex(pt), new Int(0));
+  }
 }
 
-Bool* getThreadPredicate(const ir_utils::ParallelTypeBitmap& bits) {
+Bool* getThreadPredicate(
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:28]: what is the difference between `threadPredicate()` and `getThreadPredicate()` ?

-> an example of why consistent naming helps: either use `foo()` or `getFoo()`, but not both (since most of the code base uses the former, I'd stick with that and never use `get` in function names)

In this case I think we avoid the confusion by using more explicit names.

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp [hunk 5]
```diff
@@ -144,23 +205,46 @@ ThreadPredicateMap::const_iterator ThreadPredicateMap::end() const {
...
   return thread_predicates_.at(tv);
 }
 
-ir_utils::ParallelTypeBitmap& ThreadPredicateMap::operator[](
+ThreadPredicateMap::MapType::mapped_type& ThreadPredicateMap::operator[](
     const TensorView* tv) {
   return thread_predicates_[tv];
 }
 
+void ThreadPredicateMap::emplace(
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:223]: why `emplace()` vs. a simpler `push_back`? seems a premature optimization (and a bit confusion since there's one emplace overload which wraps another, defeating the point of a true emplace)..?

**Review by tlemo — CHANGES_REQUESTED** [review]
Looks good, with a few small comments.

File: torch/csrc/jit/codegen/cuda/kernel_ir.h (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/kernel_ir.h:282]: I wasn't quite sure where this should be placed. I just picked `kernel_ir.h` just because it's related to the kernel IR. 

The function is also used from `IRPrinter`. I feel a little uneasy if I needed to include `lower_thread_predicate.h` from `ir_ioprinter.cpp`, but that might make more sense.

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp (hunk 4 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:28]: Agree. Let me refactor them.

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:223]: Nothing particular. These are private functions, so I didn't think too much about design alternatives. I didn't realize it's not going to be true emplace. I'll make them simpler with `insert`.
