### PR TITLE
Fusion IR printer with IterDomain transformations

### LINKED ISSUE #920: Fusion::Print repeats reduction operations
## 🐛 Bug

Fusion IrPrinter produced incorrect IR information.

## To Reproduce
```cpp
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());
  TensorView* tv0 = makeSymbolicTensor(2);
  fusion->addInput(tv0);
  auto tv1 = add(tv0,new Double(1.0));
  auto tv2 = sum(tv1,{1});
  
  fusion->addOutput(tv2);
  tv2->split(1, 1);
  auto tv3=tv2->rFactor({-1});
  TransformPropagator::from(tv3);
  tv0->computeAt(tv2,-1,ComputeAtMode::MostInlined);
  fusion->print();
``` 
gives 
```
%kernel {
T1[ iS2{i1}, iS14{( ceilDiv(i3, 1) )}, iS15{1} ] ca_pos( 3 ) produce_pos( 3)
   = T0[ iS0{i1}, iS16{( ceilDiv(i3, 1) )}, iS17{1} ]
   + double(1);
T3[ iS8{i1}, iS10{( ceilDiv(i3, 1) )}rf, rS11{1}rf ] ca_pos( 2 ) produce_pos( 3) = reduction( T1[ iS2{i1}, iS14{( ceilDiv(i3, 1) )}, iS15{1} ] ca_pos( 3 ) produce_pos( 3), op = add, initial value = double(0) )
T2[ iS12{i1}, rS13{( ceilDiv(i3, 1) )} ] produce_pos( 2) = reduction( T3[ iS8{i1}, iS10{( ceilDiv(i3, 1) )}rf, rS11{1}rf ] ca_pos( 2 ) produce_pos( 3), op = add, initial value = double(0) )
T3[ iS8{i1}, iS10{( ceilDiv(i3, 1) )}rf, rS11{1}rf ] ca_pos( 2 ) produce_pos( 3) = reduction( T1[ iS2{i1}, iS14{( ceilDiv(i3, 1) )}, iS15{1} ] ca_pos( 3 ) produce_pos( 3), op = add, initial value = double(0) )
T2[ iS12{i1}, rS13{( ceilDiv(i3, 1) )} ] produce_pos( 2) = reduction( T3[ iS8{i1}, iS10{( ceilDiv(i3, 1) )}rf, rS11{1}rf ] ca_pos( 2 ) produce_pos( 3), op = add, initial value = double(0) )
}
```

Maybe `IrTransformPrinter` could use some updates to cover the `TensorView` ops and extract all the `IterDomain` ops.

### PR DESCRIPTION
**Pull request by shmsong**
Fixes #920

Sample print gallery:
```cpp

%kernel {
T2[ iblockIdx.x20{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS21{1}, iS19{1}, ithreadIdx.x17{128} ] ca_pos( 4 ) produce_pos( 4)
   = T0[ iblockIdx.x27{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS28{1}, iS26{1}, ithreadIdx.x24{128} ]
   + T1[ iS34{( ceilDiv(( ceilDiv(( ceilDiv(( i5 * i7 ), 128) ), 1) ), 1) )}, iS35{1}, iS33{1}, iS31{128} ];
T3[ iblockIdx.x13{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS14{1}, iS12{1}, ithreadIdx.x10{128} ] produce_pos( 4)
   = T2[ iblockIdx.x20{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS21{1}, iS19{1}, ithreadIdx.x17{128} ] ca_pos( 4 ) produce_pos( 4)
   + double(3);

TransformPrinter : 
T0[ iblockIdx.x27{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS28{1}, iS26{1}, ithreadIdx.x24{128} ]
 root domain : (iS0{i1},iS1{i3})
    Merge: iS0{i1} and iS1{i3} -> iS22{( i1 * i3 )}
    Split: iS22{( i1 * i3 )} by factor 128 -> iS23{( ceilDiv(( i1 * i3 ), 128) )}, ithreadIdx.x24{128}
    Split: iS23{( ceilDiv(( i1 * i3 ), 128) )} by factor 1 -> iS25{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )}, iS26{1}
    Split: iS25{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )} by factor 1 -> iblockIdx.x27{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS28{1}
T1[ iS34{( ceilDiv(( ceilDiv(( ceilDiv(( i5 * i7 ), 128) ), 1) ), 1) )}, iS35{1}, iS33{1}, iS31{128} ]
 root domain : (iS2{i5},iS3{i7})
    Merge: iS2{i5} and iS3{i7} -> iS29{( i5 * i7 )}
    Split: iS29{( i5 * i7 )} by factor 128 -> iS30{( ceilDiv(( i5 * i7 ), 128) )}, iS31{128}
    Split: iS30{( ceilDiv(( i5 * i7 ), 128) )} by factor 1 -> iS32{( ceilDiv(( ceilDiv(( i5 * i7 ), 128) ), 1) )}, iS33{1}
    Split: iS32{( ceilDiv(( ceilDiv(( i5 * i7 ), 128) ), 1) )} by factor 1 -> iS34{( ceilDiv(( ceilDiv(( ceilDiv(( i5 * i7 ), 128) ), 1) ), 1) )}, iS35{1}
T2[ iblockIdx.x20{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS21{1}, iS19{1}, ithreadIdx.x17{128} ] ca_pos( 4 ) produce_pos( 4)
 root domain : (iS4{i1},iS5{i3})
    Merge: iS4{i1} and iS5{i3} -> iS15{( i1 * i3 )}
    Split: iS15{( i1 * i3 )} by factor 128 -> iS16{( ceilDiv(( i1 * i3 ), 128) )}, ithreadIdx.x17{128}
    Split: iS16{( ceilDiv(( i1 * i3 ), 128) )} by factor 1 -> iS18{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )}, iS19{1}
    Split: iS18{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )} by factor 1 -> iblockIdx.x20{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS21{1}
T3[ iblockIdx.x13{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS14{1}, iS12{1}, ithreadIdx.x10{128} ] produce_pos( 4)
 root domain : (iS6{i1},iS7{i3})
    Merge: iS6{i1} and iS7{i3} -> iS8{( i1 * i3 )}
    Split: iS8{( i1 * i3 )} by factor 128 -> iS9{( ceilDiv(( i1 * i3 ), 128) )}, ithreadIdx.x10{128}
    Split: iS9{( ceilDiv(( i1 * i3 ), 128) )} by factor 1 -> iS11{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )}, iS12{1}
    Split: iS11{( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) )} by factor 1 -> iblockIdx.x13{( ceilDiv(( ceilDiv(( ceilDiv(( i1 * i3 ), 128) ), 1) ), 1) )}, iUS14{1}
}
```

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/ir_iostream.cpp [hunk 1]
```diff
@@ -370,6 +372,38 @@ void IrPrinter::handle(const Merge* m) {
   os_ << "\n";
 }
 
+void IrTransformPrinter::handle(Fusion* f) {
+  auto all_vals = DependencyCheck::getAllValsBetween(
+      {f->inputs().begin(), f->inputs().end()}, f->outputs());
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/ir_iostream.cpp]: Should just use `fusion->usedMathVals()`

**Review by csarofeen — APPROVED** [review]
LGTM! one minor comment.

File: torch/csrc/jit/codegen/cuda/ir_iostream.cpp (hunk 1 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/ir_iostream.cpp]: Updated. Thanks!
