### PR TITLE
Fix computation of thread predicate with broadcast

### LINKED ISSUE #1127: Broadcast reset should only reset the predicate of the broadcasted domain
This doesn't seem correct:

```
 // Figure out which dims bcast wants to reset
  const auto bcast_reset_mask = ~(output_preds & input_bcasts);

  // Get rid of any reductions which are bcasted
  output_preds &= bcast_reset_mask;
```
https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp#L216

For example:

```
  auto tv0 = makeConcreteTensor({4});
  fusion.addInput(tv0);

  auto tv1 = sum(tv0, {0});
  auto tv2 = broadcast(tv1, {true});

  auto tv3 = makeConcreteTensor({4, 4});
  fusion.addInput(tv3);

  auto tv4 = sum(tv3, {1});

  auto tv5 = add(tv2, tv4);
  fusion.addOutput(tv5);

  tv1->axis(0)->parallelize(ParallelType::TIDx);
  tv2->axis(0)->parallelize(ParallelType::TIDx);
  tv4->axis(1)->parallelize(ParallelType::TIDx);
  tv5->axis(0)->parallelize(ParallelType::TIDx);
```

`tv2` doesn't have any thread predication, but `tv4` is predicated with respect to `TIDx`. So, this fusion is actually not valid since at `tv5` is parallelized with `TIDx`, but one of its inputs is predicated with `TIDx`. 

Currently, this just generates invalid code.

```
Inputs:
  T0_g[ iS0{4} ], float
  T3_g[ iS3{4}, iS4{4} ], float
Outputs:
  T5_g[ ithreadIdx.x7{4} ], float

%kernel_math {
T1_l[ rthreadIdx.x1{4} ] = reduction( T0_g[ iS0{4} ], op = add, initial value = double(0) )
T2_l[ bthreadIdx.x2{1} ] = broadcast( T1_l[ rthreadIdx.x1{4} ] )
T4_l[ iS5{4}, rthreadIdx.x6{4} ] = reduction( T3_g[ iS3{4}, iS4{4} ], op = add, initial value = double(0) )
T5_g[ ithreadIdx.x7{4} ]
   = T2_l[ bthreadIdx.x2{1} ]
   + T4_l[ iS5{4}, rthreadIdx.x6{4} ];
}
```

```
__global__ void CUDAGeneratedKernel(Tensor<float, 1> T0, Tensor<float, 2> T3, Tensor<float, 1> T5) {
  alignas(4) extern __shared__ char array[];
  void* shared_mem = array;
  NVFUSER_DEFINE_MAGIC_ZERO
  float T1[1];
  T1[0] = 0;
  blockReduce<true, false, false>(
    T1[0],
    T0[(((nvfuser_index_t)threadIdx.x) * T0.stride[0])],
    [](float &a, float b) { a = a + b; },
    threadIdx,
    blockDim,
    static_cast<float*>(shared_mem),
    true,
    float(0));
  float T2[1];
  broadcast::blockBroadcast<true, false, false>(
    T2[0],
    T1[0],
    static_cast<float*>(shared_mem),
    true);
  float T4[4];
  #pragma unroll
  for(nvfuser_index_t ki83 = 0; ki83 < 4; ++ki83) {
    T4[ki83] = 0;
  }
  NVFUSER_UPDATE_MAGIC_ZERO
  #pragma unroll
  for(nvfuser_index_t ki66 = 0; ki66 < 4; ++ki66) {
    blockReduce<true, false, false>(
      T4[ki66],
      T3[((ki66 + nvfuser_zero) * T3.stride[0]) + (((nvfuser_index_t)threadIdx.x) * T3.stride[1])],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      ((ki66 + nvfuser_zero) < 4),
      float(0));
  }
  NVFUSER_UPDATE_MAGIC_ZERO
  T5[(((nvfuser_index_t)threadIdx.x) * 1)]
    = T2[0]
    + T4[((nvfuser_index_t)threadIdx.x)];
}
```

Notice that `T5` has no predicate. That is because of the reset logic in the `updateBitSet`. 

In addition to the problem with `ThreadPredicateMap`, we also need to extend the validation of parallelization to check thread predication.

### PR DESCRIPTION
**Pull request by naoyam**
Previously, a broadcasted input resets a thread predicate of any other input, which is not correct.

Fixes #1127

### CODE REVIEW

File: test/cpp/jit/test_gpu.cpp [hunk 1]
```diff
@@ -17521,6 +17521,48 @@ TEST(NVFuserTest, FusionFloatPow_CUDA) {
...
+  fusion.addInput(tv3);
+
+  auto tv4 = sum(tv3, {1});
+
+  auto tv5 = add(tv2, tv4);
+  fusion.addOutput(tv5);
+
+  tv1->axis(0)->parallelize(ParallelType::TIDx);
+  tv2->axis(0)->parallelize(ParallelType::TIDx);
+  tv4->axis(1)->parallelize(ParallelType::TIDx);
```
Comment (shmsong) [inline test/cpp/jit/test_gpu.cpp:17546]: This test case looks invalid in another aspect, which seems to be another way to look at the same story. 

`T4` should fail parallel check in this case since `tv4->axis(1)` is `TIDx`, and `tv4->axis(0)` is mappable to `tv2->axis(0)` by caParallelMap.

File: test/cpp/jit/test_gpu.cpp [hunk 2]
```diff
@@ -17521,6 +17521,48 @@ TEST(NVFuserTest, FusionFloatPow_CUDA) {
...
+  at::Tensor at_t0 = at::randn({numel}, options);
+  at::Tensor at_t3 = at::randn({numel, numel}, options);
+  std::vector<IValue> aten_inputs = {at_t0, at_t3};
+  auto outputs = fe.runFusion(aten_inputs);
+
+  auto ref = at_t0.sum({0}).unsqueeze(0) + at_t3.sum({1});
+
+  // This fails because tv5 is predicated and parallelized with TIDx.
+  // TODO: Add validation to detect such invalid parallelization
+  ASSERT_ANY_THROW(
```
Comment (shmsong) [inline test/cpp/jit/test_gpu.cpp:17562]: This assertion seems a bit strange to me. I assume we don't want silent errors in any case.  I guess we might have to assert at runFusion time.

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp [hunk 3]
```diff
@@ -266,12 +261,23 @@ void ThreadPredicateMap::updateBitSet(const Expr* expr) {
       }
     }
 
+    // Figure out which dims bcast wants to reset
+    auto this_input_preds = pred_and_src.limited_types;
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:265]: This change makes sense to me and I'm not against it. I agree that we probably never want any input to reset other inputs' predicate, hard to imagine : ). 

But just out of curiosity, would the original method be good enough if we just `go through all the inputs, and make sure no input is parallelized on an parallel type that another one predicates on` before any predicate propagation?

**Review by shmsong — COMMENTED** [review]
The changes make sense. Thanks for fixing this tricky case 👍 . 

Had a few questions and would appreciate a round of discussion before stamping. Would also help me understand the implementation better if I didn't read some part correctly.

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp:17546]: This is really a weird fusion, but it doesn't have any computAt, so nothing is mapped by the parallel map, which only maps CA axes.

File: test/cpp/jit/test_gpu.cpp (hunk 2 above)
Comment (naoyam) [reply test/cpp/jit/test_gpu.cpp:17562]: Yeah, the generated code is invalid in the sense that it should output an incorrect result tensor. The real problem is `tv5` as it's parallelized with `TIDx` and predicated by the same type. There's a follow-up PR that does detect such errors at the time of lowering (#1166)

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:265]: `no input is parallelized on an parallel type that another one predicates on`: <- this can be actually valid if shared memory is used and the corresponding output domain is not parallelized. 

I'm not sure the original method could be made work correctly. To me, the way in this PR seems to make most sense.

File: test/cpp/jit/test_gpu.cpp (hunk 1 above)
Comment (shmsong) [reply test/cpp/jit/test_gpu.cpp:17546]: I see parallel map doesn't help here. Thanks for the clarification.

File: test/cpp/jit/test_gpu.cpp (hunk 2 above)
Comment (shmsong) [reply test/cpp/jit/test_gpu.cpp:17562]: Shouldn't block this PR but still don't think we should assert on silent error. But great to know that #1166 has a fix en route so could be ok for now.

File: torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp (hunk 3 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/lower_thread_predicate.cpp:265]: I see, makes sense. The shared mem cases could be tricky on the original one. Thanks for the clarification.

**Review by shmsong — APPROVED** [review]
LGTM, except one test issue that we expect to be fixed #1166. Thanks for clarifying on some details and thanks again for fixing the predicate issues. 👍
