### PR TITLE
Fix cyclic computeAt

### LINKED ISSUE #200: Cyclic ComputeAt
## 🐛 Bug

A cycle of computeAt tensors can occur in the following case:

(Copied from `testGPU_FusionComputeAtNonterminatingOutput` in https://github.com/naoyam/pytorch/blob/fix-compute-at-cycle/test/cpp/jit/test_gpu.cpp)
```
  TensorView* tv0 = makeDummyTensor(1);
  fusion.addInput(tv0);

  // Common intermediate tensor
  auto tv1 = add(tv0, new Float(0));
  // tv1 -> tv2
  auto tv2 = add(tv1, new Float(0));
  // tv1 -> tv3 -> tv4
  auto tv3 = add(tv1, new Float(0));
  auto tv4 = add(tv3, new Float(0));

  // The order of adding outputs matters. If tv3 is added before tv4,
  // it should be fine. However, if tv4 is added before tv3, there
  // will be a cycle of tv3->tv4 and tv4->tv3. tv3->tv4 is created
  // first, and then tv4->tv3 is created at the final phase of
  // computeAt (ComputeAt::setupOutputs).
  if (true) {
    // A cycle of tv3 <-> tv4 will be created.
    fusion.addOutput(tv2);
    fusion.addOutput(tv4);
    fusion.addOutput(tv3);
  } else {
    // This should work fine.
    fusion.addOutput(tv2);
    fusion.addOutput(tv3);
    fusion.addOutput(tv4);
  }

  tv0->computeAt(tv2, -1);
```

After the `computeAt`, `tv3` is set to be computed at `tv4`, and `tv4` is computed at `tv3`. Cycles like this are not supposed to happen. See `testGPU_FusionComputeAtNonterminatingOutput` in https://github.com/naoyam/pytorch/blob/fix-compute-at-cycle/test/cpp/jit/test_gpu.cpp for a complete reproducer. 

The code generation still works because `IrFix` breaks such cycles. However, we want that computeAt cycles never occur so that `IrFix` can be removed.

### PR DESCRIPTION
**Pull request by naoyam**
This PR fixes #200.

At the end of `computeAt`, we adjust the computeAt relationship among output tensors. It is currently done for non-terminating output tensors, which can result in a cycle of computed-at tensors as shown in #200. 

This PR changes the final adjustment such that only terminating tensors are modified. I believe this ensures the resulting computeAt relationship is always acyclic.

The first 3 commits do:

1. Add a test case exhibiting the cyclic relatinship
2. Refactor `getTerminatingOutputs` so that it can be used outside `IterVistor`.
3. Applies the above change in `ComputeAt::setupOutputs`.

Additionally, since there should be no cycle occurs, `IrFixComputeAt` should no longer be necessary, so I removed it. I first attempted to make it throw an exception when it detects a cycle rather than attempting to fix it (69b0b22), but realized it's actually not trivial because what it actually detects is not a cycle but just a backward computeAt, which can be valid when the target of computeAt is also an output tensor. I do not think `IrFixComputeAt` is necessary, and nothing breaks, so I simply removed it.

This PR is a dependency of another WIP PR, #174.

Remaining minor TODOs:

- [x] Complete the reproducer test case
- [x] Replace `class Expr` in iter_visitor.cpp with `class ExprSort`.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/fusion.cpp [hunk 1]
```diff
@@ -541,6 +549,39 @@ bool Fusion::hasGridReduction() {
...
+
+  const auto exprs = ExprSort::getExprs(
+      this, std::vector<Val*>(outputs().begin(), outputs().end()));
+
+  for (auto expr : exprs) {
+    for (auto inp : expr->inputs())
+      used_vals.emplace(inp);
+  }
+
+  std::unordered_set<Val*> terminating_outputs;
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/fusion.cpp]: I understand I'm criticizing my own code, but to get deterministic ordering, couldn't we simply use the order of `outputs()`? I'm uncertain why I didn't do:
```
std::vector<Val*> terminating_outputs;
  for (auto out : outputs()) {
    if (used_vals.find(out) != used_vals.end())
      continue;
    terminating_outputs.push_back(out);
  }
```
Wouldn't this also give us run to run determinism?

**Review by csarofeen — APPROVED** [review]
Left one minor comment, otherwise looks good, feel free to merge when you're ready.

File: torch/csrc/jit/codegen/cuda/compute_at.cpp [hunk 2]
```diff
@@ -387,12 +387,21 @@ void ComputeAt::setupOutputs() {
     return;
 
   std::vector<TensorView*> touched_output_order;
+  const auto& terminating_outputs =
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/compute_at.cpp:390]: do we need the "full" getTerminatingOutputs() here? I mean, it looks we just want the unordered set version of terminating outputs (which would also avoid the O(N^2) lookup)

File: torch/csrc/jit/codegen/cuda/fusion.cpp (hunk 1 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/fusion.cpp]: That's right and much better! Change applied.

File: torch/csrc/jit/codegen/cuda/compute_at.cpp (hunk 2 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/compute_at.cpp:390]: That's right. We could create a `unordered_set` version of the function. In practice, since the number of output tensors would be just a few, just a `vector` would be actually faster. In any case, since the number is pretty small, I don't think the efficiency would matter.

**Review by tlemo — APPROVED** [review]
