### PR TITLE
issue 1189 repro and fix

### LINKED ISSUE #1189: Infer and alloc error when binding a un-resolved broadcast to grid dimension.
## 🐛 Bug

Broadcast dimensions without broadcast resolution ops should be able to bind to a grid dimension. In that case the grid dimension should implicitly assume a size of 1. Currently this case hit infer and alloc assertion due to the lack of concrete dimension size binding.

## To Reproduce

```cpp
Fusion fusion;
FusionGuard fg(&fusion);

auto tv0 = makeConcreteTensor({16,16});
auto tv1 = makeConcreteTensor({16,16});

auto tv0b = broadcast(tv0, {false,false,true});
auto tv1b = broadcast(tv1, {false,false,true});

fusion.addInput(tv0b);
fusion.addInput(tv1b);

auto tv2 = add(tv0b, tv1b);
auto tv3 = sum(tv2,{1});
fusion.addOutput(tv3);

auto parallelize = [] (auto tv){
  tv->axis(0)->parallelize(ParallelType::TIDx);
  tv->axis(1)->parallelize(ParallelType::BIDx);
  tv->axis(2)->parallelize(ParallelType::BIDy);
};

parallelize(tv0b);
parallelize(tv1b);
parallelize(tv2);
parallelize(tv3);
  
FusionExecutor fe;
fe.compileFusion(&fusion);

auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
at::Tensor t0 = at::randn({16,16,1}, options);
at::Tensor t1 = at::randn({16,16,1}, options);
auto outputs = fe.runFusion({t0,t1});
```

### PR DESCRIPTION
**Pull request by shmsong**
Fixes #1189. This PR contains the short version of the fix and will be cleaned up further in a follow up when parallel dimension map is piped down to the runtime.

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 1]
```diff
@@ -989,12 +989,25 @@ template class ExecutorCompileTimeEntry<OutputAliasIndices>;
...
     for (auto id : tv->domain()->domain()) {
-      if (id->isThread() && !id->isBroadcast()) {
-        parallel_ids.push_back(id);
+      if (id->isThread()) {
+        if (id->isBroadcast()) {
+          // Want to keep the broadcast dimensions if they are not resolved
+          // TODO: piping down the parallel dimension map here would
+          //  be helpful
+          auto& parallel_map = lower.caParallelMap();
+          if (parallel_map.getConcreteMappedID(id) == id) {
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:1003]: Here is basically assuming if a set of parallel dimensions only has broadcast dimensions then it will "concretize" to one of the broadcast dimensions, which means one of the broadcast dims will concretize to itself. Please let me know if this doesn't cover some other cases.

**Review by csarofeen — APPROVED** [review]
Thanks for the fix.
