### PR TITLE
Fix root mapping in index computation

### LINKED ISSUE #476: Root mapping in indexing may not be correct
https://github.com/csarofeen/pytorch/blob/023f4775a6129d5b1108d0a5a4348716c068d955/torch/csrc/jit/codegen/cuda/index_compute.cpp#L576-L577

This seems to result in wrong mappings when a tensor with broadcast dimensions gets broadcasted and computed at. It is solved in `PairwiseRootDomainMap`, though it won't work for output tensors computed at other output tensors.

### PR DESCRIPTION
**Pull request by naoyam**
Closes #476

This replaces a use of the old root mapping (`TensorDomain::mapRootCtoP/PtoC`) with the new ones (`ComputeAtRootDomainMap` and `PairwiseRootDomainMap`). The old one may get confused with broadcast axes, so this PR should lead to be more robust code geneneration.

### CODE REVIEW

**Comment by naoyam** [comment]
This also fixes #329. 

Fusion:
```
  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  auto tv1 = add(tv0, new Float(1));
  auto tv2 = sum(tv1, {1});
  fusion.addOutput(tv2);
  auto tv3 = sum(tv1, {1});
  fusion.addOutput(tv3);

  tv1->computeAt(tv2, -1);
```

Currently, it fails as:

```
unknown file: Failure
C++ exception with description "index_map.find(kir_root_dom_i) != index_map.end() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/index_compute.cpp":842, please report a bug to PyTorch. Couldn't find root mapping for TV0 dim: 1 id: S.i(0 .. T0.size[1])
```

With this PR, indexing and the rest of lowering seems to work fine. A reproducer is added.

File: torch/csrc/jit/codegen/cuda/lower_unroll.h [hunk 1]
```diff
@@ -86,6 +91,8 @@ class TORCH_CUDA_API UnrollPass {
   // Map from TensorView
   const ThreadPredicateMap& thread_predicates_;
 
+  const ComputeAtRootDomainMap& ca_root_map_;
+
   IterDomainMap p2c_root_map_;
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/lower_unroll.h:96]: Having two root mappings may not be necessary. I'll look into this later (#495).

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 2]
```diff
@@ -551,7 +551,9 @@ generateIndexAndExtentMap(
     std::deque<const TensorView*> c2p_tv_stack,
     std::deque<kir::ForLoop*> loops,
     const std::unordered_map<kir::ForLoop*, kir::Val*>& loop_to_ind_map,
-    const std::vector<bool>& last_tv_root_contiguity) {
+    const std::vector<bool>& last_tv_root_contiguity,
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp:610]: it seems it's time to encapsulate all these values into a struct or a class

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 3]
```diff
@@ -773,7 +805,8 @@ generateIndexAndExtentMap(
 kir::TensorIndex* Index::getGlobalProducerIndex(
     TensorView* producer_tv,
     const TensorView* consumer_tv,
-    const std::vector<kir::ForLoop*>& loops) {
+    const std::vector<kir::ForLoop*>& loops,
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp:864]: same thing here: we're passing too much stuff as arguments

File: torch/csrc/jit/codegen/cuda/lower2device.cpp [hunk 4]
```diff
@@ -106,6 +106,9 @@ void GpuLower::lower() {
 
   // Compute thread predicates
   ThreadPredicateMap preds(fusion_);
+  // Compute root-domain mappings
```
Comment (tlemo) [inline torch/csrc/jit/codegen/cuda/lower2device.cpp:110]: nit: please insert an empty line above

File: torch/csrc/jit/codegen/cuda/root_domain_map.cpp [hunk 5]
```diff
@@ -333,50 +352,65 @@ std::unordered_set<const IterDomain*>& ComputeAtRootDomainMap::
...
 
+std::unordered_map<IterDomain*, IterDomain*> ComputeAtRootDomainMap::
+    mapBestEffort(
+        const TensorDomain* from_td,
+        const std::vector<IterDomain*>& from_root,
+        const TensorDomain* to_td,
+        const std::vector<IterDomain*>& to_root) const {
+  std::unordered_map<IterDomain*, IterDomain*> id_map;
+  for (auto& from_id : from_root) {
+    bool mapping_found = false;
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/root_domain_map.cpp]: What does `mapping_found` do? I understand that it signals a valid map insertion but seems unused in the scope.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 3 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:864]: Just wondering, would it make sense to make `Index` stateful instead of being a pure interface? It can have `ca_root_map` as a private member so it doesn't need to be carried around in all the API calls.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 6]
```diff
@@ -572,9 +574,39 @@ generateIndexAndExtentMap(
...
-        TensorDomain::mapRootCtoP(c_tv->domain(), p_tv->domain());
+    // Map root ID's from consumer to producer. c2p_tv_stack may have
+    // an additional producer tensor that is fully replayed. It may
+    // not be actually computed at the consumer. It needs to be
+    // processed specially as it needs full mapping even when it could
+    // indicate invalid root mapping in the sense of computeAt
+    // viability. For the particular case, the simpler pairwise
+    // mapping just works as they are guaranteed to be a
+    // producer-consumer pair.
+    std::unordered_map<IterDomain*, IterDomain*> c2p_root_map;
```
Comment (shmsong) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: Sorry I'm probably not up to date on this. I was wondering where the additional `producer` comes from, and it seems to be the second last one on the `c2p stack`. I knew that the multiple `fusion` outputs are forced to compute at one another. Is it a similar scenario but for an additional `producer` here?

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: It's the producer tensor of `getProducerIndex` or `getGlobalProducerIndex`. We create a list of TVs by following the `computeAtView` field of the consumer tensor. We reverse it and append the producer to it. 

Also, though the list is named as `c2p`, it's the computeAt relationship that actually defines it.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:864]: That sounds like a good idea. Thanks! 

I think that index_compute.cpp could use some refactoring. In this PR, though, I'd keep the code change as minimum as possible since its logical change is not trivial.

File: torch/csrc/jit/codegen/cuda/root_domain_map.cpp (hunk 5 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/root_domain_map.cpp]: Thanks. That was just due to copy-pasting. Removed.

File: torch/csrc/jit/codegen/cuda/lower2device.cpp (hunk 4 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/lower2device.cpp:110]: Done

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 6 above)
Comment (shmsong) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: Oh I see! Thanks for the clarification. Just wanted to double check if I'm understanding correctly. This case here is treated differently from the remaining of the `tv stack` because `ComputeAtRootDomainMap` may not want to include their root maps due to potential inconsistency or reduction violations, is that right?

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: Yes. The computeAt in our system defines not just where a tensor is defined but also where it is declared (allocated). When that tensor is used by multiple consumers, we need to make sure it is accessible by all its consumers. That's the logic behind the validation done in `ComputeAtRootDomainMap`. 

The tensors in the computeAt stack are the ones that are transformed based on the mapping provided by `ComputeAtRootDomainMap`. So, at this point, what we do is to transform index expressions by traversing the computeAt stack. We transform indices defined for one tensor to those for its next next based on the root mapping. 

In the special case with the additional producer tensor, the producer may not be computed at the consumer, and the only thing we can say here is that it's a producer of the consumer. So, `ComputeAtRootDomainMap` may return no mapping for this producer-consumer pair. Instead of `ComputeAtRootDomainMap`, `PairwiseRootDomainMap` simply looks at a producer-consumer pair and maps each axis. Though it's only valid for producer-consumer pairs, it doesn't care the computeAt semantics, and that's why it is used for the special case.

Note that `PairwiseRootDomainMap` may not work for the tensors originally in the computeAt stack since computeAt does not necessarily mean a producer-consumer relationship, i.e., terminating output tensors may have computeAt relationships, but by definition they are not producer-consumer. So, `ComputeAtRootDomainMap` is used as it can be used with arbitrary pairs of tensors.

All in all, in `getProducerIndex`, `PairwiseRootDomainMap` is used for the producer-consumer arguments. After that, `ComputeAtRootDomainMap` is used for the "real" computeAt tensors traversed from the consumer.

Comment (tlemo) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: This is very helpful - can we capture some of it as code comments?

**Comment by tlemo** [comment]
@naoyam, please run `nvfuser_bench` before & after this change and pay attention to the `LstmCell_Lower` numbers.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 6 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: Will do.

**Comment by naoyam** [comment]
> @naoyam, please run `nvfuser_bench` before & after this change and pay attention to the `LstmCell_Lower` numbers.

Here are the results on my workstation (Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz, TITAN RTX)

TOT:
```
-------------------------------------------------------------------------
Benchmark                                  Time           CPU Iterations
-------------------------------------------------------------------------
LstmCell_SetupFusion                      93 us         93 us       7527
LstmCell_AutoSchedule                  33050 us      33050 us         21
LstmCell_Lower                            47 ms         47 ms         15
LstmCell_Compile                         253 ms        251 ms          3
LstmCell_RunFusion/Small                  22 us         22 us      32374
LstmCell_RunFusion/Medium                 37 us         37 us      18499
LstmCell_RunFusion_CpuOnly/Small          12 us         12 us      59256
LstmCell_RunFusion_CpuOnly/Medium         11 us         11 us      59116
```

With this PR:
```
-------------------------------------------------------------------------
Benchmark                                  Time           CPU Iterations
-------------------------------------------------------------------------
LstmCell_SetupFusion                      92 us         92 us       7555
LstmCell_AutoSchedule                  32950 us      32950 us         21
LstmCell_Lower                            51 ms         51 ms         14
LstmCell_Compile                         166 ms        166 ms          4
LstmCell_RunFusion/Small                  22 us         22 us      32194
LstmCell_RunFusion/Medium                 37 us         37 us      18414
LstmCell_RunFusion_CpuOnly/Small          12 us         12 us      60023
LstmCell_RunFusion_CpuOnly/Medium         12 us         12 us      60049
```

The lowering time gets about 10% slower, which doesn't look good, but no optimization is done yet.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 6 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp:641]: Added. bad3543

File: torch/csrc/jit/codegen/cuda/index_compute.cpp [hunk 7]
```diff
@@ -572,9 +630,39 @@ generateIndexAndExtentMap(
...
+    if (producer_pushed && i == c2p_tv_stack.size() - 2) {
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/index_compute.cpp]: This should be safe here because of how the loop is structured, but I'm always hesitant to subtract from a uint. I'd generally feel safer with `i + 2 == c2p_tv_stack.size()`

**Review by csarofeen — APPROVED** [review]
Looks good to me, nice to see you extending your mapping into the indexing logic!

**Comment by csarofeen** [comment]
The latency increase is fine for this PR as this is a correctness fix by using the updated root mapping system.

One thing that might make this PR cleaner, if it makes sense, would be to store the root mapping object in the active GPU lower object as we can grab it with `GpuLower::current()`. That way it doesn't have to be piped through the codebase everywhere.

File: torch/csrc/jit/codegen/cuda/index_compute.cpp (hunk 7 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/index_compute.cpp]: Thanks. Agreed. Updated.

**Comment by tlemo** [comment]
> > @naoyam, please run `nvfuser_bench` before & after this change and pay attention to the `LstmCell_Lower` numbers.
> 
> Here are the results on my workstation (Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz, TITAN RTX)
> ...
> The lowering time gets about 10% slower, which doesn't look good, but no optimization is done yet.

Thanks for doing the measurements. Can you please open an issue to remind us to look for optimization opportunities when we get a chance?

**Review by tlemo — APPROVED** [review]

**Comment by naoyam** [comment]
Here's an issue on refactoring index lowering: #498. Please add any comments/suggestions.

**Comment by naoyam** [comment]
> > > @naoyam, please run `nvfuser_bench` before & after this change and pay attention to the `LstmCell_Lower` numbers.
> > 
> > 
> > Here are the results on my workstation (Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz, TITAN RTX)
> > ...
> > The lowering time gets about 10% slower, which doesn't look good, but no optimization is done yet.
> 
> Thanks for doing the measurements. Can you please open an issue to remind us to look for optimization opportunities when we get a chance?

Yes, see #499.
