### PR TITLE
Type Promotion Fixes

### LINKED ISSUE #1321: Issue with multiplying an `int32` Tensor and an Integer constant
## 🐛 Bug

```
def f(x):
  x = x * 2
  x = x * 2
  return x

size = 4
with torch.jit.fuser("fuser2"):
  f = torch.jit.script(f)
  inp = torch.ones(size, device='cuda', dtype=torch.int32)
  for _ in range(5):
    f(inp)
```

### PR DESCRIPTION
**Pull request by rdspring1**
Fixes #1321

### CODE REVIEW

**Review by csarofeen — COMMENTED** [review]
LGTM but uncertain what the type_promotion.cpp changes do, tagging @jjsjann123.

File: torch/csrc/jit/codegen/cuda/type_promotion.cpp [hunk 1]
```diff
@@ -195,11 +196,17 @@ std::vector<Val*> promoteValues(
 
 Val* optionalCast(DataType dtype, Val* v) {
   TORCH_INTERNAL_ASSERT(v->getDataType().has_value());
+  // Avoid casting Float and Int scalar values in fusion.
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/type_promotion.cpp]: nitpick, comment doesn't seem to match the implementation. We do "avoid casting Float scalar to specific FloatingPointType", but not "avoid casting float and int scalar values" in general.

**Review by jjsjann123 — APPROVED** [review]
LGTM
