### PR TITLE
Issue 1444

### LINKED ISSUE #1444: Scheduler asserts on pointwise kernel
### 🐛 Describe the bug

Error extracted from failures encountered in https://github.com/pytorch/pytorch/pull/71299

```
root@f3d8903f445f:/raid/playground# PYTORCH_NVFUSER_DISABLE_FALLBACK=1 python opinfo_failure_0.py

Traceback (most recent call last):
  File "opinfo_failure_0.py", line 19, in <module>
    outs = f(x, y, z)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Error adding cache_after T2_g[ iS2{i3}, iS3{i4} ] we restrict using cache_after on an output.
```

Python scripts:
```
import torch
import torch.nn as nn
from torch import Tensor
import time

@torch.jit.script
def f(t0, t1, t2):
  mask = t1.to(dtype=torch.bool)
  masked_input = torch.where(t0, mask, t2)
  return masked_input, mask

x = torch.randn(4, 4, device='cuda').to(dtype=torch.bool)
y = torch.randn(4, 4, device='cuda').to(dtype=torch.bool)
z = torch.tensor(1.0, device='cuda').to(dtype=torch.bool)
with torch.jit.fuser("fuser2"):
  for i in range(5):
    outs = f(x, y, z)
  print(f.graph_for(x, y, z))
  print(outs)
```

### Versions

reproed on devel branch
```
commit 16df2b8fa20c446766e27417e0a9d565b1784853 (HEAD, csarofeen/devel)
Author: Naoya Maruyama <naoyam@users.noreply.github.com>
Date:   Tue Feb 8 15:21:47 2022 -0800

    print 0-dim tensors as tensors (#1442)
```

### PR DESCRIPTION
**Pull request by csarofeen**
Avoid having arith return input tensor as it can cause parsing issues where a tensor that's marked as input is trivially marked as output.
Best effort try to support trivially marking output as input.
Fixes #1444

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/codegen.cpp [hunk 1]
```diff
@@ -59,23 +61,37 @@ class CudaKernelGenerator : private OptOutConstDispatch {
...
+    unsigned int duplicate_counter = 0;
+    for (auto i : c10::irange(params.size())) {
+      std::stringstream var_name_ss;
+      if (params[i]->isA<TensorView>()) {
+        var_name_ss << varName(params[i]->as<TensorView>());
+      } else {
+        var_name_ss << gen(params[i]);
+      }
+
+      // If value is duplicate in arguments just send a dummy val through
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/codegen.cpp]: The comment seems to suggest that we should `continue` in the true condition below.

**Review by jjsjann123 — APPROVED** [review]
LGTM, minor question on some comments.

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp [hunk 2]
```diff
@@ -588,15 +589,15 @@ void schedulePointwise(Fusion* fusion, const PointwiseParams& params) {
...
+    if (inp->uses().empty() || inp->isFusionOutput()) {
       continue;
     }
     cached_inputs.emplace_back(inp->cache_after());
   }
 
   // Figure out which outputs to cache for unrolling or vectorization
   for (auto out : output_tvs) {
-    if (out->definition() == nullptr) {
+    if (out->definition() == nullptr || out->isFusionInput()) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: Can a fusion input have a definition? Does that happen with a segmented fusion?

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: User could define operations to make a TV and then set that TV as an input. It'd be silly but definitely possible. Segmentation is done by copying the fusion and moving the inputs/outputs so yes, I believe it can.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: No, I'm wrong...
```.cpp
  // Returns the Expr that this value is an output of, returns nullptr if none
  // was found
  Expr* definition() const {
    if (is_fusion_input_) {
      return nullptr;
    }
    return definition_;
  }
```

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: But then, are those expressions preceding a fusion input considered part of the fusion? For example, `IterVisitor::traveres(Fusion*)` would traverse those pre-input expressions as well as it doesn't stop at fusion inputs, which may or may not make sense depending on use cases.

Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: Ah, commented before I saw your last comment.

File: torch/csrc/jit/codegen/cuda/scheduler/utils.cpp [hunk 3]
```diff
@@ -1032,7 +1035,7 @@ std::vector<std::pair<TensorView*, TensorView*>> cacheAndForkOutputs(
   // For intermediate outputs, apply cache_fork
   for (const auto output :
        ir_utils::filterByType<TensorView>(fusion->outputs())) {
-    if (output->definition() == nullptr) {
+    if (output->definition() == nullptr || output->isFusionInput()) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/scheduler/utils.cpp]: Is this also redundant?

File: torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp [hunk 4]
```diff
@@ -520,7 +520,8 @@ void schedulePointwise(Fusion* fusion, const PointwiseParams& params) {
   // For intermediate outputs, apply cache_fork
   auto outs = fusion->outputs();
   for (const auto output : outs) {
-    if (!output->uses().empty() && output->definition() != nullptr) {
+    if (!output->uses().empty() && output->definition() != nullptr &&
+        !output->isFusionInput()) {
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp]: Is this also redundant?

**Review by naoyam — APPROVED** [review]
