### PR TITLE
Setting maximum register usage for codegen kernel

### LINKED ISSUE #865: Normalization heuristics gives kernel that fails to launch
## 🐛 Bug

The normalization heuristics applies unroll for the schedule, which fails at launch due to register requests.

I dumped register usage in ptxas and the number runs fine for me.
I'm getting 130 register per thread, with a block size (448, 1, 1). So total register size is 58240, which is smaller than 64k.
However, when I add `--maxrregcount=90` it does compile and run. :confused: 

```
--- a/torch/csrc/jit/codegen/cuda/executor_utils.cpp
+++ b/torch/csrc/jit/codegen/cuda/executor_utils.cpp
@@ -668,6 +668,14 @@ NvrtcFunction nvrtcCompile(
 #endif
   }
 
+  args.push_back("--maxrregcount=90");
+
+  //args.push_back("--resource-usage");
+  // args.push_back("--ptxas-options --verbose");
+  args.push_back("--ptxas-options");
+  args.push_back("--verbose");
+
+
   // Add debug info to generated kernels
 #ifndef NDEBUG
   args.push_back("-G");
@@ -711,6 +719,13 @@ NvrtcFunction nvrtcCompile(
 
       TORCH_INTERNAL_ASSERT(
           false, code.c_str(), "\nCUDA NVRTC compile error: ", log.data());
+    } else {
+      size_t logsize;
+      at::globalContext().getNVRTC().nvrtcGetProgramLogSize(program, &logsize);
+      std::vector<char> log(logsize);
+      at::globalContext().getNVRTC().nvrtcGetProgramLog(program, log.data());
+
+      std::cout << "\nCUDA NVRTC compile log: " << log.data() << std::endl;
     }
```

## To Reproduce

https://github.com/csarofeen/pytorch/tree/BNBackward_launch_bound_repro
`./build/bin/test_jit --gtest_filter="*BNBackwardRepro3*"`

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #865 

A very small PR that limits the register usage to ensure that we do not request more register than available.
Two changes:
1. prior to kernel compilation, we bind the inputs at compile time to compute launch param (blocksize)
2. based on the compile-time blocksize, we calculate the maximum register size per thread and use `--maxrregcount` to restrict register usage for compiler

### CODE REVIEW

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 1]
```diff
@@ -672,6 +689,42 @@ NvrtcFunction nvrtcCompile(
...
+  std::string max_register_usage = "--maxrregcount=";
+  // TODO: double check the math with occupancy header
+  if (opt_block_size.has_value()) {
+    // int num_partition;
+    // cudaOccSubPartitionsPerMultiprocessor(&num_partition, prop);
+    // status = cudaOccRegAllocationGranularity(
+    //     &allocationGranularity,
+    //     properties);
+    int num_partition = 4;
+    int reg_allocation_granularity = 256;
```
Comment (naoyam) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp]: Is this because the granularity per thread is 8?

Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp]: Yes.

In the occupancy header, they were associating the granularity per warp as 256. Since we always have warp size 32, we can put it 8 per thread as well.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 2]
```diff
@@ -672,6 +689,42 @@ NvrtcFunction nvrtcCompile(
 #ifndef NDEBUG
   args.push_back("-lineinfo");
 #endif
+  args.push_back("-G");
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp]: Should we always be using `-G`?

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp [hunk 3]
```diff
@@ -672,6 +689,42 @@ NvrtcFunction nvrtcCompile(
...
+    int warp_size = 32;
+
+    int num_warps = ceilDiv(opt_block_size.value(), warp_size);
+    int max_warps_per_sm_partition = ceilDiv(num_warps, num_partition);
+
+    int hardware_warps_mem_check = roundUp(num_warps, num_partition);
+    int max_reg_per_warp = prop->regsPerBlock / hardware_warps_mem_check / reg_allocation_granularity * reg_allocation_granularity;
+    int max_register = max_reg_per_warp / warp_size;
+
+    max_register_usage += std::to_string(max_register);
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/executor_utils.cpp:704]: I'm really confused here why we care about partitions or warps in our register usage check. In my mind we should only be checking 2 things, register per thread is <255 and register per block usage is <65536 (x32-bit registers). I don't understand what else you're trying to check here.

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp [hunk 4]
```diff
@@ -393,14 +393,20 @@ std::vector<at::Tensor> FusionKernelRuntime::runKernelWithInput(
...
-  // Load launch params for reduction and normalization kernels
-  if (scheduler_entry->hasReductionParam()) {
-    launch_params = scheduler_entry->reductionParams().lparams;
+    // Load launch params for reduction and normalization kernels
+    if (scheduler_entry->hasReductionParam()) {
+      launch_params = scheduler_entry->reductionParams().lparams;
+    } else {
+      launch_params = scheduler_entry->pointwiseParams().lparams;
+    }
+    executors_[group_id].compileFusion(fusion_to_run.get(), options, inputs, launch_params);
```
Comment (csarofeen) [inline torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Not loving this interface now that requires inputs and launch params for compilation.

**Review by csarofeen — CHANGES_REQUESTED** [review]

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 3 above)
Comment (naoyam) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:704]: I think this is because register partitioning is done by each warp scheduler per SM. The number of warp schedulers is assumed as 4 here, which is I think true except for very old architectures, but we could make it more robust by checking the architecture version number.

I'm assuming Jie is still just prototyping this for now, but more detailed comments would be definitely helpful.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 2 above)
Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp]: this was to repro the register issue with cpp test. So I can have something to verify this actually works. Will remove it later.

File: torch/csrc/jit/codegen/cuda/executor_utils.cpp (hunk 3 above)
Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/executor_utils.cpp:704]: Naoya was right, there's a hardware check on register numbers, which assumes register allocations are made to all partitions (warp scheduler) simultaneously, so to simulate the hardware check, we round up the warp number to the number of partitions.

This was what's causing the error for us earlier.
We have 448 threads with 130 register per thread requested. On paper we have 448 * 130 = 60928 < 65536
but in reality, 130 register per thread is rounded to 136 register per thread (allocation granularity), while 448 threads -> 14 warps, rounded up to 16 warps (512 threads). So hardware check does 512 * 136 = 69632 > 65536 and it's failing the check.

I was copying the checks from `cuda_occupancy.h`, where they were doing the opposite logic.

File: torch/csrc/jit/codegen/cuda/kernel_cache.cpp (hunk 4 above)
Comment (jjsjann123) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: But this is only optional, as in:

  void compileFusion(Fusion* fusion, CompileOptions options = CompileOptions(),      const at::ArrayRef&lt;IValue&gt;&amp; inputs = {},      const LaunchParams&amp; launch_constraints = LaunchParams());

I agree this is still pretty ugly though :(
I only need to get the block size, but doing that requires a lowered kernel, which happens inside compileFusion. I can try to break it into two functions but I don't know if that would be a cleaner API

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/kernel_cache.cpp]: Yeah, I'll live ;-)

File: torch/csrc/jit/codegen/cuda/executor_launch_params.h [hunk 5]
```diff
@@ -37,11 +37,11 @@ class TORCH_CUDA_CU_API LaunchParams {
   }
 
   int64_t nBlocks() const {
-    return gdimx_ * gdimy_ * gdimz_;
+    return abs(gdimx_ * gdimy_ * gdimz_);
```
Comment (jjsjann123) [inline torch/csrc/jit/codegen/cuda/executor_launch_params.h:40]: We could have uninitialized value here that gives negative numbers.

Comment (csarofeen) [reply torch/csrc/jit/codegen/cuda/executor_launch_params.h:40]: Whoops, thanks

**Review by csarofeen — APPROVED** [review]
LGTM
